// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityOpenIdConnect.Generated.Health;
using SecurityOpenIdConnect.Generated.Me;
using SecurityOpenIdConnect.Generated.Resources;

namespace SecurityOpenIdConnect.Generated;

/// <summary>
/// Extension methods for registering all SecurityOpenIdConnect API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class SecurityOpenIdConnectEndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all SecurityOpenIdConnect API endpoint implementations from all path segments.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddSecurityOpenIdConnectEndpoints(this IServiceCollection services)
    {
        services.AddHealthEndpoints();
        services.AddMeEndpoints();
        services.AddResourcesEndpoints();

        return services;
    }
}