// <auto-generated />
import { ApiClient } from './ApiClient';
import type { User } from '../models';
import type { ApiError, ValidationError } from '../errors';

export type CreateUserResult =
  | { status: 'ok'; data: User; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type CreateUsersWithListInputResult =
  | { status: 'ok'; data: User; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type LoginUserResult =
  | { status: 'ok'; data: string; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type LogoutUserResult =
  | { status: 'ok'; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type GetUserByNameResult =
  | { status: 'ok'; data: User; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type UpdateUserResult =
  | { status: 'ok'; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type DeleteUserResult =
  | { status: 'ok'; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'unauthorized'; error: ApiError; response: Response }
  | { status: 'forbidden'; error: ApiError; response: Response }
  | { status: 'conflict'; error: ApiError; response: Response }
  | { status: 'unprocessableEntity'; error: ApiError; response: Response }
  | { status: 'tooManyRequests'; error: ApiError; response: Response }
  | { status: 'serverError'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class UserClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Create user. */
  async createUser(body: User): Promise<CreateUserResult> {
    return this.api.request<User>('POST', '/user', {
      body,
    }) as Promise<CreateUserResult>;
  }

  /** Creates list of users with given input array. */
  async createUsersWithListInput(body: User[]): Promise<CreateUsersWithListInputResult> {
    return this.api.request<User>('POST', '/user/createWithList', {
      body,
    }) as Promise<CreateUsersWithListInputResult>;
  }

  /** Logs user into the system. */
  async loginUser(query?: { username?: string; password?: string }): Promise<LoginUserResult> {
    return this.api.request<string>('GET', '/user/login', {
      query: {
        username: query?.username,
        password: query?.password,
      },
      responseType: 'text',
    }) as Promise<LoginUserResult>;
  }

  /** Logs out current logged in user session. */
  async logoutUser(): Promise<LogoutUserResult> {
    return this.api.request<void>('GET', '/user/logout') as Promise<LogoutUserResult>;
  }

  /** Get user by user name. */
  async getUserByName(username: string): Promise<GetUserByNameResult> {
    return this.api.request<User>('GET', `/user/${username}`) as Promise<GetUserByNameResult>;
  }

  /** Update user resource. */
  async updateUser(username: string, body: User): Promise<UpdateUserResult> {
    return this.api.request<void>('PUT', `/user/${username}`, {
      body,
    }) as Promise<UpdateUserResult>;
  }

  /** Delete user resource. */
  async deleteUser(username: string): Promise<DeleteUserResult> {
    return this.api.request<void>('DELETE', `/user/${username}`) as Promise<DeleteUserResult>;
  }
}