// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using VersioningUrlSegment.Generated.Owners.Endpoints.Results;

namespace VersioningUrlSegment.Generated.Owners.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all owners
/// Operation: ListOwners.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOwnersEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListOwnersEndpointResult> ExecuteAsync(
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default);
}