// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using Polymorphism.Generated;
using Polymorphism.Generated.Payments.Endpoints.Interfaces;
using Polymorphism.Generated.Payments.Endpoints.Results;
using Polymorphism.Generated.Payments.Models;
using Polymorphism.Generated.Payments.Client;

namespace Polymorphism.Generated.Payments.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Get a specific payment
/// Operation: GetPaymentById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class GetPaymentByIdEndpoint : IGetPaymentByIdEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public GetPaymentByIdEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<GetPaymentByIdEndpointResult> ExecuteAsync(
        GetPaymentByIdParameters parameters,
        string httpClientName = "Polymorphism-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/payments/{paymentId}");
        requestBuilder.WithPathParameter("paymentId", parameters.PaymentId);

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<PaymentMethod>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.NotFound);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new GetPaymentByIdEndpointResult(x), cancellationToken);
    }
}