// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Users.Client;
using PetStoreFull.Generated.Users.Endpoints.Results;

namespace PetStoreFull.Generated.Users.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Update user resource.
/// Operation: UpdateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUpdateUserEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<UpdateUserEndpointResult> ExecuteAsync(
        UpdateUserParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default);
}