// <auto-generated />
namespace PetStoreFull.Generated.Parameters;

public sealed record FindPetsByStatusParameters(
    [property: FromQuery(Name = "status"), Required, DefaultValue("available")] string Status = "available");