// <auto-generated />
namespace ModelsAndProperties.Generated.Models;

public record EnumTypes(
    GenderType GenderType,
    StatusType StatusType,
    ColorType ColorType,
    PriorityType PriorityType,
    string InlineEnum,
    RoleType RoleType);