// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using PetStoreSimple.Generated.Models;

namespace PetStoreSimple.Generated;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IPetStoreSimpleClient
{
    Task<List<Pet>> ListPetsAsync(
        ListPetsParameters parameters,
        CancellationToken cancellationToken = default);

    Task CreatePetsAsync(CancellationToken cancellationToken = default);

    Task<Pet> ShowPetByIdAsync(
        ShowPetByIdParameters parameters,
        CancellationToken cancellationToken = default);
}