// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using PetStoreSimple.Generated.Models;

namespace PetStoreSimple.Generated;

/// <summary>
/// Parameters for operation request.
/// Description: Info for a specific pet.
/// Operation: ShowPetById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ShowPetByIdParameters(
    [property: Required] string PetId);