// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using CircularSchemas.Generated.Models;
using CircularSchemas.Generated.Parameters;
using CircularSchemas.Generated.Results;

namespace CircularSchemas.Generated.Handlers;

/// <summary>
/// Get tree structure.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetTreeHandler
{
    Task<GetTreeResult> ExecuteAsync(CancellationToken cancellationToken = default);
}