// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using Polymorphism.Generated.Notifications.Handlers;
using Polymorphism.Generated.Payments.Handlers;
using Polymorphism.Generated.Shapes.Handlers;

namespace Polymorphism;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ApiHandlerServiceCollectionExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>
    /// The service collection for method chaining.
    /// </returns>
    public static IServiceCollection AddApiHandlersFromPolymorphism(this IServiceCollection services)
    {
        services.AddScoped<ICreatePaymentHandler, global::Polymorphism.ApiHandlers.CreatePaymentHandler>();
        services.AddScoped<IGetPaymentByIdHandler, global::Polymorphism.ApiHandlers.GetPaymentByIdHandler>();
        services.AddScoped<IListNotificationsHandler, global::Polymorphism.ApiHandlers.ListNotificationsHandler>();
        services.AddScoped<IListPaymentsHandler, global::Polymorphism.ApiHandlers.ListPaymentsHandler>();
        services.AddScoped<IListShapesHandler, global::Polymorphism.ApiHandlers.ListShapesHandler>();
        services.AddScoped<ISendNotificationHandler, global::Polymorphism.ApiHandlers.SendNotificationHandler>();

        return services;
    }
}