// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ArrayTypes } from '../models';

export type GetArrayTypesResult =
  | { status: 'ok'; data: ArrayTypes; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class ArraysClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getArrayTypes(): Promise<GetArrayTypesResult> {
    return this.api.request<ArrayTypes>('GET', '/arrays') as Promise<GetArrayTypesResult>;
  }
}