// <auto-generated />
import { ApiClient } from './ApiClient';
import type { NullableTypes } from '../models';

export type GetNullablesResult =
  | { status: 'ok'; data: NullableTypes; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class NullablesClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Get nullable types model */
  async getNullables(): Promise<GetNullablesResult> {
    return this.api.request<NullableTypes>('GET', '/nullables') as Promise<GetNullablesResult>;
  }
}