// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { Person } from '../models';
import type { GenderType } from '../enums';

export class PersonsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async listPersons(query?: { gender?: GenderType }): Promise<ApiResult<Person[]>> {
    return this.api.request<Person[]>('GET', '/persons', {
      query: {
        gender: query?.gender,
      },
    });
  }
}