// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { StringFormats } from '../models';

export class StringFormatsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getStringFormats(): Promise<ApiResult<StringFormats>> {
    return this.api.request<StringFormats>('GET', '/string-formats');
  }
}