// <auto-generated />
namespace SecurityHybrid.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class SecurityHybridClient
{
    private readonly HttpClient httpClient;

    public SecurityHybridClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async Task<HealthStatus> GetHealthAsync(CancellationToken cancellationToken = default)
    {
        var url = "/public/health";
        return (await httpClient.GetFromJsonAsync<HealthStatus>(url, cancellationToken))!;
    }

    public async Task<Product[]> ListProductsAsync(CancellationToken cancellationToken = default)
    {
        var url = "/products";
        return (await httpClient.GetFromJsonAsync<Product[]>(url, cancellationToken))!;
    }

    public async Task<Product> GetProductByIdAsync(
        GetProductByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/products/{parameters.ProductId}";
        return (await httpClient.GetFromJsonAsync<Product>(url, cancellationToken))!;
    }

    public async Task<Order[]> ListOrdersAsync(CancellationToken cancellationToken = default)
    {
        var url = "/orders";
        return (await httpClient.GetFromJsonAsync<Order[]>(url, cancellationToken))!;
    }

    public async Task<Order> CreateOrderAsync(
        CreateOrderParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/orders";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Order>(cancellationToken: cancellationToken))!;
    }

    public async Task<Order> GetOrderByIdAsync(
        GetOrderByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/orders/{parameters.OrderId}";
        return (await httpClient.GetFromJsonAsync<Order>(url, cancellationToken))!;
    }

    public async Task DeleteOrderAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/orders/{parameters.OrderId}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async Task<AdminSettings> GetAdminSettingsAsync(CancellationToken cancellationToken = default)
    {
        var url = "/admin/settings";
        return (await httpClient.GetFromJsonAsync<AdminSettings>(url, cancellationToken))!;
    }

    public async Task<AdminSettings> UpdateAdminSettingsAsync(
        UpdateAdminSettingsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/admin/settings";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<AdminSettings>(cancellationToken: cancellationToken))!;
    }

    public async Task<ListReportsResponseItem[]> ListReportsAsync(CancellationToken cancellationToken = default)
    {
        var url = "/reports";
        return (await httpClient.GetFromJsonAsync<ListReportsResponseItem[]>(url, cancellationToken))!;
    }

    public async Task<GetOrderTrackingResponse> GetOrderTrackingAsync(
        GetOrderTrackingParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/orders/{parameters.OrderId}/tracking";
        return (await httpClient.GetFromJsonAsync<GetOrderTrackingResponse>(url, cancellationToken))!;
    }
}