namespace Atc.Rest.Api.Generator.Helpers;

/// <summary>
/// Helper class for building consistent file headers across code generators.
/// </summary>
public static class HeaderBuilder
{
    /// <summary>
    /// The standard auto-generated header comment.
    /// </summary>
    public const string AutoGeneratedComment = "// <auto-generated />";

    /// <summary>
    /// The nullable enable directive.
    /// </summary>
    public const string NullableEnable = "#nullable enable";

    /// <summary>
    /// Simple header with just auto-generated comment and nullable enable.
    /// Use this for files that don't need any using statements in the header.
    /// </summary>
    public const string Simple = "// <auto-generated />\r\n#nullable enable\r\n";

    /// <summary>
    /// Simple header with trailing newline for separation before namespace.
    /// </summary>
    public const string SimpleWithNewline = "// <auto-generated />\r\n#nullable enable\r\n\r\n";

    /// <summary>
    /// Builds a header with specific using statements.
    /// </summary>
    /// <param name="usings">The using namespaces to include.</param>
    /// <returns>The complete header string.</returns>
    public static string WithUsings(params string[] usings)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoGeneratedComment);
        sb.AppendLine(NullableEnable);
        sb.AppendLine();

        foreach (var ns in usings.OrderBy(GetSortOrder).ThenBy(u => u, StringComparer.Ordinal))
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        return sb.ToString();
    }

    /// <summary>
    /// Builds a header by analyzing content for required using statements.
    /// Delegates to UsingStatementHelper.BuildHeader for content analysis.
    /// </summary>
    /// <param name="content">The generated code content to analyze.</param>
    /// <param name="alwaysInclude">Namespaces to always include regardless of content.</param>
    /// <returns>The complete header string.</returns>
    public static string FromContent(
        string content,
        params string[] alwaysInclude)
        => UsingStatementHelper.BuildHeader(content, alwaysInclude);

    /// <summary>
    /// Builds a header for DI extension methods.
    /// </summary>
    /// <returns>The complete header string.</returns>
    public static string ForDependencyInjection()
        => WithUsings(
            "System.CodeDom.Compiler",
            "Microsoft.Extensions.DependencyInjection");

    /// <summary>
    /// Builds a header for FluentValidation DI extension methods.
    /// </summary>
    /// <returns>The complete header string.</returns>
    public static string ForValidatorDependencyInjection()
        => WithUsings(
            "System.CodeDom.Compiler",
            "FluentValidation",
            "Microsoft.Extensions.DependencyInjection");

    /// <summary>
    /// Builds a header for WebApplication extension methods.
    /// </summary>
    /// <returns>The complete header string.</returns>
    public static string ForWebApplicationExtensions()
        => WithUsings(
            "System.CodeDom.Compiler",
            "Microsoft.AspNetCore.Builder");

    /// <summary>
    /// Builds a header for handler interfaces.
    /// </summary>
    /// <returns>The complete header string.</returns>
    public static string ForHandlers()
        => Simple;

    /// <summary>
    /// Builds a header for model records (with optional additional using).
    /// </summary>
    /// <param name="additionalUsing">Optional additional using namespace.</param>
    /// <returns>The complete header string.</returns>
    public static string ForModels(string? additionalUsing = null)
        => string.IsNullOrEmpty(additionalUsing)
            ? Simple
            : WithUsings(additionalUsing!);

    /// <summary>
    /// Gets the sort order for a namespace to ensure consistent ordering.
    /// System.* first, then Microsoft.*, Asp.*, Atc.*, FluentValidation.*, Polly.*, then custom.
    /// </summary>
    private static int GetSortOrder(string ns)
    {
        if (ns.StartsWith("System", StringComparison.Ordinal))
        {
            return 0;
        }

        if (ns.StartsWith("Microsoft", StringComparison.Ordinal))
        {
            return 1;
        }

        if (ns.StartsWith("Asp.", StringComparison.Ordinal))
        {
            return 2;
        }

        if (ns.StartsWith("Atc.", StringComparison.Ordinal))
        {
            return 3;
        }

        if (ns.StartsWith("FluentValidation", StringComparison.Ordinal))
        {
            return 4;
        }

        if (ns.StartsWith("Polly", StringComparison.Ordinal))
        {
            return 5;
        }

        return 6;
    }
}