// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using Demo.Generated.Tests.Models;

namespace Demo.Generated.Tests.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Create with empty response.
/// Operation: CreateTestItemEmpty.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateTestItemEmptyParameters(
    [property: Required] CreateTestItemRequest Request);