// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using Demo.Generated.Users.Models;

namespace Demo.Generated.Users.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Create user.
/// Operation: CreateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateUserParameters(
    [property: Required] CreateUserRequest Request);