// <auto-generated />
namespace Demo.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class DemoClient
{
    private readonly HttpClient httpClient;

    public DemoClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async System.Threading.Tasks.Task<List<Account>> ListAccountsAsync(
        ListAccountsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts";
        var queryParams = new List<string>();

        if (parameters.Limit.HasValue)
        {
            queryParams.Add($"limit={parameters.Limit}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<List<Account>>(url, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<Account> CreateAccountAsync(
        CreateAccountParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Account>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<Account> GetAccountByIdAsync(
        GetAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        return (await httpClient.GetFromJsonAsync<Account>(url, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task DeleteAccountByIdAsync(
        DeleteAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task<Account> UpdateAccountByIdAsync(
        UpdateAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Account>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<PaginatedResult<Account>> ListPaginatedAccountsAsync(
        ListPaginatedAccountsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts/paginated";
        var queryParams = new List<string>();

        if (parameters.PageSize.HasValue)
        {
            queryParams.Add($"pageSize={parameters.PageSize}");
        }

        if (parameters.PageIndex.HasValue)
        {
            queryParams.Add($"pageIndex={parameters.PageIndex}");
        }

        if (!string.IsNullOrEmpty(parameters.QueryString))
        {
            queryParams.Add($"queryString={Uri.EscapeDataString(parameters.QueryString)}");
        }

        if (!string.IsNullOrEmpty(parameters.Continuation))
        {
            queryParams.Add($"continuation={Uri.EscapeDataString(parameters.Continuation)}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<PaginatedResult<Account>>(url, cancellationToken))!;
    }

    public async IAsyncEnumerable<Account> ListAsyncEnumerableAccountsAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var url = "/accounts/async-enumerable";
        var jsonOptions = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };

        using var response = await httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
        response.EnsureSuccessStatusCode();

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);

        await foreach (var item in JsonSerializer.DeserializeAsyncEnumerable<Account>(stream, jsonOptions, cancellationToken))
        {
            if (item != null)
            {
                yield return item;
            }
        }
    }

    public async System.Threading.Tasks.Task<List<Task>> ListTasksAsync(
        ListTasksParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tasks";
        var queryParams = new List<string>();

        if (parameters.Limit.HasValue)
        {
            queryParams.Add($"limit={parameters.Limit}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<List<Task>>(url, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task CreateTaskAsync(
        CreateTaskParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tasks";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task GetTaskByIdAsync(
        GetTaskByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/tasks/{Uri.EscapeDataString(parameters.TaskId)}";
        var response = await httpClient.GetAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task DeleteTaskByIdAsync(
        DeleteTaskByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/tasks/{Uri.EscapeDataString(parameters.TaskId)}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task UpdateTaskByIdAsync(
        UpdateTaskByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/tasks/{Uri.EscapeDataString(parameters.TaskId)}";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task<List<User>> ListUsersAsync(
        ListUsersParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/users";
        var queryParams = new List<string>();

        if (!string.IsNullOrEmpty(parameters.Search))
        {
            queryParams.Add($"search={Uri.EscapeDataString(parameters.Search)}");
        }

        if (!string.IsNullOrEmpty(parameters.Country))
        {
            queryParams.Add($"country={Uri.EscapeDataString(parameters.Country)}");
        }

        if (!string.IsNullOrEmpty(parameters.Role))
        {
            queryParams.Add($"role={Uri.EscapeDataString(parameters.Role)}");
        }

        if (parameters.IsActive.HasValue)
        {
            queryParams.Add($"isActive={parameters.IsActive}");
        }

        if (parameters.Limit.HasValue)
        {
            queryParams.Add($"limit={parameters.Limit}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<List<User>>(url, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<User> CreateUserAsync(
        CreateUserParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/users";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<User>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<User> GetUserByIdAsync(
        GetUserByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/users/{parameters.UserId}";
        return (await httpClient.GetFromJsonAsync<User>(url, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<User> UpdateUserByIdAsync(
        UpdateUserByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/users/{parameters.UserId}";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<User>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task DeleteUserByIdAsync(
        DeleteUserByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/users/{parameters.UserId}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task GetFileByIdAsync(
        GetFileByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/files/{Uri.EscapeDataString(parameters.Id)}";
        var response = await httpClient.GetAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task UploadFormDataFileAsync(
        UploadFormDataFileParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleObject";
        using var content = new MultipartFormDataContent();

        if (parameters.Request?.ItemName != null)
        {
            content.Add(new StringContent(parameters.Request.ItemName.ToString()!), "itemName");
        }

        if (parameters.Request?.File != null)
        {
            var fileContent = new StreamContent(parameters.Request.File);
            content.Add(fileContent, "file", "file");
        }

        if (parameters.Request?.Items != null)
        {
            foreach (var item in parameters.Request.Items)
            {
                content.Add(new StringContent(item?.ToString() ?? string.Empty), "items");
            }
        }


        var response = await httpClient.PostAsync(url, content, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task UploadFormDataFilesAsync(
        UploadFormDataFilesParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleObjectMultiFile";
        using var content = new MultipartFormDataContent();

        if (parameters.Request?.Files != null)
        {
            for (var i = 0; i < parameters.Request.Files.Count; i++)
            {
                var fileContent = new StreamContent(parameters.Request.Files[i]);
                content.Add(fileContent, "files", $"files_{i}");
            }
        }


        var response = await httpClient.PostAsync(url, content, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task UploadSingleFileAsFormDataAsync(
        UploadSingleFileAsFormDataParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleFile";

        using var content = new StreamContent(parameters.File!);
        content.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");

        var response = await httpClient.PostAsync(url, content, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task UploadMultiFilesAsFormDataAsync(
        UploadMultiFilesAsFormDataParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/multiFile";

        using var content = new MultipartFormDataContent();

        for (var i = 0; i < parameters.File!.Length; i++)
        {
            var streamContent = new StreamContent(parameters.File[i]);
            content.Add(streamContent, "files", $"file{i}");
        }

        var response = await httpClient.PostAsync(url, content, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async System.Threading.Tasks.Task<TestItem> CreateTestItemWithModelAsync(
        CreateTestItemWithModelParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tests/create/create-model";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<TestItem>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<Uri> CreateTestItemWithLocationHeaderAsync(
        CreateTestItemWithLocationHeaderParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tests/create/create-location-header";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return response.Headers.Location!;
    }

    public async System.Threading.Tasks.Task<Uri> CreateTestItemWithLocationInBodyAsync(
        CreateTestItemWithLocationInBodyParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tests/create/create-location-body";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Uri>(cancellationToken: cancellationToken))!;
    }

    public async System.Threading.Tasks.Task CreateTestItemEmptyAsync(
        CreateTestItemEmptyParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/tests/create/create-empty";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
    }
}