// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using RateLimit.Generated.Orders.Models;

namespace RateLimit.Generated.Orders.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Delete order (strict policy override).
/// Operation: DeleteOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record DeleteOrderParameters(
    [property: Required] Guid OrderId);