// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using RateLimit.Generated.Orders.Models;

namespace RateLimit.Generated.Orders.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Create order (orders-standard policy).
/// Operation: CreateOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateOrderParameters(
    [property: Required] CreateOrderRequest Request);