// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;

namespace NonJsonContent.Generated.Items.Client;

/// <summary>
/// Registration extensions for <see cref="IItemsClient"/>.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ItemsClientServiceCollectionExtensions
{
    /// <summary>
    /// Adds <see cref="ItemsClient"/> as <see cref="IItemsClient"/> using IHttpClientFactory.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional callback to configure the underlying <see cref="HttpClient"/>.</param>
    public static IHttpClientBuilder AddItemsClient(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null)
    {
        if (services is null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        // An explicit factory is used because the generated client exposes both a
        // (HttpClient) and a (HttpClient, JsonSerializerOptions) constructor, which
        // ActivatorUtilities cannot disambiguate on its own.
        if (configureClient is null)
        {
            return services.AddHttpClient<IItemsClient>()
                .AddTypedClient<IItemsClient>(
                    static (httpClient, _) => new ItemsClient(httpClient));
        }

        return services.AddHttpClient<IItemsClient>(configureClient)
            .AddTypedClient<IItemsClient>(
                static (httpClient, _) => new ItemsClient(httpClient));
    }
}