// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;

namespace NonJsonContent.Generated.Files.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IFilesClient
{
    Task<byte[]> DownloadFileAsync(
        DownloadFileParameters parameters,
        CancellationToken cancellationToken = default);
}