// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreSimple.Generated.Client;
using PetStoreSimple.Generated.Endpoints.Results;

namespace PetStoreSimple.Generated.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all pets
/// Operation: ListPets.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListPetsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListPetsEndpointResult> ExecuteAsync(
        ListPetsParameters parameters,
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default);
}