// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using DiscriminatorImprovements.Generated.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiscriminatorImprovements.Generated.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: Get an order.
/// Operation: GetOrderById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetOrderByIdParameters(
    [property: FromRoute(Name = "orderId"), Required] Guid OrderId);