// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using HttpMethods.Generated.Client;
using HttpMethods.Generated.Endpoints.Results;

namespace HttpMethods.Generated.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Query resources with a body
/// Operation: QueryResources.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IQueryResourcesEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<QueryResourcesEndpointResult> ExecuteAsync(
        QueryResourcesParameters parameters,
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default);
}