// <auto-generated />
import type { Country } from './Country';

/** Postal address with validation constraints */
export interface Address {
  /** Street name */
  readonly streetName: string;

  /** Street/house number */
  readonly streetNumber?: string | null;

  /** Postal/ZIP code */
  readonly postalCode: string;

  /** City name */
  readonly cityName: string;

  /** State or region */
  readonly state?: string | null;

  readonly country: Country;
}