// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using VersioningUrlSegment.Generated.Models;
using VersioningUrlSegment.Generated.Parameters;
using VersioningUrlSegment.Generated.Results;

namespace VersioningUrlSegment.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getPetById.
/// </summary>
public sealed class GetPetByIdHandler : IGetPetByIdHandler
{
    public Task<GetPetByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getPetById not implemented");
    }
}