// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Generated.Handlers;

/// <summary>
/// Delete purchase order by identifier.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteOrderHandler
{
    Task<DeleteOrderResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);
}