// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using RateLimit.Generated;
using RateLimit.Generated.Reports.Models;

namespace RateLimit.Generated.Reports.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List reports (sliding window)
/// Operation: ListReports.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListReportsEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsTooManyRequests { get; }

    bool IsInternalServerError { get; }

    IEnumerable<Report> OkContent { get; }

    ProblemDetails TooManyRequestsContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}