// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityStandard.Generated.Models;
using SecurityStandard.Generated.Parameters;
using SecurityStandard.Generated.Results;

namespace SecurityStandard.Generated.Handlers;

/// <summary>
/// Delete an order.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteOrderHandler
{
    Task<DeleteOrderResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);
}