// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using VersioningUrlSegment.Generated;
using VersioningUrlSegment.Generated.Pets.Endpoints.Interfaces;
using VersioningUrlSegment.Generated.Pets.Endpoints.Results;
using VersioningUrlSegment.Generated.Pets.Models;
using VersioningUrlSegment.Generated.Pets.Client;

namespace VersioningUrlSegment.Generated.Pets.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Create a new pet
/// Operation: CreatePet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class CreatePetEndpoint : ICreatePetEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public CreatePetEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<CreatePetEndpointResult> ExecuteAsync(
        CreatePetParameters parameters,
        string httpClientName = "VersioningUrlSegment-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/pets");
        requestBuilder.WithBody(parameters.Request);

        using var requestMessage = requestBuilder.Build(HttpMethod.Post);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Pet>(HttpStatusCode.Created);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Conflict);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new CreatePetEndpointResult(x), cancellationToken);
    }
}