// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Builder;

namespace PetStoreFull.Generated.Endpoints;

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapPetEndpoints(this WebApplication app)
    {
        new PetEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapStoreEndpoints(this WebApplication app)
    {
        new StoreEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapUserEndpoints(this WebApplication app)
    {
        new UserEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}