// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using HeaderParameters.Generated;
using HeaderParameters.Generated.Items.Endpoints.Interfaces;
using HeaderParameters.Generated.Items.Endpoints.Results;
using HeaderParameters.Generated.Items.Models;
using HeaderParameters.Generated.Items.Client;

namespace HeaderParameters.Generated.Items.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Get a specific item
/// Operation: GetItemById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class GetItemByIdEndpoint : IGetItemByIdEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public GetItemByIdEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<GetItemByIdEndpointResult> ExecuteAsync(
        GetItemByIdParameters parameters,
        string httpClientName = "HeaderParameters-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/items/{itemId}");
        requestBuilder.WithPathParameter("itemId", parameters.ItemId);
        if (parameters.RequestId != null)
        {
            requestBuilder.WithHeaderParameter("X-Request-Id", parameters.RequestId);
        }

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Item>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<Error>(HttpStatusCode.NotFound);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new GetItemByIdEndpointResult(x), cancellationToken);
    }
}