// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Polymorphism.Generated.Models;

/// <summary>
/// Discriminator-based JSON converter for <see cref="Notification"/>.
/// Dispatches on property 'kind' and falls back to
/// <see cref="EmailNotification"/> for unrecognized discriminator values.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class NotificationJsonConverter : JsonConverter<Notification>
{
    public override Notification? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var rawText = document.RootElement.GetRawText();

        string? discriminatorValue = null;
        if (document.RootElement.TryGetProperty("kind", out var discriminatorElement))
        {
            discriminatorValue = discriminatorElement.GetString();
        }

        return discriminatorValue switch
        {
            "EmailNotification" => JsonSerializer.Deserialize<EmailNotification>(rawText, options),
            "SmsNotification" => JsonSerializer.Deserialize<SmsNotification>(rawText, options),
            "PushNotification" => JsonSerializer.Deserialize<PushNotification>(rawText, options),
            _ => JsonSerializer.Deserialize<EmailNotification>(rawText, options),
        };
    }

    public override void Write(Utf8JsonWriter writer, Notification value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value, value.GetType(), options);
    }
}