// <auto-generated />
namespace CachingOutput.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCachingOutputHandlers(this IServiceCollection services)
    {
        // Handler for ICreateProductHandler must be registered in the Domain project
        // services.AddScoped<ICreateProductHandler, YourImplementation>();
        // Handler for IDeleteProductHandler must be registered in the Domain project
        // services.AddScoped<IDeleteProductHandler, YourImplementation>();
        // Handler for IGetHealthHandler must be registered in the Domain project
        // services.AddScoped<IGetHealthHandler, YourImplementation>();
        // Handler for IGetProductByIdHandler must be registered in the Domain project
        // services.AddScoped<IGetProductByIdHandler, YourImplementation>();
        // Handler for IListCategoriesHandler must be registered in the Domain project
        // services.AddScoped<IListCategoriesHandler, YourImplementation>();
        // Handler for IListProductsHandler must be registered in the Domain project
        // services.AddScoped<IListProductsHandler, YourImplementation>();

        return services;
    }
}