// <auto-generated />
namespace SecurityOpenIdConnect.Generated.Handlers;

/// <summary>
/// List user resources.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListResourcesHandler
{
    Task<ListResourcesResult> ExecuteAsync(CancellationToken cancellationToken = default);
}