// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client;
using Demo.Generated.Accounts.Models;

namespace Demo.Generated.Accounts.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all accounts async-enumerable
/// Operation: ListAsyncEnumerableAccounts.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListAsyncEnumerableAccountsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<StreamingEndpointResponse<Account>> ExecuteAsync(
        string httpClientName = "Demo-ApiClient",
        CancellationToken cancellationToken = default);
}
