// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using Demo.Generated;
using Demo.Generated.Accounts.Models;

namespace Demo.Generated.Accounts.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Update a specific account
/// Operation: UpdateAccountById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUpdateAccountByIdEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsNotFound { get; }

    bool IsBadRequest { get; }

    bool IsConflict { get; }

    bool IsInternalServerError { get; }

    Account OkContent { get; }

    ProblemDetails NotFoundContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}