// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.OutputCaching;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CachingOutput.Generated.Categories.Handlers;
using CachingOutput.Generated.Categories.Models;
using CachingOutput.Generated.Categories.Results;
using CachingOutput.Generated.Caching;

namespace CachingOutput.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Categories.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class CategoriesEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/categories";

    public void DefineEndpoints(WebApplication app)
    {
        var categories = app
            .MapGroup(ApiRouteBase)
            .WithTags("Categories")
            .CacheOutput(OutputCachePolicies.Categories);

        categories
            .MapGet("/", ListCategories)
            .WithName("ListCategories")
            .WithSummary("List categories with vary-by-header")
            .Produces<List<Category>>()
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> ListCategories(
        [FromServices] IListCategoriesHandler handler,
        CancellationToken cancellationToken)
        => ListCategoriesResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}