// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using OpenApi31Features.Generated.Documents.Models;
using OpenApi31Features.Generated.Documents.Parameters;
using OpenApi31Features.Generated.Documents.Results;

namespace OpenApi31Features.Generated.Documents.Handlers;


/// <summary>
/// Create a document with base64 content.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateDocumentHandler
{
    Task<CreateDocumentResult> ExecuteAsync(
        CreateDocumentParameters parameters,
        CancellationToken cancellationToken = default);
}