// <auto-generated />
namespace SecurityOpenIdConnect.Generated.Models;

public sealed record UserProfile(
    [property: Required] Guid Id,
    [property: Required, EmailAddress] string Email,
    string DisplayName,
    Uri Picture,
    bool EmailVerified);