// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using RateLimit.Generated;
using RateLimit.Generated.Orders.Models;

namespace RateLimit.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create order (orders-standard policy)
/// Operation: CreateOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOrderEndpointResult : IEndpointResponse
{
    bool IsCreated { get; }

    bool IsBadRequest { get; }

    bool IsConflict { get; }

    bool IsTooManyRequests { get; }

    bool IsInternalServerError { get; }

    Order CreatedContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails TooManyRequestsContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}