// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityStandard.Generated;
using SecurityStandard.Generated.Users.Models;

namespace SecurityStandard.Generated.Users.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List all users
/// Operation: ListUsers.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListUsersEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsInternalServerError { get; }

    IEnumerable<User> OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}