// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Tests.Client;
using Demo.Generated.Tests.Endpoints.Results;

namespace Demo.Generated.Tests.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Create with empty response
/// Operation: CreateTestItemEmpty.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateTestItemEmptyEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<CreateTestItemEmptyEndpointResult> ExecuteAsync(
        CreateTestItemEmptyParameters parameters,
        string httpClientName = "Demo-ApiClient",
        CancellationToken cancellationToken = default);
}