// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using Demo.Generated;
using Demo.Generated.Files.Endpoints.Interfaces;
using Demo.Generated.Files.Client;

namespace Demo.Generated.Files.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Get File By Id
/// Operation: GetFileById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class GetFileByIdEndpoint : IGetFileByIdEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public GetFileByIdEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<BinaryEndpointResponse> ExecuteAsync(
        GetFileByIdParameters parameters,
        string httpClientName = "Demo-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/files/{id}");
        requestBuilder.WithPathParameter("id", parameters.Id);

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        return await responseBuilder.BuildBinaryResponseAsync(cancellationToken);
    }
}