// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace PetStoreFull.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ApiResponse(
    int Code,
    string Type,
    string Message);