// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client.Options;
using Microsoft.Extensions.DependencyInjection;
using Polymorphism.Generated.Shapes.Endpoints;
using Polymorphism.Generated.Shapes.Endpoints.Interfaces;

namespace Polymorphism.Generated.Shapes;

/// <summary>
/// Extension methods for registering Shapes API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all Shapes API endpoint implementations.
    /// Also ensures IHttpMessageFactory and IContractSerializer are registered (from Atc.Rest.Client).
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddShapesEndpoints(this IServiceCollection services)
    {
        // Ensure Atc.Rest.Client core services are registered (IHttpMessageFactory, IContractSerializer)
        services.AddAtcRestClientCore();

        services.AddTransient<IListShapesEndpoint, ListShapesEndpoint>();

        return services;
    }
}