// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace CachingHybrid.Generated.Users.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateUserRequest(
    [property: EmailAddress] string Email,
    string Name,
    string Role);