// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using CachingHybrid.Generated.Users.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CachingHybrid.Generated.Users.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: List users with HybridCache.
/// Operation: ListUsers.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListUsersParameters(
    [property: FromQuery(Name = "search")] string? Search,
    [property: FromQuery(Name = "role")] string? Role,
    [property: FromQuery(Name = "limit"), DefaultValue(50)] int? Limit = 50);

/// <summary>
/// Parameters for operation request.
/// Description: Create user (no caching).
/// Operation: CreateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateUserParameters(
    [property: FromBody, Required] CreateUserRequest Request);

/// <summary>
/// Parameters for operation request.
/// Description: Get user by ID with HybridCache and sliding expiration.
/// Operation: GetUserById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetUserByIdParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId);

/// <summary>
/// Parameters for operation request.
/// Description: Update user (no caching).
/// Operation: UpdateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateUserParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId,
    [property: FromBody, Required] UpdateUserRequest Request);

/// <summary>
/// Parameters for operation request.
/// Description: Delete user (no caching).
/// Operation: DeleteUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record DeleteUserParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId);