// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using RateLimit.Generated.Exports.Models;

namespace RateLimit.Generated.Exports.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Create export (concurrency limited).
/// Operation: CreateExport.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateExportParameters(
    [property: Required] ExportRequest Request);