// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;

namespace RateLimit.Generated.Webhooks.Client;

/// <summary>
/// Registration extensions for <see cref="IWebhooksClient"/>.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class WebhooksClientServiceCollectionExtensions
{
    /// <summary>
    /// Adds <see cref="WebhooksClient"/> as <see cref="IWebhooksClient"/> using IHttpClientFactory.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional callback to configure the underlying <see cref="HttpClient"/>.</param>
    public static IHttpClientBuilder AddWebhooksClient(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null)
    {
        if (services is null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        // An explicit factory is used because the generated client exposes both a
        // (HttpClient) and a (HttpClient, JsonSerializerOptions) constructor, which
        // ActivatorUtilities cannot disambiguate on its own.
        if (configureClient is null)
        {
            return services.AddHttpClient<IWebhooksClient>()
                .AddTypedClient<IWebhooksClient>(
                    static (httpClient, _) => new WebhooksClient(httpClient));
        }

        return services.AddHttpClient<IWebhooksClient>(configureClient)
            .AddTypedClient<IWebhooksClient>(
                static (httpClient, _) => new WebhooksClient(httpClient));
    }
}