// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SecurityOpenIdConnect.Generated.Me.Handlers;
using SecurityOpenIdConnect.Generated.Me.Models;
using SecurityOpenIdConnect.Generated.Me.Results;

namespace SecurityOpenIdConnect.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Me.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class MeEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/me";

    public void DefineEndpoints(WebApplication app)
    {
        var me = app
            .MapGroup(ApiRouteBase)
            .WithTags("Me")
            .RequireAuthorization();

        me
            .MapGet("/", GetCurrentUser)
            .WithName("GetCurrentUser")
            .WithSummary("Get current user profile")
            .Produces<UserProfile>()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .RequireAuthorization(policy => policy
                .AddAuthenticationSchemes("oidc")
                .RequireAuthenticatedUser());

        me
            .MapGet("profile", GetCurrentUserProfile)
            .WithName("GetCurrentUserProfile")
            .WithSummary("Get detailed user profile")
            .Produces<UserProfile>()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .RequireAuthorization(policy => policy
                .AddAuthenticationSchemes("oidc")
                .RequireAuthenticatedUser());
    }

    internal async Task<IResult> GetCurrentUser(
        [FromServices] IGetCurrentUserHandler handler,
        CancellationToken cancellationToken)
        => GetCurrentUserResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));

    internal async Task<IResult> GetCurrentUserProfile(
        [FromServices] IGetCurrentUserProfileHandler handler,
        CancellationToken cancellationToken)
        => GetCurrentUserProfileResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}