// <auto-generated />
namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: uploadFormDataFile.
/// </summary>
public sealed class UploadFormDataFileHandler : IUploadFormDataFileHandler
{
    public Task<UploadFormDataFileResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("uploadFormDataFile not implemented");
    }
}