// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: uploadFormDataFiles.
/// </summary>
public sealed class UploadFormDataFilesHandler : IUploadFormDataFilesHandler
{
    public Task<UploadFormDataFilesResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("uploadFormDataFiles not implemented");
    }
}