// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Retry.Generated.Models;
using Retry.Generated.Parameters;
using Retry.Generated.Results;

namespace Retry.Generated.Handlers;

/// <summary>
/// Health check (global retry policy).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthHandler
{
    Task<GetHealthResult> ExecuteAsync(CancellationToken cancellationToken = default);
}