// <auto-generated />
import type { AxiosResponse } from 'axios';
import { ApiClient } from './ApiClient';
import type { Address } from '../models';

export type ListAddressesResult =
  | { status: 'ok'; data: Address[]; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export type CreateAddressResult =
  | { status: 'created'; data: Address; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export class AddressesClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** List addresses */
  async listAddresses(): Promise<ListAddressesResult> {
    return this.api.request<Address[]>('GET', '/addresses') as Promise<ListAddressesResult>;
  }

  /** Create address */
  async createAddress(body: Address): Promise<CreateAddressResult> {
    return this.api.request<Address>('POST', '/addresses', {
      body,
    }) as Promise<CreateAddressResult>;
  }
}