// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using Polymorphism.Generated.Notifications.Models;

namespace Polymorphism.Generated.Notifications.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface INotificationsClient
{
    Task SendNotificationAsync(
        SendNotificationParameters parameters,
        CancellationToken cancellationToken = default);

    Task<List<Notification>> ListNotificationsAsync(CancellationToken cancellationToken = default);
}