// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using VersioningQueryString.Generated;
using VersioningQueryString.Generated.Owners.Models;

namespace VersioningQueryString.Generated.Owners.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create a new owner
/// Operation: CreateOwner.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOwnerEndpointResult : IEndpointResponse
{
    bool IsCreated { get; }

    bool IsBadRequest { get; }

    bool IsConflict { get; }

    bool IsInternalServerError { get; }

    Owner CreatedContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}