// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using ReadOnlyWriteOnly.Generated.Models;

namespace ReadOnlyWriteOnly.Generated;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IReadOnlyWriteOnlyClient
{
    Task<User> CreateUserAsync(
        CreateUserParameters parameters,
        CancellationToken cancellationToken = default);

    Task<User> GetUserByIdAsync(
        GetUserByIdParameters parameters,
        CancellationToken cancellationToken = default);
}