// <auto-generated />
namespace CachingOutput.Generated.Handlers;

/// <summary>
/// List categories with vary-by-header.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListCategoriesHandler
{
    Task<ListCategoriesResult> ExecuteAsync(CancellationToken cancellationToken = default);
}