// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using HttpMethods.Generated;
using HttpMethods.Generated.Models;

namespace HttpMethods.Generated.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Link a resource (custom verb)
/// Operation: LinkResource.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ILinkResourceEndpointResult : IEndpointResponse
{
    bool IsNoContent { get; }

    bool IsInternalServerError { get; }

    bool IsGatewayTimeout { get; }

    ProblemDetails InternalServerErrorContent { get; }

    ProblemDetails GatewayTimeoutContent { get; }
}