// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using HttpMethods.Generated.Endpoints.Results;

namespace HttpMethods.Generated.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List resources
/// Operation: ListResources.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListResourcesEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListResourcesEndpointResult> ExecuteAsync(
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default);
}