// <auto-generated />
namespace VersioningHeader.Generated.Handlers;

/// <summary>
/// Delete a pet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeletePetHandler
{
    Task<DeletePetResult> ExecuteAsync(
        DeletePetParameters parameters,
        CancellationToken cancellationToken = default);
}