// <auto-generated />
namespace VersioningHeader.Generated.Handlers;

/// <summary>
/// Get a pet by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetPetByIdHandler
{
    Task<GetPetByIdResult> ExecuteAsync(
        GetPetByIdParameters parameters,
        CancellationToken cancellationToken = default);
}