// <auto-generated />
namespace Polymorphism.Generated.Models;

public record CreditCard : PaymentMethod(
    [property: Required] string Type,
    [property: Required, MinLength(13), MaxLength(19)] string CardNumber,
    [property: Required, RegularExpression(@"^\d{2}/\d{2}$")] string ExpiryDate,
    [property: MinLength(3), MaxLength(4)] string? Cvv,
    [property: MaxLength(100)] string? CardholderName);