// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using Retry.Generated.Models;
using Retry.Generated.Parameters;
using Retry.Generated.Results;

namespace Retry.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listOrders.
/// </summary>
public sealed class ListOrdersHandler : IListOrdersHandler
{
    public Task<ListOrdersResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listOrders not implemented");
    }
}