// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getUserByName.
/// </summary>
public sealed class GetUserByNameHandler : IGetUserByNameHandler
{
    public Task<GetUserByNameResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getUserByName not implemented");
    }
}