// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: updateUser.
/// </summary>
public sealed class UpdateUserHandler : IUpdateUserHandler
{
    public Task<UpdateUserResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("updateUser not implemented");
    }
}