// <auto-generated />
namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: updateUser.
/// </summary>
public sealed class UpdateUserHandler : IUpdateUserHandler
{
    public Task<UpdateUserResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("updateUser not implemented");
    }
}