// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityHybrid.Generated;
using SecurityHybrid.Generated.Public.Models;

namespace SecurityHybrid.Generated.Public.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Health check (public)
/// Operation: GetHealth.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsInternalServerError { get; }

    HealthStatus OkContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}