// <auto-generated />
import { ApiClient, type ApiClientOptions } from './ApiClient';
import { PetsClient } from './PetsClient';
import { UsersClient } from './UsersClient';

export class ApiService {
  readonly pets: PetsClient;
  readonly users: UsersClient;

  constructor(baseUrl: string, options?: ApiClientOptions) {
    const api = new ApiClient(baseUrl, options);
    this.pets = new PetsClient(api);
    this.users = new UsersClient(api);
  }
}