// <auto-generated />
namespace RateLimit.Generated.Handlers;

/// <summary>
/// Send notification (token bucket with queue).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ISendNotificationHandler
{
    Task<SendNotificationResult> ExecuteAsync(
        SendNotificationParameters parameters,
        CancellationToken cancellationToken = default);
}