// <auto-generated />
import type { AxiosResponse } from 'axios';
import { ApiClient } from './ApiClient';
import type { Product } from '../models';
import type { ApiError } from '../errors';

export type ListProductsResult =
  | { status: 'ok'; data: Product[]; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export type GetProductByIdResult =
  | { status: 'ok'; data: Product; response: AxiosResponse }
  | { status: 'notFound'; error: ApiError; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export class ProductsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async listProducts(): Promise<ListProductsResult> {
    return this.api.request<Product[]>('GET', '/products') as Promise<ListProductsResult>;
  }

  async getProductById(productId: string): Promise<GetProductByIdResult> {
    return this.api.request<Product>('GET', `/products/${productId}`) as Promise<GetProductByIdResult>;
  }
}