// <auto-generated />
namespace CachingHybrid.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddCachingHybridHandlers(this IServiceCollection services)
    {
        // Handler for ICreateUserHandler must be registered in the Domain project
        // services.AddScoped<ICreateUserHandler, YourImplementation>();
        // Handler for IDeleteUserHandler must be registered in the Domain project
        // services.AddScoped<IDeleteUserHandler, YourImplementation>();
        // Handler for IGetHealthHandler must be registered in the Domain project
        // services.AddScoped<IGetHealthHandler, YourImplementation>();
        // Handler for IGetSettingsHandler must be registered in the Domain project
        // services.AddScoped<IGetSettingsHandler, YourImplementation>();
        // Handler for IGetUserByIdHandler must be registered in the Domain project
        // services.AddScoped<IGetUserByIdHandler, YourImplementation>();
        // Handler for IListSessionsHandler must be registered in the Domain project
        // services.AddScoped<IListSessionsHandler, YourImplementation>();
        // Handler for IListUsersHandler must be registered in the Domain project
        // services.AddScoped<IListUsersHandler, YourImplementation>();
        // Handler for IUpdateUserHandler must be registered in the Domain project
        // services.AddScoped<IUpdateUserHandler, YourImplementation>();

        return services;
    }
}