// <auto-generated />
import { ApiClient } from './ApiClient';
import type { CreatePetRequest, Pet, UpdatePetRequest } from '../models';
import type { ApiError, ValidationError } from '../errors';

export type ListPetsResult =
  | { status: 'ok'; data: Pet[]; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type CreatePetResult =
  | { status: 'created'; data: Pet; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type GetPetByIdResult =
  | { status: 'ok'; data: Pet; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type UpdatePetResult =
  | { status: 'ok'; data: Pet; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type DeletePetResult =
  | { status: 'noContent'; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class PetsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** List all pets */
  async listPets(query?: { limit?: number }): Promise<ListPetsResult> {
    return this.api.request<Pet[]>('GET', '/pets', {
      query: {
        limit: query?.limit,
      },
    }) as Promise<ListPetsResult>;
  }

  /** Create a new pet */
  async createPet(body: CreatePetRequest): Promise<CreatePetResult> {
    return this.api.request<Pet>('POST', '/pets', {
      body,
    }) as Promise<CreatePetResult>;
  }

  /** Get a pet by ID */
  async getPetById(petId: string): Promise<GetPetByIdResult> {
    return this.api.request<Pet>('GET', `/pets/${petId}`) as Promise<GetPetByIdResult>;
  }

  /** Update a pet */
  async updatePet(petId: string, body: UpdatePetRequest): Promise<UpdatePetResult> {
    return this.api.request<Pet>('PUT', `/pets/${petId}`, {
      body,
    }) as Promise<UpdatePetResult>;
  }

  /** Delete a pet */
  async deletePet(petId: string): Promise<DeletePetResult> {
    return this.api.request<void>('DELETE', `/pets/${petId}`) as Promise<DeletePetResult>;
  }
}