// <auto-generated />
namespace RateLimit.Generated.Handlers;

/// <summary>
/// Health check (global rate limit).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthHandler
{
    Task<GetHealthResult> ExecuteAsync(CancellationToken cancellationToken = default);
}