namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptApiServiceExtractorTests
{
    [Fact]
    public void Generate_NullClientList_Throws()
    {
        Assert.Throws<ArgumentNullException>(
            () => TypeScriptApiServiceExtractor.Generate(headerContent: null, clientClassNames: null!));
    }

    [Fact]
    public void Generate_ImportsApiClientAndOptions()
    {
        var result = TypeScriptApiServiceExtractor.Generate(headerContent: null, clientClassNames: []);

        Assert.Contains("import { ApiClient, type ApiClientOptions } from './ApiClient';", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_PerSegmentClient_GetsImportAndReadonlyProperty()
    {
        var clients = new List<string> { "AccountsClient", "UsersClient" };

        var result = TypeScriptApiServiceExtractor.Generate(headerContent: null, clients);

        Assert.Contains("import { AccountsClient } from './AccountsClient';", result, StringComparison.Ordinal);
        Assert.Contains("import { UsersClient } from './UsersClient';", result, StringComparison.Ordinal);

        // Property names are camel-cased segment names (Client suffix dropped).
        Assert.Contains("readonly accounts: AccountsClient;", result, StringComparison.Ordinal);
        Assert.Contains("readonly users: UsersClient;", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ConstructorAcceptsBaseUrlAndOptionsAndConstructsApiClient()
    {
        var result = TypeScriptApiServiceExtractor.Generate(headerContent: null, clientClassNames: ["FilesClient"]);

        Assert.Contains("constructor(baseUrl: string, options?: ApiClientOptions)", result, StringComparison.Ordinal);
        Assert.Contains("const api = new ApiClient(baseUrl, options);", result, StringComparison.Ordinal);
        Assert.Contains("this.files = new FilesClient(api);", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_HeaderContent_PrependedWhenProvided()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptApiServiceExtractor.Generate(header, clientClassNames: []);

        Assert.StartsWith(header, result, StringComparison.Ordinal);
    }
}