namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptMswHandlerExtractorTests
{
    private const string PetStoreYaml = """
                                        openapi: 3.0.0
                                        info:
                                          title: T
                                          version: 1.0.0
                                        paths:
                                          /pets:
                                            get:
                                              operationId: listPets
                                              responses:
                                                '200':
                                                  description: OK
                                                  content:
                                                    application/json:
                                                      schema:
                                                        type: array
                                                        items:
                                                          type: string
                                          /users:
                                            get:
                                              operationId: listUsers
                                              responses:
                                                '200':
                                                  description: OK
                                                  content:
                                                    application/json:
                                                      schema:
                                                        type: object
                                                        properties:
                                                          id: { type: string }
                                        """;

    [Fact]
    public void Extract_NullDocument_Throws()
    {
        Assert.Throws<ArgumentNullException>(
            () => TypeScriptMswHandlerExtractor.Extract(openApiDoc: null, headerContent: null, baseUrl: "/api", TypeScriptNamingStrategy.CamelCase));
    }

    [Fact]
    public void Extract_NoPaths_ReturnsEmpty()
    {
        var result = TypeScriptMswHandlerExtractor.Extract(new OpenApiDocument(), headerContent: null, baseUrl: "/api", TypeScriptNamingStrategy.CamelCase);

        Assert.Empty(result);
    }

    [Fact]
    public void Extract_PerSegmentHandlerFile_PlusCombinedIndex()
    {
        var doc = ParseYaml(PetStoreYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: "/api", TypeScriptNamingStrategy.CamelCase);

        // Two segments + one combined "handlers" index file = 3 outputs.
        Assert.Equal(3, result.Count);
        Assert.Contains(result, x => x.SegmentName == "Pets");
        Assert.Contains(result, x => x.SegmentName == "Users");
        Assert.Contains(result, x => x.SegmentName == "handlers");
    }

    [Fact]
    public void Extract_HandlerFile_UsesMswImports()
    {
        var doc = ParseYaml(PetStoreYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: "/api", TypeScriptNamingStrategy.CamelCase);

        var (_, content) = result.First(x => x.SegmentName == "Pets");
        Assert.Contains("from 'msw'", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Extract_HandlerFile_IncludesBaseUrlInRoute()
    {
        var doc = ParseYaml(PetStoreYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: "/api/v1", TypeScriptNamingStrategy.CamelCase);

        var (_, content) = result.First(x => x.SegmentName == "Pets");
        Assert.Contains("/api/v1", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Extract_HeaderContentPropagatesIntoEverySegmentFile()
    {
        const string header = "// <auto-generated />\n";
        var doc = ParseYaml(PetStoreYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, header, baseUrl: "/api", TypeScriptNamingStrategy.CamelCase);

        Assert.All(result, x => Assert.StartsWith(header, x.Content, StringComparison.Ordinal));
    }

    [Fact]
    public void Extract_QueryOperation_UsesHttpAllWithMethodGuard()
    {
        // MSW's http namespace exposes the standard verbs plus http.all — there is no
        // http.query, so deriving the handler name from the verb emitted a call to a
        // function that does not exist and broke the consumer's test suite at import time.
        var doc = ParseYaml(NonStandardVerbYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: string.Empty, TypeScriptNamingStrategy.CamelCase);

        var (_, content) = result.First(x => x.SegmentName == "Resources");

        Assert.DoesNotContain("http.query(", content, StringComparison.Ordinal);
        Assert.Contains("http.all('/resources', ({ request }) => {", content, StringComparison.Ordinal);
        Assert.Contains("if (request.method !== 'QUERY') return;", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Extract_CustomVerbOperation_UsesHttpAllWithMethodGuard()
    {
        var doc = ParseYaml(NonStandardVerbYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: string.Empty, TypeScriptNamingStrategy.CamelCase);

        var (_, content) = result.First(x => x.SegmentName == "Resources");

        Assert.DoesNotContain("http.link(", content, StringComparison.Ordinal);
        Assert.Contains("if (request.method !== 'LINK') return;", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Extract_StandardVerbOperation_KeepsDedicatedHttpHelper()
    {
        // The http.all fallback must not regress the standard verbs — those keep the
        // dedicated helper, which is both idiomatic MSW and narrower matching.
        var doc = ParseYaml(NonStandardVerbYaml);
        Assert.NotNull(doc);

        var result = TypeScriptMswHandlerExtractor.Extract(doc, headerContent: null, baseUrl: string.Empty, TypeScriptNamingStrategy.CamelCase);

        var (_, content) = result.First(x => x.SegmentName == "Resources");

        Assert.Contains("http.get('/resources', () => {", content, StringComparison.Ordinal);
    }

    private const string NonStandardVerbYaml = """
                                               openapi: 3.2.0
                                               info: { title: T, version: 1.0.0 }
                                               paths:
                                                 /resources:
                                                   get:
                                                     operationId: listResources
                                                     responses:
                                                       '200':
                                                         description: OK
                                                         content:
                                                           application/json:
                                                             schema:
                                                               type: array
                                                               items: { type: string }
                                                   query:
                                                     operationId: queryResources
                                                     requestBody:
                                                       required: true
                                                       content:
                                                         application/json:
                                                           schema: { type: object }
                                                     responses:
                                                       '200':
                                                         description: OK
                                                         content:
                                                           application/json:
                                                             schema:
                                                               type: array
                                                               items: { type: string }
                                                   additionalOperations:
                                                     LINK:
                                                       operationId: linkResource
                                                       responses:
                                                         '204': { description: Linked }
                                               """;

    private static OpenApiDocument? ParseYaml(string yaml)
        => OpenApiDocumentHelper.TryParseYaml(yaml, "test.yaml", out var document)
            ? document
            : null;
}