namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptBarrelExportExtractorTests
{
    [Fact]
    public void Create_OrdersTypeNamesAlphabetically()
    {
        var result = TypeScriptBarrelExportExtractor.Create(headerContent: null, ["Banana", "Apple", "Cherry"]);

        // Stable ordinal ordering keeps the index.ts diff-noise free across runs.
        Assert.NotNull(result.Exports);
        var modules = result.Exports!.Select(e => e.ModulePath).ToList();
        Assert.Equal(["./Apple", "./Banana", "./Cherry"], modules);
    }

    [Fact]
    public void Create_DefaultIsTypeOnly()
    {
        var result = TypeScriptBarrelExportExtractor.Create(headerContent: null, ["Apple"]);

        Assert.NotNull(result.Exports);
        Assert.All(result.Exports!, export => Assert.True(export.IsTypeOnly));
    }

    [Fact]
    public void Create_IsTypeOnlyFalse_GeneratesValueExports()
    {
        var result = TypeScriptBarrelExportExtractor.Create(headerContent: null, ["Apple"], isTypeOnly: false);

        Assert.NotNull(result.Exports);
        Assert.All(result.Exports!, export => Assert.False(export.IsTypeOnly));
    }

    [Fact]
    public void CreateWithZod_InterleavesMainAndZodReExports()
    {
        // For each name we expect two consecutive exports: ./Name then ./Name.zod.
        var result = TypeScriptBarrelExportExtractor.CreateWithZod(headerContent: null, ["Account", "User"]);

        Assert.NotNull(result.Exports);
        var modules = result.Exports!.Select(e => e.ModulePath).ToList();
        Assert.Equal(["./Account", "./Account.zod", "./User", "./User.zod"], modules);
    }

    [Fact]
    public void CreateWithZod_ZodReExportsAreNeverTypeOnly()
    {
        // Zod schemas are runtime const values — type-only re-exports would erase them at runtime.
        var result = TypeScriptBarrelExportExtractor.CreateWithZod(headerContent: null, ["Account"]);

        Assert.NotNull(result.Exports);
        var zodExport = result.Exports!.Single(e => e.ModulePath.EndsWith(".zod", StringComparison.Ordinal));
        Assert.False(zodExport.IsTypeOnly);
    }

    [Fact]
    public void CreateForSubdirectories_NonTypeOnlyExports()
    {
        var result = TypeScriptBarrelExportExtractor.CreateForSubdirectories(headerContent: null, ["models", "enums", "client"]);

        Assert.NotNull(result.Exports);
        var modules = result.Exports!.Select(e => e.ModulePath).ToList();
        Assert.Equal(["./client", "./enums", "./models"], modules);
        Assert.All(result.Exports!, export => Assert.False(export.IsTypeOnly));
    }

    [Fact]
    public void Create_ForwardsHeaderContentVerbatim()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptBarrelExportExtractor.Create(header, ["Apple"]);

        Assert.Equal(header, result.HeaderContent);
    }
}