namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptPaginationHelperExtractorTests
{
    [Fact]
    public void Generate_EmitsPaginatedResponseInterface()
    {
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        // Both `results` and `items` accommodate the two common server-side conventions.
        Assert.Contains("export interface PaginatedResponse<T>", result, StringComparison.Ordinal);
        Assert.Contains("readonly results?: T[];", result, StringComparison.Ordinal);
        Assert.Contains("readonly items?: T[];", result, StringComparison.Ordinal);
        Assert.Contains("readonly continuation?: string | null;", result, StringComparison.Ordinal);
        Assert.Contains("readonly pageIndex?: number;", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_EmitsPaginateAllAsyncGenerator()
    {
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        Assert.Contains("export async function* paginateAll<T, P extends Record<string, unknown>>", result, StringComparison.Ordinal);
        Assert.Contains("AsyncGenerator<T>", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_PaginateAll_AdvancesByContinuationOrPageIndex()
    {
        // The auto-paginator must support both pagination styles — losing either branch
        // hangs the iteration on real-world APIs.
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        Assert.Contains("if (page.continuation)", result, StringComparison.Ordinal);
        Assert.Contains("page.pageIndex !== undefined", result, StringComparison.Ordinal);
        Assert.Contains("page.pageIndex + 1", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_PaginateAll_StopsOnNonOkStatus()
    {
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        Assert.Contains("result.status !== 'ok' && result.status !== 'created'", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_EmitsCollectAllConvenience()
    {
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        Assert.Contains("export async function collectAll<T, P extends Record<string, unknown>>", result, StringComparison.Ordinal);
        Assert.Contains("Promise<T[]>", result, StringComparison.Ordinal);
        Assert.Contains("for await (const item of paginateAll(fetcher, initialParams))", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_HeaderContent_PrependedWhenProvided()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptPaginationHelperExtractor.Generate(header);

        Assert.StartsWith(header, result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_ImportsApiResultType()
    {
        var result = TypeScriptPaginationHelperExtractor.Generate(headerContent: null);

        Assert.Contains("import type { ApiResult } from '../types/ApiResult';", result, StringComparison.Ordinal);
    }
}