namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptErrorExtractorTests
{
    [Fact]
    public void GenerateApiError_FetchClient_NoAxiosImport()
    {
        var result = TypeScriptErrorExtractor.GenerateApiError(headerContent: null);

        Assert.Contains("export class ApiError extends Error", result, StringComparison.Ordinal);
        Assert.Contains("response?: Response", result, StringComparison.Ordinal);
        Assert.DoesNotContain("AxiosResponse", result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateApiError_AxiosClient_ImportsAndUsesAxiosResponse()
    {
        var result = TypeScriptErrorExtractor.GenerateApiError(headerContent: null, httpClient: TypeScriptHttpClient.Axios);

        Assert.Contains("import type { AxiosResponse } from 'axios';", result, StringComparison.Ordinal);
        Assert.Contains("response?: AxiosResponse", result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateApiError_ConstructorAssignsAllFields()
    {
        var result = TypeScriptErrorExtractor.GenerateApiError(headerContent: null);

        // The class is consumed by handleResponse — losing any of these fields silently
        // breaks consumer error handling.
        Assert.Contains("readonly status: number;", result, StringComparison.Ordinal);
        Assert.Contains("readonly statusText: string;", result, StringComparison.Ordinal);
        Assert.Contains("this.name = 'ApiError';", result, StringComparison.Ordinal);
        Assert.Contains("this.status = status;", result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateValidationError_ExtendsApiErrorAndAddsErrorsField()
    {
        var result = TypeScriptErrorExtractor.GenerateValidationError(headerContent: null);

        Assert.Contains("import { ApiError } from './ApiError';", result, StringComparison.Ordinal);
        Assert.Contains("export class ValidationError extends ApiError", result, StringComparison.Ordinal);
        Assert.Contains("readonly errors: Record<string, string[]>;", result, StringComparison.Ordinal);
        Assert.Contains("this.name = 'ValidationError';", result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateValidationError_AxiosClient_ImportsAxiosResponse()
    {
        var result = TypeScriptErrorExtractor.GenerateValidationError(headerContent: null, httpClient: TypeScriptHttpClient.Axios);

        Assert.Contains("import type { AxiosResponse } from 'axios';", result, StringComparison.Ordinal);
        Assert.Contains("response?: AxiosResponse", result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateApiError_HeaderContent_PrependedWhenProvided()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptErrorExtractor.GenerateApiError(header);

        Assert.StartsWith(header, result, StringComparison.Ordinal);
    }

    [Fact]
    public void GenerateValidationError_HeaderContent_PrependedWhenProvided()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptErrorExtractor.GenerateValidationError(header);

        Assert.StartsWith(header, result, StringComparison.Ordinal);
    }
}