namespace Atc.Rest.Api.Generator.Cli.Tests.Extractors.TypeScript;

public class TypeScriptApiResultExtractorTests
{
    [Fact]
    public void Generate_FetchClient_UsesNativeResponseType()
    {
        var result = TypeScriptApiResultExtractor.Generate(headerContent: null);

        // Fetch variant uses the native fetch Response type, NOT axios's AxiosResponse.
        Assert.Contains("response: Response", result, StringComparison.Ordinal);
        Assert.DoesNotContain("AxiosResponse", result, StringComparison.Ordinal);
        Assert.DoesNotContain("import type { AxiosResponse }", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_AxiosClient_ImportsAndUsesAxiosResponse()
    {
        var result = TypeScriptApiResultExtractor.Generate(headerContent: null, httpClient: TypeScriptHttpClient.Axios);

        Assert.Contains("import type { AxiosResponse } from 'axios';", result, StringComparison.Ordinal);
        Assert.Contains("response: AxiosResponse", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_DiscriminatedUnion_CoversAllExpectedStatuses()
    {
        var result = TypeScriptApiResultExtractor.Generate(headerContent: null);

        // Each status in the discriminated union must be represented — losing one
        // would silently break callers that switch on `result.status`.
        Assert.Contains("status: 'ok'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'created'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'noContent'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'badRequest'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'unauthorized'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'forbidden'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'notFound'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'conflict'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'unprocessableEntity'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'tooManyRequests'", result, StringComparison.Ordinal);
        Assert.Contains("status: 'serverError'", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_TypeGuards_EmittedForEachStatus()
    {
        var result = TypeScriptApiResultExtractor.Generate(headerContent: null);

        Assert.Contains("export function isOk<T>", result, StringComparison.Ordinal);
        Assert.Contains("export function isCreated<T>", result, StringComparison.Ordinal);
        Assert.Contains("export function isNoContent<T>", result, StringComparison.Ordinal);
        Assert.Contains("export function isBadRequest<T>", result, StringComparison.Ordinal);
        Assert.Contains("export function isServerError<T>", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_BadRequestGuard_NarrowsToValidationError()
    {
        var result = TypeScriptApiResultExtractor.Generate(headerContent: null);

        // 400 is the only status whose error type is ValidationError (carries field
        // errors); the other error guards narrow to ApiError.
        Assert.Contains("badRequest'; error: ValidationError", result, StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_HeaderContent_PrependedWhenProvided()
    {
        const string header = "// <auto-generated />\n";

        var result = TypeScriptApiResultExtractor.Generate(header);

        Assert.StartsWith(header, result, StringComparison.Ordinal);
    }
}