// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Demo.Generated.Tasks.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Generated.Tasks.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: List all tasks.
/// Operation: ListTasks.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListTasksParameters(
    [property: FromQuery(Name = "limit"), Range(long.MinValue, 100)] int? Limit);

/// <summary>
/// Parameters for operation request.
/// Description: Create task.
/// Operation: CreateTask.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateTaskParameters(
    [property: FromBody, Required] Demo.Generated.Tasks.Models.Task Request);

/// <summary>
/// Parameters for operation request.
/// Description: Get a specific task.
/// Operation: GetTaskById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetTaskByIdParameters(
    [property: FromRoute(Name = "taskId"), Required] string TaskId);

/// <summary>
/// Parameters for operation request.
/// Description: Delete a specific task.
/// Operation: DeleteTaskById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record DeleteTaskByIdParameters(
    [property: FromRoute(Name = "taskId"), Required] string TaskId);

/// <summary>
/// Parameters for operation request.
/// Description: Update a specific task.
/// Operation: UpdateTaskById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateTaskByIdParameters(
    [property: FromRoute(Name = "taskId"), Required] string TaskId,
    [property: FromBody, Required] Demo.Generated.Tasks.Models.Task Request);