// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Tasks.Models;
using Demo.Generated.Tasks.Parameters;
using Demo.Generated.Tasks.Results;

namespace Demo.Generated.Tasks.Handlers;


/// <summary>
/// List all tasks.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListTasksHandler
{
    System.Threading.Tasks.Task<ListTasksResult> ExecuteAsync(
        ListTasksParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Create task.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateTaskHandler
{
    System.Threading.Tasks.Task<CreateTaskResult> ExecuteAsync(
        CreateTaskParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Get a specific task.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetTaskByIdHandler
{
    System.Threading.Tasks.Task<GetTaskByIdResult> ExecuteAsync(
        GetTaskByIdParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Delete a specific task.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteTaskByIdHandler
{
    System.Threading.Tasks.Task<DeleteTaskByIdResult> ExecuteAsync(
        DeleteTaskByIdParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Update a specific task.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUpdateTaskByIdHandler
{
    System.Threading.Tasks.Task<UpdateTaskByIdResult> ExecuteAsync(
        UpdateTaskByIdParameters parameters,
        CancellationToken cancellationToken = default);
}