// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Demo.Generated.Users.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Generated.Users.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: List all users.
/// Operation: ListUsers.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListUsersParameters(
    [property: FromQuery(Name = "search")] string? Search,
    [property: FromQuery(Name = "country")] string? Country,
    [property: FromQuery(Name = "role")] ListUsersParametersRole? Role,
    [property: FromQuery(Name = "isActive")] bool? IsActive,
    [property: FromQuery(Name = "limit"), Range(1, 100), DefaultValue(25)] int? Limit = 25);

/// <summary>
/// Parameters for operation request.
/// Description: Create user.
/// Operation: CreateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateUserParameters(
    [property: FromBody, Required] CreateUserRequest Request);

/// <summary>
/// Parameters for operation request.
/// Description: Get a specific user.
/// Operation: GetUserById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetUserByIdParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId);

/// <summary>
/// Parameters for operation request.
/// Description: Update a specific user.
/// Operation: UpdateUserById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateUserByIdParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId,
    [property: FromBody, Required] UpdateUserRequest Request);

/// <summary>
/// Parameters for operation request.
/// Description: Delete a specific user.
/// Operation: DeleteUserById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record DeleteUserByIdParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId);