// <auto-generated />
/** Configuration for a retry policy. */
export interface RetryPolicy {
  /** Maximum number of retry attempts. */
  readonly maxAttempts: number;
  /** Initial delay between retries in milliseconds. */
  readonly delayMs: number;
  /** Backoff strategy: how delay increases between retries. */
  readonly backoff: 'constant' | 'linear' | 'exponential';
  /** Whether to add random jitter to retry delays. */
  readonly useJitter: boolean;
  /** Per-attempt timeout in milliseconds, or undefined for no timeout. */
  readonly timeoutMs?: number;
  /** Whether to handle 429 Too Many Requests with Retry-After header. */
  readonly handle429: boolean;
}

/** Named retry policies extracted from the OpenAPI specification. */
export const retryPolicies = {
  standard: {
    maxAttempts: 3,
    delayMs: 1000,
    backoff: 'exponential',
    useJitter: true,
    timeoutMs: 30000,
    handle429: true,
  } satisfies RetryPolicy,
  ordersFast: {
    maxAttempts: 2,
    delayMs: 500,
    backoff: 'exponential',
    useJitter: true,
    timeoutMs: 10000,
    handle429: true,
  } satisfies RetryPolicy,
  ordersDelete: {
    maxAttempts: 5,
    delayMs: 2000,
    backoff: 'exponential',
    useJitter: true,
    timeoutMs: 30000,
    handle429: true,
  } satisfies RetryPolicy,
  externalService: {
    maxAttempts: 5,
    delayMs: 3000,
    backoff: 'exponential',
    useJitter: true,
    timeoutMs: 60000,
    handle429: true,
  } satisfies RetryPolicy,
  notificationsConstant: {
    maxAttempts: 3,
    delayMs: 5000,
    backoff: 'constant',
    useJitter: false,
    timeoutMs: 30000,
    handle429: true,
  } satisfies RetryPolicy,
} as const;

/** Default retry policy ('standard'). */
export const defaultRetryPolicy: RetryPolicy = retryPolicies.standard;