// <auto-generated />
import type { DataOperation } from '../enums/DataOperation';

/** Data change webhook payload */
export interface DataChangeEvent {
  readonly id: string;

  /** Type of entity (e.g., "User", "Account", "Task") */
  readonly entityType: string;

  /** ID of the affected entity */
  readonly entityId: string;

  readonly operation: DataOperation;

  readonly timestamp: string;

  /** User who performed the operation */
  readonly performedBy?: string | null;

  /** Previous entity state as JSON string (for updates) */
  readonly previousValue?: string | null;

  /** New entity state as JSON string (for creates/updates) */
  readonly newValue?: string | null;
}