// <auto-generated />
namespace PetStoreSimple.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createPets.
/// </summary>
public sealed class CreatePetsHandler : ICreatePetsHandler
{
    public Task<CreatePetsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createPets not implemented");
    }
}