// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreSimple.Generated.Models;
using PetStoreSimple.Generated.Parameters;
using PetStoreSimple.Generated.Results;

namespace PetStoreSimple.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listPets.
/// </summary>
public sealed class ListPetsHandler : IListPetsHandler
{
    public Task<ListPetsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listPets not implemented");
    }
}