// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: deletePet.
/// </summary>
public sealed class DeletePetHandler : IDeletePetHandler
{
    public Task<DeletePetResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("deletePet not implemented");
    }
}