// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: findPetsByStatus.
/// </summary>
public sealed class FindPetsByStatusHandler : IFindPetsByStatusHandler
{
    public Task<FindPetsByStatusResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("findPetsByStatus not implemented");
    }
}