// <auto-generated />
namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: findPetsByTags.
/// </summary>
public sealed class FindPetsByTagsHandler : IFindPetsByTagsHandler
{
    public Task<FindPetsByTagsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("findPetsByTags not implemented");
    }
}