// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: updatePet.
/// </summary>
public sealed class UpdatePetHandler : IUpdatePetHandler
{
    public Task<UpdatePetResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("updatePet not implemented");
    }
}