// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using ComponentsReuse.Generated.Models;

namespace ComponentsReuse.Generated;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IComponentsReuseClient
{
    Task<List<Item>> ListItemsAsync(CancellationToken cancellationToken = default);

    Task<Item> GetItemByIdAsync(
        GetItemByIdParameters parameters,
        CancellationToken cancellationToken = default);
}