// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityAtcExt.Generated.Models;
using SecurityAtcExt.Generated.Parameters;
using SecurityAtcExt.Generated.Results;

namespace SecurityAtcExt.Generated.Handlers;

/// <summary>
/// List orders (requires auth).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersHandler
{
    Task<ListOrdersResult> ExecuteAsync(CancellationToken cancellationToken = default);
}