// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using OpenApi31Features.Generated.Models;
using OpenApi31Features.Generated.Parameters;
using OpenApi31Features.Generated.Results;

namespace OpenApi31Features.Generated.Handlers;

/// <summary>
/// Get coordinates.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetCoordinatesHandler
{
    Task<GetCoordinatesResult> ExecuteAsync(CancellationToken cancellationToken = default);
}