// <auto-generated />
namespace VersioningUrlSegment.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class VersioningUrlSegmentClient
{
    private readonly HttpClient httpClient;

    public VersioningUrlSegmentClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async Task<Pet[]> ListPetsAsync(
        ListPetsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/pets";
        var queryParams = new List<string>();

        if (parameters.Limit.HasValue)
        {
            queryParams.Add($"limit={parameters.Limit}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<Pet[]>(url, cancellationToken))!;
    }

    public async Task<Pet> CreatePetAsync(
        CreatePetParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/pets";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Pet>(cancellationToken: cancellationToken))!;
    }

    public async Task<Pet> GetPetByIdAsync(
        GetPetByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/pets/{parameters.PetId}";
        return (await httpClient.GetFromJsonAsync<Pet>(url, cancellationToken))!;
    }

    public async Task<Pet> UpdatePetAsync(
        UpdatePetParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/pets/{parameters.PetId}";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Pet>(cancellationToken: cancellationToken))!;
    }

    public async Task DeletePetAsync(
        DeletePetParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/pets/{parameters.PetId}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }

    public async Task<Owner[]> ListOwnersAsync(CancellationToken cancellationToken = default)
    {
        var url = "/owners";
        return (await httpClient.GetFromJsonAsync<Owner[]>(url, cancellationToken))!;
    }

    public async Task<Owner> CreateOwnerAsync(
        CreateOwnerParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/owners";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Owner>(cancellationToken: cancellationToken))!;
    }

    public async Task<Owner> GetOwnerByIdAsync(
        GetOwnerByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/owners/{parameters.OwnerId}";
        return (await httpClient.GetFromJsonAsync<Owner>(url, cancellationToken))!;
    }
}