// <auto-generated />
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using VersioningHeader.Generated.Models;

namespace VersioningHeader.Generated.Parameters;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListPetsParameters(
    [property: FromQuery(Name = "limit"), Range(long.MinValue, 100)] int? Limit);