// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;

namespace PetStoreFull.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IPetStoreFullClient
{
    Task<Pet> UpdatePetAsync(
        UpdatePetParameters parameters,
        CancellationToken cancellationToken = default);

    Task<Pet> AddPetAsync(
        AddPetParameters parameters,
        CancellationToken cancellationToken = default);

    Task<List<Pet>> FindPetsByStatusAsync(
        FindPetsByStatusParameters parameters,
        CancellationToken cancellationToken = default);

    Task<List<Pet>> FindPetsByTagsAsync(
        FindPetsByTagsParameters parameters,
        CancellationToken cancellationToken = default);

    Task<Pet> GetPetByIdAsync(
        GetPetByIdParameters parameters,
        CancellationToken cancellationToken = default);

    Task<Pet> UpdatePetWithFormAsync(
        UpdatePetWithFormParameters parameters,
        CancellationToken cancellationToken = default);

    Task DeletePetAsync(
        DeletePetParameters parameters,
        CancellationToken cancellationToken = default);

    Task<ApiResponse> UploadFileAsync(
        UploadFileParameters parameters,
        CancellationToken cancellationToken = default);

    Task<object> GetInventoryAsync(CancellationToken cancellationToken = default);

    Task<Order> PlaceOrderAsync(
        PlaceOrderParameters parameters,
        CancellationToken cancellationToken = default);

    Task<Order> GetOrderByIdAsync(
        GetOrderByIdParameters parameters,
        CancellationToken cancellationToken = default);

    Task DeleteOrderAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);

    Task<User> CreateUserAsync(
        CreateUserParameters parameters,
        CancellationToken cancellationToken = default);

    Task<User> CreateUsersWithListInputAsync(
        CreateUsersWithListInputParameters parameters,
        CancellationToken cancellationToken = default);

    Task<string> LoginUserAsync(
        LoginUserParameters parameters,
        CancellationToken cancellationToken = default);

    Task LogoutUserAsync(CancellationToken cancellationToken = default);

    Task<User> GetUserByNameAsync(
        GetUserByNameParameters parameters,
        CancellationToken cancellationToken = default);

    Task UpdateUserAsync(
        UpdateUserParameters parameters,
        CancellationToken cancellationToken = default);

    Task DeleteUserAsync(
        DeleteUserParameters parameters,
        CancellationToken cancellationToken = default);
}