// <auto-generated />
import { ApiClient } from './ApiClient';
import type { Pet } from '../models';
import type { ApiError, ValidationError } from '../errors';

export type ListPetsResult =
  | { status: 'ok'; data: Pet[]; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type CreatePetResult =
  | { status: 'created'; data: Pet; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type GetPetByIdResult =
  | { status: 'ok'; data: Pet; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class PetsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** List all pets */
  async listPets(): Promise<ListPetsResult> {
    return this.api.request<Pet[]>('GET', '/pets') as Promise<ListPetsResult>;
  }

  /** Create a pet */
  async createPet(body: Pet): Promise<CreatePetResult> {
    return this.api.request<Pet>('POST', '/pets', {
      body,
    }) as Promise<CreatePetResult>;
  }

  /** Get a pet by ID */
  async getPetById(petId: number): Promise<GetPetByIdResult> {
    return this.api.request<Pet>('GET', `/pets/${petId}`) as Promise<GetPetByIdResult>;
  }
}
