// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using SecurityHybrid.Generated;
using SecurityHybrid.Generated.Orders.Endpoints.Interfaces;
using SecurityHybrid.Generated.Orders.Endpoints.Results;
using SecurityHybrid.Generated.Orders.Models;
using SecurityHybrid.Generated.Orders.Client;

namespace SecurityHybrid.Generated.Orders.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Delete an order
/// Operation: DeleteOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class DeleteOrderEndpoint : IDeleteOrderEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public DeleteOrderEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<DeleteOrderEndpointResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        string httpClientName = "SecurityHybrid-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/orders/{orderId}");
        requestBuilder.WithPathParameter("orderId", parameters.OrderId);

        using var requestMessage = requestBuilder.Build(HttpMethod.Delete);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse(HttpStatusCode.NoContent);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.NotFound);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Forbidden);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new DeleteOrderEndpointResult(x), cancellationToken);
    }
}