// <auto-generated />
#nullable enable
using Microsoft.Extensions.DependencyInjection;
using ReadOnlyWriteOnly.Generated.Handlers;

namespace ReadOnlyWriteOnly.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddReadOnlyWriteOnlyHandlers(this IServiceCollection services)
    {
        // Handler for ICreateUserHandler must be registered in the Domain project
        // services.AddScoped<ICreateUserHandler, YourImplementation>();
        // Handler for IGetUserByIdHandler must be registered in the Domain project
        // services.AddScoped<IGetUserByIdHandler, YourImplementation>();

        return services;
    }
}