// <auto-generated />
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RateLimit.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ExportRequest(
    [property: Required] string Format,
    Dictionary<string, string>? Filters);