// <auto-generated />
import type { AxiosResponse } from 'axios';
import { ApiClient } from './ApiClient';
import type { PaymentRequest, PaymentResult } from '../models';
import type { ApiError } from '../errors';

export type ProcessPaymentResult =
  | { status: 'ok'; data: PaymentResult; response: AxiosResponse }
  | { status: 'serverError'; error: ApiError; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export class ExternalClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Process payment (circuit breaker enabled) */
  async processPayment(body: PaymentRequest): Promise<ProcessPaymentResult> {
    return this.api.request<PaymentResult>('POST', '/external/payment', {
      body,
    }) as Promise<ProcessPaymentResult>;
  }
}