// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using Demo.Generated.Users.Models;

namespace Demo.Generated.Users.Client;

/// <summary>
/// Parameters for operation request.
/// Description: List all users.
/// Operation: ListUsers.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListUsersParameters(
    string? Search,
    string? Country,
    ListUsersParametersRole? Role,
    bool? IsActive,
    [property: Range(1, 100), DefaultValue(25)] int? Limit = 25);