// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using Demo.Generated.Accounts.Models;

namespace Demo.Generated.Accounts.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Update a specific account.
/// Operation: UpdateAccountById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateAccountByIdParameters(
    [property: Required] string AccountId,
    [property: Required] Account Request);