// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using Demo.Generated.Files.Models;

namespace Demo.Generated.Files.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class FilesClient : IFilesClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public FilesClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public FilesClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async System.Threading.Tasks.Task<byte[]> GetFileByIdAsync(
        GetFileByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/files/{Uri.EscapeDataString(parameters.Id)}";
        var response = await httpClient.GetAsync(url, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
        return await response.Content.ReadAsByteArrayAsync(cancellationToken);
    }

    public async System.Threading.Tasks.Task UploadFormDataFileAsync(
        UploadFormDataFileParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleObject";
        using var content = new MultipartFormDataContent();

        if (parameters.Request?.ItemName is not null)
        {
            content.Add(new StringContent(parameters.Request.ItemName.ToString()!), "itemName");
        }

        if (parameters.Request?.File is not null)
        {
            var fileContent = new StreamContent(parameters.Request.File.OpenReadStream());

            if (parameters.Request.File.ContentType is not null)
            {
                fileContent.Headers.ContentType = new MediaTypeHeaderValue(parameters.Request.File.ContentType);
            }

            content.Add(fileContent, "file", parameters.Request.File.FileName);
        }

        if (parameters.Request?.Items is not null)
        {
            foreach (var item in parameters.Request.Items)
            {
                content.Add(new StringContent(item?.ToString() ?? string.Empty), "items");
            }
        }


        var response = await httpClient.PostAsync(url, content, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    public async System.Threading.Tasks.Task UploadFormDataFilesAsync(
        UploadFormDataFilesParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleObjectMultiFile";
        using var content = new MultipartFormDataContent();

        if (parameters.Request?.Files is not null)
        {
            for (var i = 0; i < parameters.Request.Files.Count; i++)
            {
                var fileItem = parameters.Request.Files[i];
                var fileContent = new StreamContent(fileItem.OpenReadStream());

                if (fileItem.ContentType is not null)
                {
                    fileContent.Headers.ContentType = new MediaTypeHeaderValue(fileItem.ContentType);
                }

                content.Add(fileContent, "files", fileItem.FileName);
            }
        }


        var response = await httpClient.PostAsync(url, content, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    public async System.Threading.Tasks.Task UploadSingleFileAsFormDataAsync(
        UploadSingleFileAsFormDataParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/singleFile";

        using var content = new StreamContent(parameters.File!.OpenReadStream());
        content.Headers.ContentType = new MediaTypeHeaderValue(parameters.File.ContentType ?? "application/octet-stream");

        var response = await httpClient.PostAsync(url, content, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    public async System.Threading.Tasks.Task UploadMultiFilesAsFormDataAsync(
        UploadMultiFilesAsFormDataParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/files/form-data/multiFile";

        using var content = new MultipartFormDataContent();

        for (var i = 0; i < parameters.File!.Length; i++)
        {
            var fileItem = parameters.File[i];
            var streamContent = new StreamContent(fileItem.OpenReadStream());

            if (fileItem.ContentType is not null)
            {
                streamContent.Headers.ContentType = new MediaTypeHeaderValue(fileItem.ContentType);
            }

            content.Add(streamContent, "files", fileItem.FileName);
        }

        var response = await httpClient.PostAsync(url, content, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}