// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;

namespace Demo.Generated.Tests.Client;

/// <summary>
/// Registration extensions for <see cref="ITestsClient"/>.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class TestsClientServiceCollectionExtensions
{
    /// <summary>
    /// Adds <see cref="TestsClient"/> as <see cref="ITestsClient"/> using IHttpClientFactory.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional callback to configure the underlying <see cref="HttpClient"/>.</param>
    public static IHttpClientBuilder AddTestsClient(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null)
    {
        if (services is null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        // An explicit factory is used because the generated client exposes both a
        // (HttpClient) and a (HttpClient, JsonSerializerOptions) constructor, which
        // ActivatorUtilities cannot disambiguate on its own.
        if (configureClient is null)
        {
            return services.AddHttpClient<ITestsClient>()
                .AddTypedClient<ITestsClient>(
                    static (httpClient, _) => new TestsClient(httpClient));
        }

        return services.AddHttpClient<ITestsClient>(configureClient)
            .AddTypedClient<ITestsClient>(
                static (httpClient, _) => new TestsClient(httpClient));
    }
}