// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using Demo.Generated.Accounts.Models;

namespace Demo.Generated.Accounts.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class AccountsClient : IAccountsClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public AccountsClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public AccountsClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async System.Threading.Tasks.Task<List<Account>> ListAccountsAsync(
        ListAccountsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts";
        var queryParams = new List<string>();

        if (parameters.Limit.HasValue)
        {
            queryParams.Add($"limit={parameters.Limit}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<List<Account>>(url, jsonSerializerOptions, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<Account> CreateAccountAsync(
        CreateAccountParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, jsonSerializerOptions, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
        return (await response.Content.ReadFromJsonAsync<Account>(jsonSerializerOptions, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<Account> GetAccountByIdAsync(
        GetAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        return (await httpClient.GetFromJsonAsync<Account>(url, jsonSerializerOptions, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task DeleteAccountByIdAsync(
        DeleteAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    public async System.Threading.Tasks.Task<Account> UpdateAccountByIdAsync(
        UpdateAccountByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/accounts/{Uri.EscapeDataString(parameters.AccountId)}";
        var response = await httpClient.PutAsJsonAsync(url, parameters.Request, jsonSerializerOptions, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
        return (await response.Content.ReadFromJsonAsync<Account>(jsonSerializerOptions, cancellationToken))!;
    }

    public async System.Threading.Tasks.Task<PaginatedResult<Account>> ListPaginatedAccountsAsync(
        ListPaginatedAccountsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/accounts/paginated";
        var queryParams = new List<string>();

        if (parameters.PageSize.HasValue)
        {
            queryParams.Add($"pageSize={parameters.PageSize}");
        }

        if (parameters.PageIndex.HasValue)
        {
            queryParams.Add($"pageIndex={parameters.PageIndex}");
        }

        if (!string.IsNullOrEmpty(parameters.QueryString))
        {
            queryParams.Add($"queryString={Uri.EscapeDataString(parameters.QueryString)}");
        }

        if (!string.IsNullOrEmpty(parameters.Continuation))
        {
            queryParams.Add($"continuation={Uri.EscapeDataString(parameters.Continuation)}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<PaginatedResult<Account>>(url, jsonSerializerOptions, cancellationToken))!;
    }

    public async IAsyncEnumerable<Account> ListAsyncEnumerableAccountsAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var url = "/accounts/async-enumerable";
        using var response = await httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);

        await foreach (var item in JsonSerializer.DeserializeAsyncEnumerable<Account>(stream, jsonSerializerOptions, cancellationToken))
        {
            if (item is not null)
            {
                yield return item;
            }
        }
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}