// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityStandard.Generated;
using SecurityStandard.Generated.Datas.Models;

namespace SecurityStandard.Generated.Datas.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Get data
/// Operation: GetData.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetDataEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    GetDataResponse OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails ForbiddenContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}