// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createTestItemWithLocationHeader.
/// </summary>
public sealed class CreateTestItemWithLocationHeaderHandler : ICreateTestItemWithLocationHeaderHandler
{
    public Task<CreateTestItemWithLocationHeaderResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createTestItemWithLocationHeader not implemented");
    }
}