// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createTestItemWithLocationInBody.
/// </summary>
public sealed class CreateTestItemWithLocationInBodyHandler : ICreateTestItemWithLocationInBodyHandler
{
    public Task<CreateTestItemWithLocationInBodyResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createTestItemWithLocationInBody not implemented");
    }
}