// <auto-generated />
import { ApiClient } from './ApiClient';
import type { AdminSettings } from '../models';

export type GetAdminSettingsResult =
  | { status: 'ok'; data: AdminSettings; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type UpdateAdminSettingsResult =
  | { status: 'ok'; data: AdminSettings; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class AdminClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Get admin settings */
  async getAdminSettings(): Promise<GetAdminSettingsResult> {
    return this.api.request<AdminSettings>('GET', '/admin/settings') as Promise<GetAdminSettingsResult>;
  }

  /** Update admin settings */
  async updateAdminSettings(body: AdminSettings): Promise<UpdateAdminSettingsResult> {
    return this.api.request<AdminSettings>('PUT', '/admin/settings', {
      body,
    }) as Promise<UpdateAdminSettingsResult>;
  }
}