// <auto-generated />
namespace OpenApi31Features.Generated.Webhooks.Handlers;

/// <summary>
/// Handler interface for the newPet webhook.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IOnNewPetWebhookHandler
{
    /// <summary>
    /// A new pet was added.
    /// </summary>
    Task<OnNewPetWebhookResult> ExecuteAsync(
        OnNewPetWebhookParameters parameters,
        CancellationToken cancellationToken = default);
}