// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using SecurityAtcExt.Generated;
using SecurityAtcExt.Generated.Orders.Endpoints.Interfaces;
using SecurityAtcExt.Generated.Orders.Endpoints.Results;
using SecurityAtcExt.Generated.Orders.Models;
using SecurityAtcExt.Generated.Orders.Client;

namespace SecurityAtcExt.Generated.Orders.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Create order (requires auth)
/// Operation: CreateOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class CreateOrderEndpoint : ICreateOrderEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public CreateOrderEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<CreateOrderEndpointResult> ExecuteAsync(
        CreateOrderParameters parameters,
        string httpClientName = "SecurityAtcExt-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/orders");
        requestBuilder.WithBody(parameters.Request);

        using var requestMessage = requestBuilder.Build(HttpMethod.Post);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Order>(HttpStatusCode.Created);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Conflict);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new CreateOrderEndpointResult(x), cancellationToken);
    }
}