// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using SecurityAtcExt.Generated;
using SecurityAtcExt.Generated.Orders.Endpoints.Interfaces;
using SecurityAtcExt.Generated.Orders.Endpoints.Results;
using SecurityAtcExt.Generated.Orders.Models;
using SecurityAtcExt.Generated.Orders.Client;

namespace SecurityAtcExt.Generated.Orders.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Get order (manager role inherited)
/// Operation: GetOrderById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class GetOrderByIdEndpoint : IGetOrderByIdEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public GetOrderByIdEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<GetOrderByIdEndpointResult> ExecuteAsync(
        GetOrderByIdParameters parameters,
        string httpClientName = "SecurityAtcExt-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/orders/{orderId}");
        requestBuilder.WithPathParameter("orderId", parameters.OrderId);

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Order>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.NotFound);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Forbidden);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new GetOrderByIdEndpointResult(x), cancellationToken);
    }
}