// <auto-generated />
namespace Demo.Generated.Handlers;

/// <summary>
/// Upload a file as OctetStream.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUploadSingleFileAsFormDataHandler
{
    System.Threading.Tasks.Task<UploadSingleFileAsFormDataResult> ExecuteAsync(
        UploadSingleFileAsFormDataParameters parameters,
        CancellationToken cancellationToken = default);
}