// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityHybrid.Generated.Public;
using SecurityHybrid.Generated.Products;
using SecurityHybrid.Generated.Orders;
using SecurityHybrid.Generated.Admin;
using SecurityHybrid.Generated.Reports;

namespace SecurityHybrid.Generated;

/// <summary>
/// Extension methods for registering all SecurityHybrid API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class SecurityHybridEndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all SecurityHybrid API endpoint implementations from all path segments.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddSecurityHybridEndpoints(this IServiceCollection services)
    {
        services.AddPublicEndpoints();
        services.AddProductsEndpoints();
        services.AddOrdersEndpoints();
        services.AddAdminEndpoints();
        services.AddReportsEndpoints();

        return services;
    }
}