// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace ModelsAndProperties.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record EnumTypes(
    GenderType GenderType,
    StatusType StatusType,
    ColorType ColorType,
    PriorityType PriorityType,
    string InlineEnum,
    RoleType RoleType);