// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using SecurityHybrid.Generated.Models;
using SecurityHybrid.Generated.Parameters;
using SecurityHybrid.Generated.Results;

namespace SecurityHybrid.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getHealth.
/// </summary>
public sealed class GetHealthHandler : IGetHealthHandler
{
    public Task<GetHealthResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getHealth not implemented");
    }
}