// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Demo.Generated.Models;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Generated.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: Create and return the created model.
/// Operation: CreateTestItemWithModel.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateTestItemWithModelParameters(
    [property: FromBody, Required] CreateTestItemRequest Request);