// <auto-generated />
namespace Demo.Generated.Models;

public sealed record FileAsFormDataRequest(
    [property: Required] string ItemName,
    IFormFile? File,
    [property: Required] List<string> Items);