// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using VersioningQueryString.Generated.Models;
using VersioningQueryString.Generated.Parameters;
using VersioningQueryString.Generated.Results;

namespace VersioningQueryString.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createPet.
/// </summary>
public sealed class CreatePetHandler : ICreatePetHandler
{
    public Task<CreatePetResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createPet not implemented");
    }
}