// <auto-generated />
namespace VersioningQueryString.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: updatePet.
/// </summary>
public sealed class UpdatePetHandler : IUpdatePetHandler
{
    public Task<UpdatePetResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("updatePet not implemented");
    }
}