// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { Shape } from '../models';

export class ShapesClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async listShapes(): Promise<ApiResult<Shape[]>> {
    return this.api.request<Shape[]>('GET', '/shapes');
  }
}