// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { Shape } from '../models';

export class ShapesClient {
  constructor(private readonly api: ApiClient) {}

  async listShapes(): Promise<ApiResult<Shape[]>> {
    return this.api.request<Shape[]>('GET', '/shapes');
  }
}