// <auto-generated />
namespace PetStoreFull.Generated.Parameters;

public sealed record UploadFileParameters(
    [property: FromRoute(Name = "petId"), Required] long PetId,
    [property: FromQuery(Name = "additionalMetadata")] string? AdditionalMetadata,
    [property: FromBody, Required] Stream File);