// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using Retry.Generated.Models;

namespace Retry.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IRetryClient
{
    Task<HealthStatus> GetHealthAsync(CancellationToken cancellationToken = default);

    Task<List<Order>> ListOrdersAsync(CancellationToken cancellationToken = default);

    Task<Order> CreateOrderAsync(
        CreateOrderParameters parameters,
        CancellationToken cancellationToken = default);

    Task<Order> GetOrderByIdAsync(
        GetOrderByIdParameters parameters,
        CancellationToken cancellationToken = default);

    Task DeleteOrderAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);

    Task<PaymentResult> ProcessPaymentAsync(
        ProcessPaymentParameters parameters,
        CancellationToken cancellationToken = default);

    Task GenerateReportAsync(
        GenerateReportParameters parameters,
        CancellationToken cancellationToken = default);

    Task SendNotificationAsync(
        SendNotificationParameters parameters,
        CancellationToken cancellationToken = default);
}