// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Store.Models;
using PetStoreFull.Generated.Store.Parameters;
using PetStoreFull.Generated.Store.Results;

namespace PetStoreFull.Generated.Store.Handlers;


/// <summary>
/// Returns pet inventories by status.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetInventoryHandler
{
    Task<GetInventoryResult> ExecuteAsync(CancellationToken cancellationToken = default);
}

/// <summary>
/// Place an order for a pet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IPlaceOrderHandler
{
    Task<PlaceOrderResult> ExecuteAsync(
        PlaceOrderParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Find purchase order by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOrderByIdHandler
{
    Task<GetOrderByIdResult> ExecuteAsync(
        GetOrderByIdParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Delete purchase order by identifier.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteOrderHandler
{
    Task<DeleteOrderResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);
}