openapi: 3.0.3
info:
  title: Multi-Part Demo API
  description: Demo API showcasing multi-part specification support
  version: 1.0.0
  contact:
    name: ATC Team
servers:
  - url: https://api.example.com/v1
    description: Production server
tags:
  - name: Users
    description: User management operations
  - name: Products
    description: Product management operations
components:
  schemas: {}
