// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getAccountById.
/// </summary>
public sealed class GetAccountByIdHandler : IGetAccountByIdHandler
{
    public Task<GetAccountByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getAccountById not implemented");
    }
}