// <auto-generated />
namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listPaginatedAccounts.
/// </summary>
public sealed class ListPaginatedAccountsHandler : IListPaginatedAccountsHandler
{
    public Task<ListPaginatedAccountsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listPaginatedAccounts not implemented");
    }
}