// <auto-generated />
namespace ModelsAndProperties.Generated.Handlers;

/// <summary>
/// List animals.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListAnimalsHandler
{
    Task<ListAnimalsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}