// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityStandard.Generated.Public;
using SecurityStandard.Generated.Orders;
using SecurityStandard.Generated.Users;
using SecurityStandard.Generated.Admin;
using SecurityStandard.Generated.Data;

namespace SecurityStandard.Generated;

/// <summary>
/// Extension methods for registering all SecurityStandard API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class SecurityStandardEndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all SecurityStandard API endpoint implementations from all path segments.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddSecurityStandardEndpoints(this IServiceCollection services)
    {
        services.AddPublicEndpoints();
        services.AddOrdersEndpoints();
        services.AddUsersEndpoints();
        services.AddAdminEndpoints();
        services.AddDataEndpoints();

        return services;
    }
}