// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityOpenIdConnect.Generated.Healths.Endpoints.Results;

namespace SecurityOpenIdConnect.Generated.Healths.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Health check (public)
/// Operation: GetHealth.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetHealthEndpointResult> ExecuteAsync(
        string httpClientName = "SecurityOpenIdConnect-ApiClient",
        CancellationToken cancellationToken = default);
}