// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityOpenIdConnect.Generated.Health.Handlers;
using SecurityOpenIdConnect.Generated.Me.Handlers;
using SecurityOpenIdConnect.Generated.Resources.Handlers;

namespace SecurityOpenIdConnect;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ApiHandlerServiceCollectionExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>
    /// The service collection for method chaining.
    /// </returns>
    public static IServiceCollection AddApiHandlersFromSecurityOpenIdConnect(this IServiceCollection services)
    {
        services.AddScoped<ICreateResourceHandler, global::SecurityOpenIdConnect.ApiHandlers.CreateResourceHandler>();
        services.AddScoped<IDeleteResourceHandler, global::SecurityOpenIdConnect.ApiHandlers.DeleteResourceHandler>();
        services.AddScoped<IGetCurrentUserHandler, global::SecurityOpenIdConnect.ApiHandlers.GetCurrentUserHandler>();
        services.AddScoped<IGetCurrentUserProfileHandler, global::SecurityOpenIdConnect.ApiHandlers.GetCurrentUserProfileHandler>();
        services.AddScoped<IGetHealthHandler, global::SecurityOpenIdConnect.ApiHandlers.GetHealthHandler>();
        services.AddScoped<IGetResourceByIdHandler, global::SecurityOpenIdConnect.ApiHandlers.GetResourceByIdHandler>();
        services.AddScoped<IListResourcesHandler, global::SecurityOpenIdConnect.ApiHandlers.ListResourcesHandler>();

        return services;
    }
}