// <auto-generated />
namespace RateLimit.Generated.Handlers;

/// <summary>
/// Create order (orders-standard policy).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOrderHandler
{
    Task<CreateOrderResult> ExecuteAsync(
        CreateOrderParameters parameters,
        CancellationToken cancellationToken = default);
}