// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using RateLimit.Generated.Models;
using RateLimit.Generated.Parameters;
using RateLimit.Generated.Results;

namespace RateLimit.Generated.Handlers;

/// <summary>
/// List orders (orders-standard policy).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersHandler
{
    Task<ListOrdersResult> ExecuteAsync(CancellationToken cancellationToken = default);
}