// <auto-generated />
export interface AddressRequest {
  readonly street: string;

  readonly city: string;

  readonly state?: string | null;

  readonly postalCode: string;

  readonly country: string;

  readonly countryCode?: string | null;

  readonly latitude?: number | null;

  readonly longitude?: number | null;
}