// <auto-generated />
import type { NotificationType } from '../enums/NotificationType';

/** Notification subscription */
export interface Subscription {
  readonly id: string;

  /** Optional friendly name for the subscription */
  readonly name?: string | null;

  /** Event types to subscribe to */
  readonly topics: NotificationType[];

  /** HTTP callback URL for webhook delivery (optional) */
  readonly callbackUrl?: string | null;

  /** SignalR connection ID for real-time delivery */
  readonly connectionId?: string | null;

  readonly isActive: boolean;

  readonly createdAt: string;

  /** Optional expiration time */
  readonly expiresAt?: string | null;

  readonly lastNotificationAt?: string | null;
}