// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using PetStoreFull.Generated;
using PetStoreFull.Generated.User.Models;

namespace PetStoreFull.Generated.User.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Logs out current logged in user session.
/// Operation: LogoutUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ILogoutUserEndpointResult : IEndpointResponse
{
    new bool IsOk { get; }

    bool IsInternalServerError { get; }

    ProblemDetails InternalServerErrorContent { get; }
}