// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityAtcExt.Generated.Reports.Models;
using SecurityAtcExt.Generated.Reports.Results;

namespace SecurityAtcExt.Generated.Reports.Handlers;


/// <summary>
/// List reports (admin OR manager).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListReportsHandler
{
    Task<ListReportsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}