// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Polymorphism.Generated.Models;
using Polymorphism.Generated.Parameters;
using Polymorphism.Generated.Results;

namespace Polymorphism.Generated.Handlers;

/// <summary>
/// Get a specific payment.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetPaymentByIdHandler
{
    Task<GetPaymentByIdResult> ExecuteAsync(
        GetPaymentByIdParameters parameters,
        CancellationToken cancellationToken = default);
}