// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityHybrid.Generated.Models;
using SecurityHybrid.Generated.Parameters;
using SecurityHybrid.Generated.Results;

namespace SecurityHybrid.Generated.Handlers;

/// <summary>
/// Health check (public).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthHandler
{
    Task<GetHealthResult> ExecuteAsync(CancellationToken cancellationToken = default);
}