// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using NonJsonContent.Generated.Exports.Results;

namespace NonJsonContent.Generated.Exports.Handlers;


/// <summary>
/// Export data as CSV.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IExportCsvHandler
{
    Task<ExportCsvResult> ExecuteAsync(CancellationToken cancellationToken = default);
}