// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using VersioningQueryString.Generated.Models;
using VersioningQueryString.Generated.Parameters;
using VersioningQueryString.Generated.Results;

namespace VersioningQueryString.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getOwnerById.
/// </summary>
public sealed class GetOwnerByIdHandler : IGetOwnerByIdHandler
{
    public Task<GetOwnerByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getOwnerById not implemented");
    }
}