// <auto-generated />
namespace Retry;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
public static class ServiceCollectionEndpointHandlerExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    public static IServiceCollection AddApiHandlersFromDomain(this IServiceCollection services)
    {
        services.AddScoped<IGetHealthHandler, GetHealthHandler>();
        services.AddScoped<IListOrdersHandler, ListOrdersHandler>();
        services.AddScoped<ICreateOrderHandler, CreateOrderHandler>();
        services.AddScoped<IGetOrderByIdHandler, GetOrderByIdHandler>();
        services.AddScoped<IDeleteOrderHandler, DeleteOrderHandler>();
        services.AddScoped<IProcessPaymentHandler, ProcessPaymentHandler>();
        services.AddScoped<IGenerateReportHandler, GenerateReportHandler>();
        services.AddScoped<ISendNotificationHandler, SendNotificationHandler>();

        return services;
    }
}