// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using OpenApi31Features.Generated.Coordinates.Models;
using OpenApi31Features.Generated.Models;

namespace OpenApi31Features.Generated.Coordinates.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICoordinatesClient
{
    Task<Coordinate> GetCoordinatesAsync(CancellationToken cancellationToken = default);

    Task<List<Coordinate>> ListCoordinatesAsync(CancellationToken cancellationToken = default);
}