// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Polymorphism.Generated.Notifications.Handlers;
using Polymorphism.Generated.Notifications.Models;
using Polymorphism.Generated.Notifications.Parameters;
using Polymorphism.Generated.Notifications.Results;

namespace Polymorphism.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Notifications.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class NotificationsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/notifications";

    public void DefineEndpoints(WebApplication app)
    {
        var notifications = app
            .MapGroup(ApiRouteBase)
            .WithTags("Notifications");

        notifications
            .MapPost("/", SendNotification)
            .WithName("SendNotification")
            .WithSummary("Send a notification")
            .Produces(StatusCodes.Status202Accepted)
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);

        notifications
            .MapGet("/", ListNotifications)
            .WithName("ListNotifications")
            .WithSummary("List all notifications")
            .Produces<List<Notification>>()
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> SendNotification(
        [FromServices] ISendNotificationHandler handler,
        [AsParameters] SendNotificationParameters parameters,
        CancellationToken cancellationToken)
        => SendNotificationResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async Task<IResult> ListNotifications(
        [FromServices] IListNotificationsHandler handler,
        CancellationToken cancellationToken)
        => ListNotificationsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}