// <auto-generated />
namespace CachingOutput.Generated.Models;

public sealed record CreateProductRequest(
    [property: Required] string Name,
    string Description,
    [property: Required] double Price,
    Guid CategoryId);