// <auto-generated />
namespace CachingOutput.Generated.Models;

public record Product(
    [property: Required] Guid Id,
    [property: Required] string Name,
    string Description,
    [property: Required] double Price,
    Guid CategoryId,
    DateTimeOffset CreatedAt);