// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { RgbColor } from '../models';

export class ColorsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getColors(): Promise<ApiResult<RgbColor>> {
    return this.api.request<RgbColor>('GET', '/colors');
  }
}