// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { Account, Accounts, PaginatedResult } from '../models';

export class AccountsClient {
  constructor(private readonly api: ApiClient) {}

  async listAccounts(query?: { limit?: number }): Promise<ApiResult<Accounts>> {
    return this.api.request<Accounts>('GET', '/accounts', {
      query: {
        limit: query?.limit,
      },
    });
  }

  async createAccount(body: Account): Promise<ApiResult<Account>> {
    return this.api.request<Account>('POST', '/accounts', {
      body,
    });
  }

  async getAccountById(accountId: string): Promise<ApiResult<Account>> {
    return this.api.request<Account>('GET', `/accounts/${accountId}`);
  }

  async deleteAccountById(accountId: string): Promise<ApiResult<void>> {
    return this.api.request<void>('DELETE', `/accounts/${accountId}`);
  }

  async updateAccountById(accountId: string, body: Account): Promise<ApiResult<Account>> {
    return this.api.request<Account>('PUT', `/accounts/${accountId}`, {
      body,
    });
  }

  async listPaginatedAccounts(query?: { pageSize?: number; pageIndex?: number; queryString?: string; continuation?: string }): Promise<ApiResult<PaginatedResult>> {
    return this.api.request<PaginatedResult>('GET', '/accounts/paginated', {
      query: {
        pageSize: query?.pageSize,
        pageIndex: query?.pageIndex,
        queryString: query?.queryString,
        continuation: query?.continuation,
      },
    });
  }

  async *listAsyncEnumerableAccounts(signal?: AbortSignal): AsyncGenerator<Account> {
    yield* this.api.requestStream<Account>('GET', '/accounts/async-enumerable', { signal });
  }
}