// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { AddressRequest, CreateUserRequest, UpdateUserRequest, User, Users } from '../models';
import type { UserRole } from '../enums';

export class UsersClient {
  constructor(private readonly api: ApiClient) {}

  async listUsers(query?: { search?: string; country?: string; role?: string; isActive?: boolean; limit?: number }): Promise<ApiResult<Users>> {
    return this.api.request<Users>('GET', '/users', {
      query: {
        search: query?.search,
        country: query?.country,
        role: query?.role,
        isActive: query?.isActive,
        limit: query?.limit,
      },
    });
  }

  async createUser(body: CreateUserRequest): Promise<ApiResult<User>> {
    return this.api.request<User>('POST', '/users', {
      body,
    });
  }

  async getUserById(userId: string): Promise<ApiResult<User>> {
    return this.api.request<User>('GET', `/users/${userId}`);
  }

  async updateUserById(userId: string, body: UpdateUserRequest): Promise<ApiResult<User>> {
    return this.api.request<User>('PUT', `/users/${userId}`, {
      body,
    });
  }

  async deleteUserById(userId: string): Promise<ApiResult<void>> {
    return this.api.request<void>('DELETE', `/users/${userId}`);
  }
}