// <auto-generated />
namespace Polymorphism.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createPayment.
/// </summary>
public sealed class CreatePaymentHandler : ICreatePaymentHandler
{
    public Task<CreatePaymentResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createPayment not implemented");
    }
}