// <auto-generated />
namespace SecurityOpenIdConnect.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getResourceById.
/// </summary>
public sealed class GetResourceByIdHandler : IGetResourceByIdHandler
{
    public Task<GetResourceByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getResourceById not implemented");
    }
}