// <auto-generated />
namespace SecurityOpenIdConnect.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listResources.
/// </summary>
public sealed class ListResourcesHandler : IListResourcesHandler
{
    public Task<ListResourcesResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listResources not implemented");
    }
}