// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using CachingHybrid.Generated.Models;
using CachingHybrid.Generated.Parameters;
using CachingHybrid.Generated.Results;

namespace CachingHybrid.Generated.Handlers;

/// <summary>
/// List users with HybridCache.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListUsersHandler
{
    Task<ListUsersResult> ExecuteAsync(
        ListUsersParameters parameters,
        CancellationToken cancellationToken = default);
}