// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityHybrid.Generated.Orders.Models;
using SecurityHybrid.Generated.Orders.Parameters;
using SecurityHybrid.Generated.Orders.Results;

namespace SecurityHybrid.Generated.Orders.Handlers;


/// <summary>
/// List all orders.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersHandler
{
    Task<ListOrdersResult> ExecuteAsync(CancellationToken cancellationToken = default);
}

/// <summary>
/// Create a new order.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOrderHandler
{
    Task<CreateOrderResult> ExecuteAsync(
        CreateOrderParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Get order by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOrderByIdHandler
{
    Task<GetOrderByIdResult> ExecuteAsync(
        GetOrderByIdParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Delete an order.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteOrderHandler
{
    Task<DeleteOrderResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Get order tracking.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOrderTrackingHandler
{
    Task<GetOrderTrackingResult> ExecuteAsync(
        GetOrderTrackingParameters parameters,
        CancellationToken cancellationToken = default);
}