// <auto-generated />
namespace SecurityAtcExt.Generated.Models;

public record ApiKey(
    [property: Required] Guid Id,
    [property: Required] string Name,
    DateTimeOffset CreatedAt,
    DateTimeOffset ExpiresAt);