// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { HealthStatus } from '../models';

export class HealthClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getHealth(): Promise<ApiResult<HealthStatus>> {
    return this.api.request<HealthStatus>('GET', '/health');
  }
}