// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { UserProfile } from '../models';

export class MeClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getCurrentUser(): Promise<ApiResult<UserProfile>> {
    return this.api.request<UserProfile>('GET', '/me');
  }

  async getCurrentUserProfile(): Promise<ApiResult<UserProfile>> {
    return this.api.request<UserProfile>('GET', '/me/profile');
  }
}