// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { UserProfile } from '../models';

export class MeClient {
  constructor(private readonly api: ApiClient) {}

  async getCurrentUser(): Promise<ApiResult<UserProfile>> {
    return this.api.request<UserProfile>('GET', '/me');
  }

  async getCurrentUserProfile(): Promise<ApiResult<UserProfile>> {
    return this.api.request<UserProfile>('GET', '/me/profile');
  }
}