// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using NonJsonContent.Generated.Models;
using NonJsonContent.Generated.Parameters;
using NonJsonContent.Generated.Results;

namespace NonJsonContent.Generated.Handlers;

/// <summary>
/// List items as JSON.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListItemsHandler
{
    Task<ListItemsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}