// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Pet.Client;
using PetStoreFull.Generated.Pet.Endpoints.Results;

namespace PetStoreFull.Generated.Pet.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Finds Pets by tags.
/// Operation: FindPetsByTags.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IFindPetsByTagsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<FindPetsByTagsEndpointResult> ExecuteAsync(
        FindPetsByTagsParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default);
}