// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Pet.Client;
using PetStoreFull.Generated.Pet.Endpoints.Results;

namespace PetStoreFull.Generated.Pet.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Uploads an image.
/// Operation: UploadFile.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUploadFileEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<UploadFileEndpointResult> ExecuteAsync(
        UploadFileParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default);
}