// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Retry.Generated.Reports.Client;
using Retry.Generated.Reports.Endpoints.Results;

namespace Retry.Generated.Reports.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Generate report (no retry, long timeout)
/// Operation: GenerateReport.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGenerateReportEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GenerateReportEndpointResult> ExecuteAsync(
        GenerateReportParameters parameters,
        string httpClientName = "Retry-ApiClient",
        CancellationToken cancellationToken = default);
}