// <auto-generated />
namespace Retry.Generated.Handlers;

/// <summary>
/// Generate report (no retry, long timeout).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGenerateReportHandler
{
    Task<GenerateReportResult> ExecuteAsync(
        GenerateReportParameters parameters,
        CancellationToken cancellationToken = default);
}