// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { CreatePetRequest, Pet, UpdatePetRequest } from '../models';

export class PetsClient {
  constructor(private readonly api: ApiClient) {}

  async listPets(query?: { limit?: number }): Promise<ApiResult<Pet[]>> {
    return this.api.request<Pet[]>('GET', '/pets', {
      query: {
        limit: query?.limit,
      },
    });
  }

  async createPet(body: CreatePetRequest): Promise<ApiResult<Pet>> {
    return this.api.request<Pet>('POST', '/pets', {
      body,
    });
  }

  async getPetById(petId: string): Promise<ApiResult<Pet>> {
    return this.api.request<Pet>('GET', `/pets/${petId}`);
  }

  async updatePet(petId: string, body: UpdatePetRequest): Promise<ApiResult<Pet>> {
    return this.api.request<Pet>('PUT', `/pets/${petId}`, {
      body,
    });
  }

  async deletePet(petId: string): Promise<ApiResult<void>> {
    return this.api.request<void>('DELETE', `/pets/${petId}`);
  }
}