// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace PetStoreFull.Generated;

/// <summary>
/// A list type that supports parsing from comma-separated string values.
/// Used for array query parameters bound via [AsParameters] in minimal APIs.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ParsableList<T> : List<T>, IParsable<ParsableList<T>>
    where T : IParsable<T>
{
    /// <inheritdoc />
    public static ParsableList<T> Parse(string s, IFormatProvider? provider)
    {
        var list = new ParsableList<T>();
        if (!string.IsNullOrEmpty(s))
        {
            foreach (var item in s.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                list.Add(T.Parse(item, provider));
            }
        }

        return list;
    }

    /// <inheritdoc />
    public static bool TryParse(string? s, IFormatProvider? provider, out ParsableList<T> result)
    {
        result = new ParsableList<T>();
        if (string.IsNullOrEmpty(s))
        {
            return true;
        }

        foreach (var item in s.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            if (!T.TryParse(item, provider, out var parsed))
            {
                return false;
            }

            result.Add(parsed);
        }

        return true;
    }
}