// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace CachingOutput.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record Category(
    [property: Required] Guid Id,
    [property: Required] string Name,
    string Description);