// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SecurityHybrid.Generated.Products.Handlers;
using SecurityHybrid.Generated.Products.Models;
using SecurityHybrid.Generated.Products.Parameters;
using SecurityHybrid.Generated.Products.Results;

namespace SecurityHybrid.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Products.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ProductsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/products";

    public void DefineEndpoints(WebApplication app)
    {
        var products = app
            .MapGroup(ApiRouteBase)
            .WithTags("Products")
            .RequireAuthorization();

        products
            .MapGet("/", ListProducts)
            .WithName("ListProducts")
            .WithSummary("List products")
            .Produces<List<Product>>()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);

        products
            .MapGet("{productId}", GetProductById)
            .WithName("GetProductById")
            .WithSummary("Get product by ID")
            .Produces<Product>()
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status403Forbidden)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .RequireAuthorization(policy => policy.RequireRole("manager", "admin"));
    }

    internal async Task<IResult> ListProducts(
        [FromServices] IListProductsHandler handler,
        CancellationToken cancellationToken)
        => ListProductsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));

    internal async Task<IResult> GetProductById(
        [FromServices] IGetProductByIdHandler handler,
        [AsParameters] GetProductByIdParameters parameters,
        CancellationToken cancellationToken)
        => GetProductByIdResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}