// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityAtcExt.Generated.Admin.Endpoints.Results;

namespace SecurityAtcExt.Generated.Admin.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Get admin settings (Bearer + admin role)
/// Operation: GetAdminSettings.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetAdminSettingsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetAdminSettingsEndpointResult> ExecuteAsync(
        string httpClientName = "SecurityAtcExt-ApiClient",
        CancellationToken cancellationToken = default);
}