// <auto-generated />
namespace ModelsAndProperties.Generated.Models;

public sealed record Dog(
    [property: Required] string Name,
    int Age,
    [property: Required] string Breed) : Animal(Name, Age);