// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using VersioningUrlSegment.Generated;
using VersioningUrlSegment.Generated.Pets.Models;

namespace VersioningUrlSegment.Generated.Pets.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create a new pet
/// Operation: CreatePet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreatePetEndpointResult : IEndpointResponse
{
    bool IsCreated { get; }

    bool IsBadRequest { get; }

    bool IsConflict { get; }

    bool IsInternalServerError { get; }

    Pet CreatedContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}