// <auto-generated />
namespace SecurityOpenIdConnect.Generated.Models;

public record Resource(
    [property: Required] Guid Id,
    [property: Required] string Name,
    Guid OwnerId,
    DateTimeOffset CreatedAt);