// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using Demo.Generated;
using Demo.Generated.Tasks.Models;

namespace Demo.Generated.Tasks.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create task
/// Operation: CreateTask.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateTaskEndpointResult : IEndpointResponse
{
    bool IsCreated { get; }

    bool IsConflict { get; }

    bool IsBadRequest { get; }

    bool IsInternalServerError { get; }

    Task CreatedContent { get; }

    ProblemDetails ConflictContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}