// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using Demo.Generated;
using Demo.Generated.Tasks.Models;

namespace Demo.Generated.Tasks.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List all tasks
/// Operation: ListTasks.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListTasksEndpointResult : IEndpointResponse
{
    bool IsBadRequest { get; }

    bool IsInternalServerError { get; }

    IEnumerable<Task> OkContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}