// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityOpenIdConnect.Generated;
using SecurityOpenIdConnect.Generated.Mes.Models;

namespace SecurityOpenIdConnect.Generated.Mes.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Get detailed user profile
/// Operation: GetCurrentUserProfile.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetCurrentUserProfileEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    UserProfile OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails ForbiddenContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}