// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityOpenIdConnect.Generated.Mes.Endpoints.Results;

namespace SecurityOpenIdConnect.Generated.Mes.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Get detailed user profile
/// Operation: GetCurrentUserProfile.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetCurrentUserProfileEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetCurrentUserProfileEndpointResult> ExecuteAsync(
        string httpClientName = "SecurityOpenIdConnect-ApiClient",
        CancellationToken cancellationToken = default);
}