// <auto-generated />
namespace SecurityOpenIdConnect.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddSecurityOpenIdConnectHandlers(this IServiceCollection services)
    {
        // Handler for ICreateResourceHandler must be registered in the Domain project
        // services.AddScoped<ICreateResourceHandler, YourImplementation>();
        // Handler for IDeleteResourceHandler must be registered in the Domain project
        // services.AddScoped<IDeleteResourceHandler, YourImplementation>();
        // Handler for IGetCurrentUserHandler must be registered in the Domain project
        // services.AddScoped<IGetCurrentUserHandler, YourImplementation>();
        // Handler for IGetCurrentUserProfileHandler must be registered in the Domain project
        // services.AddScoped<IGetCurrentUserProfileHandler, YourImplementation>();
        // Handler for IGetHealthHandler must be registered in the Domain project
        // services.AddScoped<IGetHealthHandler, YourImplementation>();
        // Handler for IGetResourceByIdHandler must be registered in the Domain project
        // services.AddScoped<IGetResourceByIdHandler, YourImplementation>();
        // Handler for IListResourcesHandler must be registered in the Domain project
        // services.AddScoped<IListResourcesHandler, YourImplementation>();

        return services;
    }
}