// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using SecurityStandard.Generated.Models;
using SecurityStandard.Generated.Parameters;
using SecurityStandard.Generated.Results;

namespace SecurityStandard.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: getData.
/// </summary>
public sealed class GetDataHandler : IGetDataHandler
{
    public Task<GetDataResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("getData not implemented");
    }
}