// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityAtcExt.Generated;
using SecurityAtcExt.Generated.Orders.Models;

namespace SecurityAtcExt.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Get tracking (public override)
/// Operation: GetOrderTracking.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOrderTrackingEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsNotFound { get; }

    bool IsInternalServerError { get; }

    TrackingInfo OkContent { get; }

    ProblemDetails NotFoundContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}