// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityAtcExt.Generated.Orders.Client;
using SecurityAtcExt.Generated.Orders.Endpoints.Results;

namespace SecurityAtcExt.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Get order (manager role inherited)
/// Operation: GetOrderById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOrderByIdEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetOrderByIdEndpointResult> ExecuteAsync(
        GetOrderByIdParameters parameters,
        string httpClientName = "SecurityAtcExt-ApiClient",
        CancellationToken cancellationToken = default);
}