// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityAtcExt.Generated;
using SecurityAtcExt.Generated.Orders.Models;

namespace SecurityAtcExt.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List orders (requires auth)
/// Operation: ListOrders.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsInternalServerError { get; }

    IEnumerable<Order> OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}