// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using HeaderParameters.Generated.Models;
using Microsoft.AspNetCore.Mvc;

namespace HeaderParameters.Generated.Parameters;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetItemByIdParameters(
    [property: FromRoute(Name = "itemId"), Required] string ItemId,
    [property: FromHeader(Name = "X-Request-Id")] string? RequestId);