// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityBearerOnly.Generated.Handlers;

namespace SecurityBearerOnly;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ApiHandlerServiceCollectionExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>
    /// The service collection for method chaining.
    /// </returns>
    public static IServiceCollection AddApiHandlersFromSecurityBearerOnly(this IServiceCollection services)
    {
        services.AddScoped<IGetCurrentUserHandler, global::SecurityBearerOnly.ApiHandlers.GetCurrentUserHandler>();

        return services;
    }
}