// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityHybrid.Generated;
using SecurityHybrid.Generated.Orders.Models;

namespace SecurityHybrid.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Create a new order
/// Operation: CreateOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOrderEndpointResult : IEndpointResponse
{
    bool IsCreated { get; }

    bool IsBadRequest { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsConflict { get; }

    bool IsInternalServerError { get; }

    Order CreatedContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails ForbiddenContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}