// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityHybrid.Generated.Orders.Endpoints.Results;

namespace SecurityHybrid.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all orders
/// Operation: ListOrders.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListOrdersEndpointResult> ExecuteAsync(
        string httpClientName = "SecurityHybrid-ApiClient",
        CancellationToken cancellationToken = default);
}