// <auto-generated />
/** The lifecycle state of a ticket. */
export type TicketStatus = 'Open' | 'InProgress' | 'Resolved' | 'Closed';

export const TicketStatusValues = ['Open', 'InProgress', 'Resolved', 'Closed'] as const;