// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using SingleTypedClient.Generated.Models;

namespace SingleTypedClient.Generated;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ISingleTypedApiClient
{
    Task<List<Account>> ListAccountsAsync(CancellationToken cancellationToken = default);

    Task<Account> GetAccountByIdAsync(
        GetAccountByIdParameters parameters,
        CancellationToken cancellationToken = default);

    Task<List<Order>> ListOrdersAsync(CancellationToken cancellationToken = default);

    Task<Order> CreateOrderAsync(
        CreateOrderParameters parameters,
        CancellationToken cancellationToken = default);
}