// <auto-generated />
namespace Demo.Generated.Handlers;

/// <summary>
/// Create account.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateAccountHandler
{
    System.Threading.Tasks.Task<CreateAccountResult> ExecuteAsync(
        CreateAccountParameters parameters,
        CancellationToken cancellationToken = default);
}