// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ExportJob, ExportRequest } from '../models';

export type CreateExportResult =
  | { status: 'accepted'; data: ExportJob; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class ExportsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Create export (concurrency limited) */
  async createExport(body: ExportRequest): Promise<CreateExportResult> {
    return this.api.request<void>('POST', '/exports', {
      body,
    }) as Promise<CreateExportResult>;
  }
}