// <auto-generated />
import type { Address } from './Address';

/** Demonstrates nullable versions of all types */
export interface NullableTypes {
  /** Required non-nullable string */
  readonly requiredString: string;

  /** Nullable string */
  readonly nullableString?: string | null;

  /** Nullable integer */
  readonly nullableInteger?: number | null;

  /** Nullable long */
  readonly nullableLong?: number | null;

  /** Nullable number */
  readonly nullableNumber?: number | null;

  /** Nullable float */
  readonly nullableFloat?: number | null;

  /** Nullable boolean */
  readonly nullableBoolean?: boolean | null;

  /** Nullable UUID */
  readonly nullableUuid?: string | null;

  /** Nullable date-time */
  readonly nullableDateTime?: string | null;

  /** Nullable date */
  readonly nullableDate?: string | null;

  /** Nullable URI */
  readonly nullableUri?: string | null;

  /** Nullable email */
  readonly nullableEmail?: string | null;

  /** Nullable integer with range */
  readonly nullableIntegerWithRange?: number | null;

  /** Nullable string with length */
  readonly nullableStringWithLength?: string | null;

  /** Nullable string with default */
  readonly nullableWithDefault?: string | null;

  /** Nullable array of strings */
  readonly nullableArray?: string[] | null;

  /** Nullable address reference */
  readonly nullableAddress?: Address | null;
}