// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Demo.Generated.Users.Handlers;
using Demo.Generated.Users.Models;
using Demo.Generated.Users.Parameters;
using Demo.Generated.Users.Results;

namespace Demo.Generated.Users.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Users.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class UsersEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/users";

    public void DefineEndpoints(WebApplication app)
    {
        var users = app
            .MapGroup(ApiRouteBase)
            .WithTags("Users");

        users
            .MapGet("/", ListUsers)
            .WithName("ListUsers")
            .WithSummary("List all users")
            .Produces<List<User>>()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        users
            .MapPost("/", CreateUser)
            .WithName("CreateUser")
            .WithSummary("Create user")
            .Produces<User>(StatusCodes.Status201Created)
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        users
            .MapGet("{userId}", GetUserById)
            .WithName("GetUserById")
            .WithSummary("Get a specific user")
            .Produces<User>()
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        users
            .MapPut("{userId}", UpdateUserById)
            .WithName("UpdateUserById")
            .WithSummary("Update a specific user")
            .Produces<User>()
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        users
            .MapDelete("{userId}", DeleteUserById)
            .WithName("DeleteUserById")
            .WithSummary("Delete a specific user")
            .Produces(StatusCodes.Status204NoContent)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status500InternalServerError);
    }

    internal async System.Threading.Tasks.Task<IResult> ListUsers(
        [FromServices] IListUsersHandler handler,
        [AsParameters] ListUsersParameters parameters,
        CancellationToken cancellationToken)
        => ListUsersResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async System.Threading.Tasks.Task<IResult> CreateUser(
        [FromServices] ICreateUserHandler handler,
        [AsParameters] CreateUserParameters parameters,
        CancellationToken cancellationToken)
        => CreateUserResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async System.Threading.Tasks.Task<IResult> GetUserById(
        [FromServices] IGetUserByIdHandler handler,
        [AsParameters] GetUserByIdParameters parameters,
        CancellationToken cancellationToken)
        => GetUserByIdResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async System.Threading.Tasks.Task<IResult> UpdateUserById(
        [FromServices] IUpdateUserByIdHandler handler,
        [AsParameters] UpdateUserByIdParameters parameters,
        CancellationToken cancellationToken)
        => UpdateUserByIdResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async System.Threading.Tasks.Task<IResult> DeleteUserById(
        [FromServices] IDeleteUserByIdHandler handler,
        [AsParameters] DeleteUserByIdParameters parameters,
        CancellationToken cancellationToken)
        => DeleteUserByIdResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapUsersEndpoints(this WebApplication app)
    {
        new UsersEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}