// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PetStoreSimple.Generated.Pets.Handlers;
using PetStoreSimple.Generated.Pets.Models;
using PetStoreSimple.Generated.Pets.Parameters;
using PetStoreSimple.Generated.Pets.Results;

namespace PetStoreSimple.Generated.Pets.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Pets.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class PetsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/pets";

    public void DefineEndpoints(WebApplication app)
    {
        var pets = app
            .MapGroup(ApiRouteBase)
            .WithTags("Pets");

        pets
            .MapGet("/", ListPets)
            .WithName("ListPets")
            .WithSummary("List all pets")
            .Produces<List<Pet>>()
            .ProducesValidationProblem()
            .ProducesValidationProblem();

        pets
            .MapPost("/", CreatePets)
            .WithName("CreatePets")
            .WithSummary("Create a pet")
            .Produces(StatusCodes.Status201Created)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status409Conflict);

        pets
            .MapGet("{petId}", ShowPetById)
            .WithName("ShowPetById")
            .WithSummary("Info for a specific pet")
            .Produces<Pet>()
            .ProducesValidationProblem()
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status404NotFound);
    }

    internal async Task<IResult> ListPets(
        [FromServices] IListPetsHandler handler,
        [AsParameters] ListPetsParameters parameters,
        CancellationToken cancellationToken)
        => ListPetsResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));

    internal async Task<IResult> CreatePets(
        [FromServices] ICreatePetsHandler handler,
        CancellationToken cancellationToken)
        => CreatePetsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));

    internal async Task<IResult> ShowPetById(
        [FromServices] IShowPetByIdHandler handler,
        [AsParameters] ShowPetByIdParameters parameters,
        CancellationToken cancellationToken)
        => ShowPetByIdResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapPetsEndpoints(this WebApplication app)
    {
        new PetsEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}