// <auto-generated />
namespace Retry.Generated.Handlers;

/// <summary>
/// Send notification (constant backoff).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ISendNotificationHandler
{
    Task<SendNotificationResult> ExecuteAsync(
        SendNotificationParameters parameters,
        CancellationToken cancellationToken = default);
}