// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Retry.Generated.Models;
using Retry.Generated.Parameters;
using Retry.Generated.Results;

namespace Retry.Generated.Handlers;

/// <summary>
/// Send notification (constant backoff).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ISendNotificationHandler
{
    Task<SendNotificationResult> ExecuteAsync(
        SendNotificationParameters parameters,
        CancellationToken cancellationToken = default);
}