// <auto-generated />
namespace CachingOutput.Generated.Parameters;

public sealed record ListProductsParameters(
    [property: FromQuery(Name = "category")] string? Category,
    [property: FromQuery(Name = "page"), DefaultValue(1)] int? Page = 1,
    [property: FromQuery(Name = "limit"), DefaultValue(20)] int? Limit = 20);