// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiError, ValidationError } from '../errors';

export type ListReportsResult =
  | { status: 'ok'; data: unknown[]; response: Response }
  | { status: 'badRequest'; error: ValidationError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export type GetReportResult =
  | { status: 'ok'; data: unknown; response: Response }
  | { status: 'notFound'; error: ApiError; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class ReportsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** List all reports */
  async listReports(): Promise<ListReportsResult> {
    return this.api.request<unknown[]>('GET', '/reports') as Promise<ListReportsResult>;
  }

  /** Get a report by ID */
  async getReport(reportId: string): Promise<GetReportResult> {
    return this.api.request<unknown>('GET', `/reports/${reportId}`) as Promise<GetReportResult>;
  }
}