// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client.Options;
using Microsoft.Extensions.DependencyInjection;
using Retry.Generated.External.Endpoints;
using Retry.Generated.External.Endpoints.Interfaces;

namespace Retry.Generated.External;

/// <summary>
/// Extension methods for registering External API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all External API endpoint implementations.
    /// Also ensures IHttpMessageFactory and IContractSerializer are registered (from Atc.Rest.Client).
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddExternalEndpoints(this IServiceCollection services)
    {
        // Ensure Atc.Rest.Client core services are registered (IHttpMessageFactory, IContractSerializer)
        services.AddAtcRestClientCore();

        services.AddTransient<IProcessPaymentEndpoint, ProcessPaymentEndpoint>();

        return services;
    }
}