// <auto-generated />
namespace PetStoreFull.Generated.Parameters;

public record UpdateUserParameters(
    [property: FromRoute(Name = "username"), Required] string Username,
    [property: FromBody] User? Request);