// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace SecurityBearerOnly.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record User(
    string Email);