// <auto-generated />

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityBearerOnly.Generated.Handlers;
namespace SecurityBearerOnly.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddSecurityBearerOnlyHandlers(this IServiceCollection services)
    {
        // Handler for IGetCurrentUserHandler must be registered in the Domain project
        // services.AddScoped<IGetCurrentUserHandler, YourImplementation>();

        return services;
    }
}