// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using Atc.Rest.MinimalApi.Extensions;
using Microsoft.AspNetCore.Builder;

using SecurityBearerOnly.Generated;
using SecurityBearerOnly.Generated.Endpoints;

namespace SecurityBearerOnly.Generated.Extensions;

/// <summary>
/// Unified extension methods for configuring SecurityBearerOnly API middleware and endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class UnifiedWebApplicationExtensions
{
    /// <summary>
    /// Configures SecurityBearerOnly API middleware and maps all endpoints.
    /// </summary>
    /// <param name="app">The WebApplication to configure.</param>
    /// <param name="configure">Optional configuration for API middleware options.</param>
    /// <returns>The WebApplication for method chaining.</returns>
    /// <remarks>
    /// This method configures:
    /// - Authentication and authorization middleware (auto-detected)
    /// - Global error handling middleware
    /// - All API endpoints
    /// </remarks>
    public static WebApplication MapSecurityBearerOnlyApi(
        this WebApplication app,
        Action<ApiMiddlewareOptions>? configure = null)
    {
        var options = new ApiMiddlewareOptions();
        configure?.Invoke(options);

        // Authentication and authorization middleware
        if (options.UseAuthentication)
        {
            app.UseAuthentication();
            if (options.UseAuthorization)
            {
                app.UseAuthorization();
            }
        }
        else if (options.UseAuthorization)
        {
            app.UseAuthorization();
        }

        // Global error handling middleware (converts exceptions to ProblemDetails)
        app.UseGlobalErrorHandler(options.ConfigureErrorHandling);

        // Map all API endpoints
        app.MapEndpoints();

        return app;
    }
}