// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using PetStoreFull.Generated;
using PetStoreFull.Generated.Pet.Endpoints.Interfaces;
using PetStoreFull.Generated.Pet.Endpoints.Results;
using PetStoreFull.Generated.Pet.Models;
using PetStoreFull.Generated.Pet.Client;

namespace PetStoreFull.Generated.Pet.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Add a new pet to the store.
/// Operation: AddPet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class AddPetEndpoint : IAddPetEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public AddPetEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<AddPetEndpointResult> ExecuteAsync(
        AddPetParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/pet");
        requestBuilder.WithBody(parameters.Request);

        using var requestMessage = requestBuilder.Build(HttpMethod.Post);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Pet>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.UnprocessableEntity);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Forbidden);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Conflict);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new AddPetEndpointResult(x), cancellationToken);
    }
}