// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using PetStoreFull.Generated;
using PetStoreFull.Generated.Pet.Endpoints.Interfaces;
using PetStoreFull.Generated.Pet.Endpoints.Results;
using PetStoreFull.Generated.Pet.Models;
using PetStoreFull.Generated.Pet.Client;

namespace PetStoreFull.Generated.Pet.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Finds Pets by status.
/// Operation: FindPetsByStatus.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class FindPetsByStatusEndpoint : IFindPetsByStatusEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public FindPetsByStatusEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<FindPetsByStatusEndpointResult> ExecuteAsync(
        FindPetsByStatusParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/pet/findByStatus");
        requestBuilder.WithQueryParameter("status", parameters.Status);

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<IEnumerable<Pet>>(HttpStatusCode.OK);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Forbidden);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new FindPetsByStatusEndpointResult(x), cancellationToken);
    }
}