// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using ParameterSerialization.Generated.Models;

namespace ParameterSerialization.Generated.Parameters;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListItemsParameters(
    [property: FromQuery(Name = "tags")] ParsableList<string>? Tags,
    [property: FromQuery(Name = "q")] string? Q,
    [property: FromQuery(Name = "legacy")] ParsableList<string>? Legacy,
    [property: FromQuery(Name = "ids")] ParsableList<string>? Ids);