// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using VersioningUrlSegment.Generated.Models;
using VersioningUrlSegment.Generated.Parameters;
using VersioningUrlSegment.Generated.Results;

namespace VersioningUrlSegment.Generated.Handlers;

/// <summary>
/// Create a new owner.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateOwnerHandler
{
    Task<CreateOwnerResult> ExecuteAsync(
        CreateOwnerParameters parameters,
        CancellationToken cancellationToken = default);
}