// <auto-generated />
namespace SecurityStandard.Generated.Models;

public sealed record User(
    [property: Required] Guid Id,
    [property: Required] string Username,
    [property: EmailAddress] string Email,
    string Role);