// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using CookieParameters.Generated.Tracking.Client;
using CookieParameters.Generated.Tracking.Endpoints.Results;

namespace CookieParameters.Generated.Tracking.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Track an event with user context
/// Operation: TrackEvent.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ITrackEventEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<TrackEventEndpointResult> ExecuteAsync(
        TrackEventParameters parameters,
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default);
}