// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Retry.Generated.External.Models;

namespace Retry.Generated.External.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: Process payment (circuit breaker enabled).
/// Operation: ProcessPayment.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ProcessPaymentParameters(
    [property: FromBody, Required] PaymentRequest Request);