// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace PetStoreFull.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record User(
    long Id,
    string Username,
    string FirstName,
    string LastName,
    string Email,
    string Password,
    string Phone,
    int UserStatus);