// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsAndProperties.Generated.Arrays.Handlers;
using ModelsAndProperties.Generated.Arrays.Models;
using ModelsAndProperties.Generated.Arrays.Results;

namespace ModelsAndProperties.Generated.Arrays.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Arrays.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ArraysEndpointDefinition : IEndpointDefinition
{
    public void DefineEndpoints(WebApplication app)
    {
        var arrays = app
            .MapGroup("/arrays")
            .WithTags("Arrays");

        arrays
            .MapGet("/", GetArrayTypes)
            .WithName("GetArrayTypes")
            .WithSummary("Get array types model")
            .Produces<ArrayTypes>()
            .ProducesProblem(StatusCodes.Status500InternalServerError);
    }

    internal async Task<IResult> GetArrayTypes(
        [FromServices] IGetArrayTypesHandler handler,
        CancellationToken cancellationToken)
        => GetArrayTypesResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapArraysEndpoints(this WebApplication app)
    {
        new ArraysEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}