// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsAndProperties.Generated.Primitives.Handlers;
using ModelsAndProperties.Generated.Primitives.Models;
using ModelsAndProperties.Generated.Primitives.Parameters;
using ModelsAndProperties.Generated.Primitives.Results;

namespace ModelsAndProperties.Generated.Primitives.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Primitives.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class PrimitivesEndpointDefinition : IEndpointDefinition
{
    public void DefineEndpoints(WebApplication app)
    {
        var primitives = app
            .MapGroup("/primitives")
            .WithTags("Primitives");

        primitives
            .MapGet("/", GetPrimitiveTypes)
            .WithName("GetPrimitiveTypes")
            .WithSummary("Get primitive types model")
            .Produces<PrimitiveTypes>()
            .ProducesProblem(StatusCodes.Status500InternalServerError);
    }

    internal async Task<IResult> GetPrimitiveTypes(
        [FromServices] IGetPrimitiveTypesHandler handler,
        CancellationToken cancellationToken)
        => GetPrimitiveTypesResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapPrimitivesEndpoints(this WebApplication app)
    {
        new PrimitivesEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}