// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModelsAndProperties.Generated.Validations.Handlers;
using ModelsAndProperties.Generated.Validations.Models;
using ModelsAndProperties.Generated.Validations.Results;

namespace ModelsAndProperties.Generated.Validations.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Validations.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ValidationsEndpointDefinition : IEndpointDefinition
{
    public void DefineEndpoints(WebApplication app)
    {
        var validations = app
            .MapGroup("/validations")
            .WithTags("Validations");

        validations
            .MapGet("/", GetValidations)
            .WithName("GetValidations")
            .WithSummary("Get validation constraints model")
            .Produces<ValidationConstraints>()
            .ProducesProblem(StatusCodes.Status500InternalServerError);
    }

    internal async Task<IResult> GetValidations(
        [FromServices] IGetValidationsHandler handler,
        CancellationToken cancellationToken)
        => GetValidationsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapValidationsEndpoints(this WebApplication app)
    {
        new ValidationsEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}