// <auto-generated />
namespace RateLimit.Generated.Handlers;

/// <summary>
/// Receive webhook (rate limiting disabled).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IReceiveWebhookHandler
{
    Task<ReceiveWebhookResult> ExecuteAsync(
        ReceiveWebhookParameters parameters,
        CancellationToken cancellationToken = default);
}