// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: deleteTaskById.
/// </summary>
public sealed class DeleteTaskByIdHandler : IDeleteTaskByIdHandler
{
    public Task<DeleteTaskByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("deleteTaskById not implemented");
    }
}