// <auto-generated />
namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listTasks.
/// </summary>
public sealed class ListTasksHandler : IListTasksHandler
{
    public Task<ListTasksResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listTasks not implemented");
    }
}