// <auto-generated />
namespace SecurityHybrid.Generated.Handlers;

/// <summary>
/// List products.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListProductsHandler
{
    Task<ListProductsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}