// <auto-generated />
import type { CreditCard } from './CreditCard';
import type { BankTransfer } from './BankTransfer';
import type { PayPal } from './PayPal';

export type PaymentMethod = CreditCard | BankTransfer | PayPal;