// <auto-generated />
import { ApiClient, ApiClientOptions } from './ApiClient';
import { PetsClient } from './PetsClient';

export class ApiService {
  readonly pets: PetsClient;

  constructor(baseUrl: string, options?: ApiClientOptions) {
    const api = new ApiClient(baseUrl, options);
    this.pets = new PetsClient(api);
  }
}