namespace Atc.Rest.Api.Generator.Cli.Services;

/// <summary>
/// Orchestrates TypeScript client generation from OpenAPI documents.
/// </summary>
public static class TypeScriptClientGenerationService
{
    /// <summary>
    /// Generates all TypeScript client files from an OpenAPI document.
    /// Includes models, enums, error types, ApiResult, base client, and per-segment clients.
    /// </summary>
    /// <param name="openApiDoc">The parsed OpenAPI document.</param>
    /// <param name="outputPath">The root output directory for generated files.</param>
    /// <param name="config">TypeScript client generation configuration.</param>
    /// <returns>A result containing counts of generated files.</returns>
    public static TypeScriptGenerationResult Generate(
        OpenApiDocument openApiDoc,
        string outputPath,
        TypeScriptClientConfig config)
    {
        ArgumentNullException.ThrowIfNull(openApiDoc);
        ArgumentNullException.ThrowIfNull(config);

        var dryRun = config.DryRun;
        var headerContent = config.GenerateFileHeaders ? TypeScriptHeaderBuilder.AutoGeneratedHeader : null;

        // Step 1: Extract enums first (needed for correct import paths in models)
        var enums = TypeScriptEnumExtractor.Extract(openApiDoc, config);
        var enumNameSet = new HashSet<string>(enums.Select(e => e.Name), StringComparer.Ordinal);
        var enumCount = WriteEnums(enums, outputPath, headerContent, config.GenerateZodSchemas, dryRun);

        // Step 2: Extract and generate models (with enum names for correct import paths)
        var models = TypeScriptModelExtractor.Extract(openApiDoc, config, enumNameSet);
        var arrayTypeAliases = TypeScriptModelExtractor.ExtractArrayTypeAliases(openApiDoc, config);
        var unionTypeAliases = TypeScriptModelExtractor.ExtractUnionTypeAliases(openApiDoc, config);
        var modelCount = WriteModels(models, arrayTypeAliases, unionTypeAliases, outputPath, headerContent, config.GenerateZodSchemas, dryRun);

        // Step 3: Generate error types
        var errorTypeCount = WriteErrorTypes(outputPath, headerContent, config.HttpClient, dryRun);

        // Step 4: Generate ApiResult type
        var typeCount = WriteApiResultType(outputPath, headerContent, config.HttpClient, config.ZodRuntimeValidate, dryRun);

        // Step 5: Generate client classes
        var specHasRetry = openApiDoc.HasRetryConfiguration();
        var writableSchemas = TypeScriptModelExtractor.CollectSchemasWithWritableVariant(openApiDoc);
        var (clientCount, segmentClientNames) = WriteClients(openApiDoc, outputPath, headerContent, enumNameSet, config.HttpClient, config.NamingStrategy, config.ConvertDates, specHasRetry, dryRun, writableSchemas, config.BrandedIds, config.ZodRuntimeValidate);

        // Step 5b: Generate helpers (pagination, retry)
        var hasRetry = clientCount > 0 && specHasRetry;
        var hasPagination = clientCount > 0 && HasPaginationSchemas(openApiDoc);
        if (hasPagination || hasRetry)
        {
            var helpersDir = Path.Combine(outputPath, "helpers");
            var helperModules = new List<string>();

            if (hasPagination)
            {
                var paginationContent = TypeScriptPaginationHelperExtractor.Generate(headerContent);
                WriteTsFile(Path.Combine(helpersDir, "paginate.ts"), paginationContent, dryRun);
                helperModules.Add("paginate");
            }

            if (hasRetry)
            {
                var retryConfigContent = TypeScriptRetryConfigExtractor.Generate(openApiDoc, headerContent);
                WriteTsFile(Path.Combine(helpersDir, "retryConfig.ts"), retryConfigContent, dryRun);
                helperModules.Add("retryConfig");

                var retryInterceptorContent = TypeScriptRetryInterceptorExtractor.Generate(headerContent);
                WriteTsFile(Path.Combine(helpersDir, "retryInterceptor.ts"), retryInterceptorContent, dryRun);
                helperModules.Add("retryInterceptor");
            }

            // Generate barrel export for helpers
            var helperBarrel = TypeScriptBarrelExportExtractor.Create(headerContent, helperModules, isTypeOnly: false);
            WriteTsFile(Path.Combine(helpersDir, "index.ts"), new GenerateContentForBarrelExport(helperBarrel).Generate(), dryRun);
        }

        // Step 6: Generate React Query hooks (if configured)
        var hookCount = 0;
        if (config.HooksStyle == TypeScriptHooksStyle.ReactQuery && clientCount > 0)
        {
            hookCount = WriteReactQueryHooks(openApiDoc, outputPath, headerContent, enumNameSet, config.NamingStrategy, config.ConvertDates, dryRun, writableSchemas, config.HooksMode, config.BrandedIds);
        }
        else if (config.HooksStyle == TypeScriptHooksStyle.Swr && clientCount > 0)
        {
            hookCount = WriteSwrHooks(openApiDoc, outputPath, headerContent, enumNameSet, config.NamingStrategy, dryRun, config.BrandedIds);
        }

        // Step 6b: Generate Zod schemas (if configured)
        var zodSchemaCount = 0;
        if (config.GenerateZodSchemas)
        {
            zodSchemaCount = WriteZodSchemas(openApiDoc, outputPath, headerContent, config, enumNameSet, dryRun);
        }

        // Step 6c: Generate MSW handlers (if configured)
        var mswHandlerCount = 0;
        if (config.GenerateMswHandlers)
        {
            mswHandlerCount = WriteMswHandlers(openApiDoc, outputPath, headerContent, config, dryRun);
        }

        // Step 6d: Emit a typed Servers map when the spec declares >1 server entry.
        // Single-server specs keep the existing baseUrl ctor-arg pattern unchanged.
        var serversEmitted = WriteServersFile(openApiDoc, outputPath, headerContent, dryRun);

        // Step 6e: Emit typed Webhook payload aliases for any operation with a
        // callbacks: block whose body resolves to a named component schema.
        var webhooksEmitted = WriteWebhooksFile(openApiDoc, outputPath, headerContent, dryRun);

        // Step 6f: Emit SignalR-style hub hooks when the doc declares an
        // x-signalr-hubs vendor extension. One hook file per declared hub.
        var hubsEmitted = WriteSignalRHubFiles(openApiDoc, outputPath, headerContent, dryRun);

        // Step 6g: Emit branded ID type aliases when --branded-ids is set. The file
        // lives under types/ so it joins the existing type-only barrel. typeCount is
        // bumped so the root barrel includes the types/ subdirectory.
        if (config.BrandedIds)
        {
            var brandedEmitted = WriteBrandedIdsFile(openApiDoc, outputPath, headerContent, dryRun);
            if (brandedEmitted)
            {
                typeCount++;
            }
        }

        // Step 7: Generate package scaffold (if configured)
        var scaffoldGenerated = false;
        if (config.Scaffold)
        {
            scaffoldGenerated = WritePackageScaffold(openApiDoc, outputPath, config, segmentClientNames, dryRun);
        }

        // Step 8: Generate root barrel export
        var subdirectories = new List<string>();
        if (modelCount > 0)
        {
            subdirectories.Add("models");
        }

        if (enumCount > 0)
        {
            subdirectories.Add("enums");
        }

        if (errorTypeCount > 0)
        {
            subdirectories.Add("errors");
        }

        if (typeCount > 0)
        {
            subdirectories.Add("types");
        }

        if (clientCount > 0)
        {
            subdirectories.Add("client");
        }

        if (hasPagination || hasRetry)
        {
            subdirectories.Add("helpers");
        }

        if (hookCount > 0)
        {
            subdirectories.Add("hooks");
        }

        if (mswHandlerCount > 0)
        {
            subdirectories.Add("mocks");
        }

        if (serversEmitted)
        {
            subdirectories.Add("servers");
        }

        if (webhooksEmitted)
        {
            subdirectories.Add("webhooks");
        }

        if (hubsEmitted)
        {
            subdirectories.Add("hubs");
        }

        if (subdirectories.Count > 0)
        {
            WriteRootBarrelExport(outputPath, headerContent, subdirectories, dryRun);
        }

        var warnings = CollectCookieParameterWarnings(openApiDoc);

        return new TypeScriptGenerationResult(
            ModelCount: modelCount,
            EnumCount: enumCount,
            ErrorTypeCount: errorTypeCount,
            TypeCount: typeCount,
            ClientCount: clientCount,
            HookCount: hookCount,
            ZodSchemaCount: zodSchemaCount,
            MswHandlerCount: mswHandlerCount,
            ScaffoldGenerated: scaffoldGenerated)
        {
            Warnings = warnings,
        };
    }

    /// <summary>
    /// Scans every operation (and path-item-level parameters) for OpenAPI <c>in: cookie</c>
    /// parameters and produces one warning per operation that declares any. The TypeScript
    /// emitter intentionally skips cookie parameters — cookies are browser-managed via
    /// <c>document.cookie</c> and the fetch <c>credentials</c> option, so SDK methods do
    /// not accept a cookies bag. The warning surfaces the silent skip so spec authors
    /// notice when a cookie param will not be wired through.
    /// </summary>
    private static IReadOnlyList<string> CollectCookieParameterWarnings(
        OpenApiDocument openApiDoc)
    {
        if (openApiDoc.Paths == null || openApiDoc.Paths.Count == 0)
        {
            return Array.Empty<string>();
        }

        var warnings = new List<string>();

        foreach (var pathEntry in openApiDoc.Paths)
        {
            if (pathEntry.Value is not OpenApiPathItem pathItem)
            {
                continue;
            }

            var pathLevelCookieNames = CollectCookieParameterNames(pathItem.Parameters);

            if (pathItem.Operations == null)
            {
                continue;
            }

            foreach (var operationEntry in pathItem.Operations)
            {
                var operationCookieNames = CollectCookieParameterNames(operationEntry.Value.Parameters);

                if (pathLevelCookieNames.Count == 0 && operationCookieNames.Count == 0)
                {
                    continue;
                }

                // Merge path-item-level params with operation-level params, preserving order
                // and de-duplicating in case the same name appears at both levels.
                var seen = new HashSet<string>(StringComparer.Ordinal);
                var names = new List<string>(pathLevelCookieNames.Count + operationCookieNames.Count);
                foreach (var name in pathLevelCookieNames.Concat(operationCookieNames))
                {
                    if (seen.Add(name))
                    {
                        names.Add(name);
                    }
                }

                var method = operationEntry.Key.ToString().ToUpperInvariant();
                var nameList = string.Join(", ", names);
                warnings.Add(
                    $"Operation {method} {pathEntry.Key}: cookie parameter(s) [{nameList}] are not emitted in the TypeScript client. Cookies are browser-managed — set credentials: 'include' on ApiClientOptions if you need them sent.");
            }
        }

        return warnings;
    }

    private static List<string> CollectCookieParameterNames(
        IList<IOpenApiParameter>? parameters)
    {
        if (parameters == null || parameters.Count == 0)
        {
            return [];
        }

        var names = new List<string>();
        foreach (var paramInterface in parameters)
        {
            var resolved = paramInterface.Resolve();
            if (resolved.Parameter is { In: ParameterLocation.Cookie } cookie)
            {
                names.Add(cookie.Name ?? "(unnamed)");
            }
        }

        return names;
    }

    /// <summary>
    /// Writes model files (interfaces and array type aliases) and their barrel export.
    /// </summary>
    private static int WriteModels(
        List<(string Name, TypeScriptInterfaceParameters Parameters)> models,
        List<(string Name, string Content)> arrayTypeAliases,
        List<(string Name, string Content)> unionTypeAliases,
        string outputPath,
        string? headerContent,
        bool includeZod,
        bool dryRun)
    {
        var totalCount = models.Count + arrayTypeAliases.Count + unionTypeAliases.Count;
        if (totalCount == 0)
        {
            return 0;
        }

        var modelsDir = Path.Combine(outputPath, "models");
        var jsDocGenerator = new JsDocCommentGenerator();
        var writer = new GenerateContentWriter(jsDocGenerator);

        foreach (var (name, parameters) in models)
        {
            var generator = new GenerateContentForInterface(writer, parameters);
            var content = generator.Generate();
            var filePath = Path.Combine(modelsDir, $"{name}.ts");
            WriteTsFile(filePath, content, dryRun);
        }

        // Write array type alias files (e.g., export type Accounts = Account[];)
        foreach (var (name, content) in arrayTypeAliases)
        {
            var filePath = Path.Combine(modelsDir, $"{name}.ts");
            WriteTsFile(filePath, content, dryRun);
        }

        // Write union type alias files (e.g., export type PaymentMethod = CreditCard | BankTransfer;)
        foreach (var (name, content) in unionTypeAliases)
        {
            var filePath = Path.Combine(modelsDir, $"{name}.ts");
            WriteTsFile(filePath, content, dryRun);
        }

        // Generate barrel export for all models (interfaces + array aliases + union aliases)
        var allModelNames = models.Select(m => m.Name)
            .Concat(arrayTypeAliases.Select(a => a.Name))
            .Concat(unionTypeAliases.Select(u => u.Name));

        var barrelParams = includeZod
            ? TypeScriptBarrelExportExtractor.CreateWithZod(headerContent, allModelNames)
            : TypeScriptBarrelExportExtractor.Create(headerContent, allModelNames);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(modelsDir, "index.ts"), barrelContent, dryRun);

        return totalCount;
    }

    /// <summary>
    /// Writes enum files and their barrel export.
    /// </summary>
    private static int WriteEnums(
        List<(string Name, string Content)> enums,
        string outputPath,
        string? headerContent,
        bool includeZod,
        bool dryRun)
    {
        if (enums.Count == 0)
        {
            return 0;
        }

        var enumsDir = Path.Combine(outputPath, "enums");

        foreach (var (name, content) in enums)
        {
            var filePath = Path.Combine(enumsDir, $"{name}.ts");
            WriteTsFile(filePath, content, dryRun);
        }

        // Generate barrel export for enums - use non-type-only for enum style Enum (they are values)
        var enumNames = enums.Select(e => e.Name);
        var barrelParams = includeZod
            ? TypeScriptBarrelExportExtractor.CreateWithZod(headerContent, enumNames, isTypeOnly: false)
            : TypeScriptBarrelExportExtractor.Create(headerContent, enumNames, isTypeOnly: false);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(enumsDir, "index.ts"), barrelContent, dryRun);

        return enums.Count;
    }

    /// <summary>
    /// Writes error type files and their barrel export.
    /// </summary>
    private static int WriteErrorTypes(
        string outputPath,
        string? headerContent,
        TypeScriptHttpClient httpClient,
        bool dryRun)
    {
        var errorsDir = Path.Combine(outputPath, "errors");

        var apiErrorContent = TypeScriptErrorExtractor.GenerateApiError(headerContent, httpClient);
        WriteTsFile(Path.Combine(errorsDir, "ApiError.ts"), apiErrorContent, dryRun);

        var validationErrorContent = TypeScriptErrorExtractor.GenerateValidationError(headerContent, httpClient);
        WriteTsFile(Path.Combine(errorsDir, "ValidationError.ts"), validationErrorContent, dryRun);

        // Generate barrel export for errors (not type-only, they are classes)
        var errorNames = new[] { "ApiError", "ValidationError" };
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, errorNames, isTypeOnly: false);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(errorsDir, "index.ts"), barrelContent, dryRun);

        return 2;
    }

    /// <summary>
    /// Writes the ApiResult type file and its barrel export.
    /// </summary>
    private static int WriteApiResultType(
        string outputPath,
        string? headerContent,
        TypeScriptHttpClient httpClient,
        bool zodRuntimeValidate,
        bool dryRun)
    {
        var typesDir = Path.Combine(outputPath, "types");

        var apiResultContent = TypeScriptApiResultExtractor.Generate(headerContent, httpClient, zodRuntimeValidate);
        WriteTsFile(Path.Combine(typesDir, "ApiResult.ts"), apiResultContent, dryRun);

        // Generate barrel export for types
        var typeNames = new[] { "ApiResult" };
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, typeNames);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(typesDir, "index.ts"), barrelContent, dryRun);

        return 1;
    }

    /// <summary>
    /// Writes client class files and their barrel export.
    /// </summary>
    private static (int Count, IReadOnlyList<string> SegmentNames) WriteClients(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        HashSet<string> enumNameSet,
        TypeScriptHttpClient httpClient,
        TypeScriptNamingStrategy namingStrategy,
        bool convertDates,
        bool hasRetry,
        bool dryRun,
        HashSet<string> writableSchemas,
        bool brandedIds,
        bool zodRuntimeValidate)
    {
        var clients = TypeScriptClientExtractor.Extract(openApiDoc, headerContent, enumNameSet, namingStrategy, convertDates, httpClient, writableSchemas, brandedIds, zodRuntimeValidate);
        if (clients.Count == 0)
        {
            return (0, Array.Empty<string>());
        }

        var clientDir = Path.Combine(outputPath, "client");

        // Write base ApiClient (fetch or axios)
        var apiClientContent = httpClient == TypeScriptHttpClient.Axios
            ? TypeScriptAxiosApiClientExtractor.Generate(headerContent, convertDates, hasRetry, zodRuntimeValidate)
            : TypeScriptFetchApiClientExtractor.Generate(headerContent, convertDates, hasRetry, zodRuntimeValidate);
        WriteTsFile(Path.Combine(clientDir, "ApiClient.ts"), apiClientContent, dryRun);

        // Write per-segment client files
        var segmentClientNames = new List<string>();
        foreach (var (className, content) in clients)
        {
            var filePath = Path.Combine(clientDir, $"{className}.ts");
            WriteTsFile(filePath, content, dryRun);
            segmentClientNames.Add(className);
        }

        // Write ApiService root orchestrator
        var apiServiceContent = TypeScriptApiServiceExtractor.Generate(headerContent, segmentClientNames);
        WriteTsFile(Path.Combine(clientDir, "ApiService.ts"), apiServiceContent, dryRun);

        // Generate barrel export for client directory (not type-only, they are classes)
        var clientNames = new List<string> { "ApiClient" };
        clientNames.AddRange(segmentClientNames);
        clientNames.Add("ApiService");
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, clientNames, isTypeOnly: false);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(clientDir, "index.ts"), barrelContent, dryRun);

        return (clients.Count, segmentClientNames);
    }

    /// <summary>
    /// Writes React Query hook files (ApiProvider, useApiService, per-segment hooks) and their barrel export.
    /// </summary>
    private static int WriteReactQueryHooks(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        HashSet<string> enumNameSet,
        TypeScriptNamingStrategy namingStrategy,
        bool convertDates,
        bool dryRun,
        HashSet<string> writableSchemas,
        TypeScriptHooksMode hooksMode,
        bool brandedIds)
    {
        var hooks = TypeScriptReactQueryHookExtractor.Extract(openApiDoc, headerContent, enumNameSet, namingStrategy, convertDates, writableSchemas, hooksMode, brandedIds);
        if (hooks.Count == 0)
        {
            return 0;
        }

        var hooksDir = Path.Combine(outputPath, "hooks");

        // Write ApiProvider.ts
        var providerContent = TypeScriptApiProviderExtractor.GenerateApiProvider(headerContent);
        WriteTsFile(
            Path.Combine(hooksDir, "ApiProvider.ts"),
            providerContent,
            dryRun);

        // Write useApiService.ts
        var useApiServiceContent = TypeScriptApiProviderExtractor.GenerateUseApiService(headerContent);
        WriteTsFile(
            Path.Combine(hooksDir, "useApiService.ts"),
            useApiServiceContent,
            dryRun);

        // Write per-segment hook files
        var hookFileNames = new List<string> { "ApiProvider", "useApiService" };
        foreach (var (fileName, content) in hooks)
        {
            var filePath = Path.Combine(hooksDir, fileName + ".ts");
            WriteTsFile(filePath, content, dryRun);
            hookFileNames.Add(fileName);
        }

        // Generate barrel export (not type-only, they export functions)
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, hookFileNames, isTypeOnly: false);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(
            Path.Combine(hooksDir, "index.ts"),
            barrelContent,
            dryRun);

        return hooks.Count;
    }

    /// <summary>
    /// Writes SWR hook files (ApiProvider, useApiService, per-segment hooks) and their barrel export.
    /// </summary>
    private static int WriteSwrHooks(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        HashSet<string> enumNameSet,
        TypeScriptNamingStrategy namingStrategy,
        bool dryRun,
        bool brandedIds)
    {
        var hooks = TypeScriptSwrHookExtractor.Extract(openApiDoc, headerContent, enumNameSet, namingStrategy, brandedIds);
        if (hooks.Count == 0)
        {
            return 0;
        }

        var hooksDir = Path.Combine(outputPath, "hooks");

        // Reuse ApiProvider and useApiService from React Query (same context pattern)
        var providerContent = TypeScriptApiProviderExtractor.GenerateApiProvider(headerContent);
        WriteTsFile(Path.Combine(hooksDir, "ApiProvider.ts"), providerContent, dryRun);

        var useApiServiceContent = TypeScriptApiProviderExtractor.GenerateUseApiService(headerContent);
        WriteTsFile(Path.Combine(hooksDir, "useApiService.ts"), useApiServiceContent, dryRun);

        // Write per-segment hook files
        var hookFileNames = new List<string> { "ApiProvider", "useApiService" };
        foreach (var (fileName, content) in hooks)
        {
            var filePath = Path.Combine(hooksDir, fileName + ".ts");
            WriteTsFile(filePath, content, dryRun);
            hookFileNames.Add(fileName);
        }

        // Generate barrel export
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, hookFileNames, isTypeOnly: false);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        WriteTsFile(Path.Combine(hooksDir, "index.ts"), barrelGenerator.Generate(), dryRun);

        return hooks.Count;
    }

    /// <summary>
    /// Writes Zod validation schema files for enums, models, and array type aliases.
    /// </summary>
    private static int WriteZodSchemas(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        TypeScriptClientConfig config,
        HashSet<string> enumNameSet,
        bool dryRun)
    {
        var zodCount = 0;

        // Generate Zod enum schemas
        var zodEnums = TypeScriptZodEnumExtractor.Extract(openApiDoc, config);
        if (zodEnums.Count > 0)
        {
            var enumsDir = Path.Combine(outputPath, "enums");
            foreach (var (name, content) in zodEnums)
            {
                var filePath = Path.Combine(enumsDir, $"{name}.zod.ts");
                WriteTsFile(filePath, content, dryRun);
            }

            zodCount += zodEnums.Count;
        }

        // Generate Zod model schemas
        var zodModels = TypeScriptZodModelExtractor.Extract(openApiDoc, config, enumNameSet);
        if (zodModels.Count > 0)
        {
            var modelsDir = Path.Combine(outputPath, "models");
            foreach (var (name, content) in zodModels)
            {
                var filePath = Path.Combine(modelsDir, $"{name}.zod.ts");
                WriteTsFile(filePath, content, dryRun);
            }

            zodCount += zodModels.Count;
        }

        // Generate Zod array type alias schemas
        var zodArrays = TypeScriptZodModelExtractor.ExtractArrayTypeAliases(openApiDoc, config);
        if (zodArrays.Count > 0)
        {
            var modelsDir = Path.Combine(outputPath, "models");
            foreach (var (name, content) in zodArrays)
            {
                var filePath = Path.Combine(modelsDir, $"{name}.zod.ts");
                WriteTsFile(filePath, content, dryRun);
            }

            zodCount += zodArrays.Count;
        }

        return zodCount;
    }

    /// <summary>
    /// Writes the root barrel export (index.ts) that re-exports from subdirectories.
    /// </summary>
    /// <summary>
    /// Writes <c>servers/Servers.ts</c> + <c>servers/index.ts</c> when the spec declares
    /// more than one <c>servers:</c> entry. Single-server specs keep the existing
    /// single-baseUrl ctor pattern; emitting a one-entry Servers const would add noise
    /// without giving the consumer a real choice.
    /// </summary>
    /// <summary>
    /// Writes <c>types/BrandedIds.ts</c> when --branded-ids is enabled and the spec
    /// has at least one qualifying property or path parameter. The <c>types/</c>
    /// barrel is rewritten to include the new module alongside ApiResult.
    /// </summary>
    private static bool WriteBrandedIdsFile(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        bool dryRun)
    {
        var brands = TypeScriptBrandedIdExtractor.CollectBrandNames(openApiDoc);
        if (brands.Count == 0)
        {
            return false;
        }

        var content = TypeScriptBrandedIdExtractor.Generate(brands, headerContent);
        if (content == null)
        {
            return false;
        }

        var typesDir = Path.Combine(outputPath, "types");
        WriteTsFile(Path.Combine(typesDir, "BrandedIds.ts"), content, dryRun);

        // Rewrite the types/ barrel to include BrandedIds alongside ApiResult.
        // ApiResult is unconditional (every spec emits it), BrandedIds is new.
        var typeNames = new[] { "ApiResult", "BrandedIds" };
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, typeNames);
        var barrelContent = new GenerateContentForBarrelExport(barrelParams).Generate();
        WriteTsFile(Path.Combine(typesDir, "index.ts"), barrelContent, dryRun);

        return true;
    }

    private static bool WriteServersFile(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        bool dryRun)
    {
        var content = TypeScriptServersExtractor.Generate(openApiDoc, headerContent);
        if (content == null)
        {
            return false;
        }

        var serversDir = Path.Combine(outputPath, "servers");
        WriteTsFile(Path.Combine(serversDir, "Servers.ts"), content, dryRun);

        // Barrel: re-exports both the Servers const and the ServerName type union.
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, new[] { "Servers" }, isTypeOnly: false);
        var barrelContent = new GenerateContentForBarrelExport(barrelParams).Generate();
        WriteTsFile(Path.Combine(serversDir, "index.ts"), barrelContent, dryRun);

        return true;
    }

    /// <summary>
    /// Writes <c>webhooks/Webhooks.ts</c> + <c>webhooks/index.ts</c> when at least one
    /// operation declares a <c>callbacks:</c> block whose body references a named
    /// component schema. Inline callback bodies are skipped (no canonical name to alias).
    /// </summary>
    private static bool WriteWebhooksFile(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        bool dryRun)
    {
        var content = TypeScriptWebhookExtractor.Generate(openApiDoc, headerContent);
        if (content == null)
        {
            return false;
        }

        var webhooksDir = Path.Combine(outputPath, "webhooks");
        WriteTsFile(Path.Combine(webhooksDir, "Webhooks.ts"), content, dryRun);

        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, new[] { "Webhooks" });
        var barrelContent = new GenerateContentForBarrelExport(barrelParams).Generate();
        WriteTsFile(Path.Combine(webhooksDir, "index.ts"), barrelContent, dryRun);

        return true;
    }

    /// <summary>
    /// Writes per-hub <c>useXxxHub.ts</c> files plus a <c>hubs/index.ts</c> barrel
    /// when the document declares an <c>x-signalr-hubs</c> vendor extension. The hooks
    /// own the SignalR connection lifecycle and forward inbound events to caller-supplied
    /// optional callbacks. No-op when the extension is missing or declares no hubs.
    /// </summary>
    private static bool WriteSignalRHubFiles(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        bool dryRun)
    {
        var hubs = TypeScriptSignalRHubExtractor.Extract(openApiDoc, headerContent);
        if (hubs.Count == 0)
        {
            return false;
        }

        var hubsDir = Path.Combine(outputPath, "hubs");
        var hookFileNames = new List<string>();
        foreach (var (fileName, content) in hubs)
        {
            WriteTsFile(Path.Combine(hubsDir, fileName + ".ts"), content, dryRun);
            hookFileNames.Add(fileName);
        }

        // Barrel — exports functions, not type-only.
        var barrelParams = TypeScriptBarrelExportExtractor.Create(headerContent, hookFileNames, isTypeOnly: false);
        var barrelContent = new GenerateContentForBarrelExport(barrelParams).Generate();
        WriteTsFile(Path.Combine(hubsDir, "index.ts"), barrelContent, dryRun);

        return true;
    }

    private static void WriteRootBarrelExport(
        string outputPath,
        string? headerContent,
        List<string> subdirectories,
        bool dryRun)
    {
        var barrelParams = TypeScriptBarrelExportExtractor.CreateForSubdirectories(headerContent, subdirectories);
        var barrelGenerator = new GenerateContentForBarrelExport(barrelParams);
        var barrelContent = barrelGenerator.Generate();
        WriteTsFile(Path.Combine(outputPath, "index.ts"), barrelContent, dryRun);
    }

    /// <summary>
    /// Writes package.json, tsconfig.json, and README.md scaffold files.
    /// </summary>
    private static bool WritePackageScaffold(
        OpenApiDocument openApiDoc,
        string outputPath,
        TypeScriptClientConfig config,
        IReadOnlyList<string> segmentClientNames,
        bool dryRun)
    {
        var packageName = config.PackageName
            ?? TypeScriptPackageScaffoldExtractor.DerivePackageName(openApiDoc.Info?.Title ?? string.Empty);

        var description = openApiDoc.Info?.Description;

        var packageJsonContent = TypeScriptPackageScaffoldExtractor.GeneratePackageJson(
            packageName,
            config.PackageVersion,
            description,
            config);
        WriteJsonFile(Path.Combine(outputPath, "package.json"), packageJsonContent, dryRun);

        var tsConfigContent = TypeScriptPackageScaffoldExtractor.GenerateTsConfig();
        WriteJsonFile(Path.Combine(outputPath, "tsconfig.json"), tsConfigContent, dryRun);

        var tsConfigCjsContent = TypeScriptPackageScaffoldExtractor.GenerateTsConfigCjs();
        WriteJsonFile(Path.Combine(outputPath, "tsconfig.cjs.json"), tsConfigCjsContent, dryRun);

        var postbuildContent = TypeScriptPackageScaffoldExtractor.GeneratePostbuildCjsScript();
        WriteTextFile(Path.Combine(outputPath, "scripts", "postbuild-cjs.mjs"), postbuildContent, dryRun);

        var readmeContent = TypeScriptPackageScaffoldExtractor.GenerateReadme(
            packageName,
            openApiDoc.Info?.Title,
            description,
            segmentClientNames,
            config);
        WriteTextFile(Path.Combine(outputPath, "README.md"), readmeContent, dryRun);

        return true;
    }

    /// <summary>
    /// Writes a UTF-8 text file (no BOM), skipping the actual write when dry-run is active.
    /// Used for non-TS/non-JSON artifacts like README.md.
    /// </summary>
    private static void WriteTextFile(
        string filePath,
        string content,
        bool dryRun)
    {
        if (dryRun)
        {
            return;
        }

        var dir = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        File.WriteAllText(filePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    /// <summary>
    /// Writes a TypeScript file, skipping the actual write when dry-run is active.
    /// </summary>
    private static void WriteTsFile(
        string filePath,
        string content,
        bool dryRun)
    {
        if (dryRun)
        {
            return;
        }

        CodeGeneration.TypeScript.Helpers.FileHelper.WriteTsFile(filePath, content);
    }

    /// <summary>
    /// Writes a JSON file with UTF-8 encoding (no BOM), skipping the actual write when dry-run is active.
    /// </summary>
    private static void WriteJsonFile(
        string filePath,
        string content,
        bool dryRun)
    {
        if (dryRun)
        {
            return;
        }

        var directory = Path.GetDirectoryName(filePath);
        if (directory != null && !Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(filePath, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }

    private static bool HasPaginationSchemas(OpenApiDocument openApiDoc)
    {
        if (openApiDoc.Components?.Schemas == null)
        {
            return false;
        }

        foreach (var schemaPair in openApiDoc.Components.Schemas)
        {
            // Check explicit x-pagination annotation first (authoritative)
            var annotation = schemaPair.Value.GetPaginationAnnotation();
            if (annotation == true)
            {
                return true;
            }

            // Heuristic fallback: check schema name convention
            if (annotation == null &&
                (schemaPair.Key.StartsWith("PaginationResult", StringComparison.Ordinal) ||
                 schemaPair.Key.StartsWith("PaginatedResult", StringComparison.Ordinal) ||
                 schemaPair.Key.StartsWith("PagedResult", StringComparison.Ordinal)))
            {
                return true;
            }
        }

        return false;
    }

    private static int WriteMswHandlers(
        OpenApiDocument openApiDoc,
        string outputPath,
        string? headerContent,
        TypeScriptClientConfig config,
        bool dryRun)
    {
        var baseUrl = string.Empty;

        var handlers = TypeScriptMswHandlerExtractor.Extract(
            openApiDoc,
            headerContent,
            baseUrl,
            config.NamingStrategy);

        if (handlers.Count == 0)
        {
            return 0;
        }

        var mocksDir = Path.Combine(outputPath, "mocks");
        var moduleNames = new List<string>();
        foreach (var (segmentName, content) in handlers)
        {
            // segmentName == "handlers" is the synthetic combined-index module — the
            // per-segment files are named after their path segment.
            var moduleName = segmentName == "handlers"
                ? "handlers"
                : segmentName.EnsureFirstCharacterToLower();
            var filePath = Path.Combine(mocksDir, moduleName + ".ts");
            WriteTsFile(filePath, content, dryRun);
            moduleNames.Add(moduleName);
        }

        // The root barrel (api/index.ts) does `export * from './mocks'` whenever any MSW
        // handler files exist; that requires a real mocks/index.ts. Without this barrel,
        // strict tsc -b emits TS2307: Cannot find module './mocks'.
        var mocksBarrel = TypeScriptBarrelExportExtractor.Create(headerContent, moduleNames, isTypeOnly: false);
        var mocksBarrelContent = new GenerateContentForBarrelExport(mocksBarrel).Generate();
        WriteTsFile(Path.Combine(mocksDir, "index.ts"), mocksBarrelContent, dryRun);

        // Exclude the combined "handlers" index from count
        return handlers.Count - 1;
    }
}