// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using PetStoreSimple.Generated;
using PetStoreSimple.Generated.Pets.Models;

namespace PetStoreSimple.Generated.Pets.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Info for a specific pet
/// Operation: ShowPetById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IShowPetByIdEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsNotFound { get; }

    bool IsInternalServerError { get; }

    Pet OkContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails NotFoundContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}