// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OpenApi32Features.Generated.Colors.Handlers;
using OpenApi32Features.Generated.Colors.Models;
using OpenApi32Features.Generated.Colors.Results;

namespace OpenApi32Features.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Colors.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ColorsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/colors";

    public void DefineEndpoints(WebApplication app)
    {
        var colors = app
            .MapGroup(ApiRouteBase)
            .WithTags("Colors");

        colors
            .MapGet("/", GetColors)
            .WithName("GetColors")
            .WithSummary("Get RGB colors")
            .Produces<RgbColor>()
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> GetColors(
        [FromServices] IGetColorsHandler handler,
        CancellationToken cancellationToken)
        => GetColorsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}