// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using ModelsAndProperties.Generated.Models;
using ModelsAndProperties.Generated.Validations.Models;

namespace ModelsAndProperties.Generated.Validations.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IValidationsClient
{
    Task<ValidationConstraints> GetValidationsAsync(CancellationToken cancellationToken = default);
}