// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using ModelsAndProperties.Generated.Models;
using ModelsAndProperties.Generated.Persons.Models;

namespace ModelsAndProperties.Generated.Persons.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class PersonsClient : IPersonsClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public PersonsClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public PersonsClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async Task<List<Person>> ListPersonsAsync(
        ListPersonsParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/persons";
        var queryParams = new List<string>();

        if (parameters.Gender is not null)
        {
            queryParams.Add($"gender={Uri.EscapeDataString($"{parameters.Gender}")}");
        }

        if (queryParams.Count > 0)
        {
            url += "?" + string.Join("&", queryParams);
        }

        return (await httpClient.GetFromJsonAsync<List<Person>>(url, jsonSerializerOptions, cancellationToken))!;
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}