// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;

namespace ModelsAndProperties.Generated.Animals.Client;

/// <summary>
/// Registration extensions for <see cref="IAnimalsClient"/>.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class AnimalsClientServiceCollectionExtensions
{
    /// <summary>
    /// Adds <see cref="AnimalsClient"/> as <see cref="IAnimalsClient"/> using IHttpClientFactory.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional callback to configure the underlying <see cref="HttpClient"/>.</param>
    public static IHttpClientBuilder AddAnimalsClient(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null)
    {
        if (services is null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        // An explicit factory is used because the generated client exposes both a
        // (HttpClient) and a (HttpClient, JsonSerializerOptions) constructor, which
        // ActivatorUtilities cannot disambiguate on its own.
        if (configureClient is null)
        {
            return services.AddHttpClient<IAnimalsClient>()
                .AddTypedClient<IAnimalsClient>(
                    static (httpClient, _) => new AnimalsClient(httpClient));
        }

        return services.AddHttpClient<IAnimalsClient>(configureClient)
            .AddTypedClient<IAnimalsClient>(
                static (httpClient, _) => new AnimalsClient(httpClient));
    }
}