// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace Polymorphism.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record EmailNotification : Notification(
    [property: Required] string Kind,
    [property: Required, EmailAddress] string To,
    [property: Required, MaxLength(200)] string Subject,
    [property: Required, MaxLength(10000)] string Body,
    bool IsHtml = false);