// <auto-generated />
namespace Polymorphism.Generated.Models;

public sealed record PushNotification : Notification(
    [property: Required] string Kind,
    [property: Required] string DeviceToken,
    [property: Required, MaxLength(100)] string Title,
    [property: MaxLength(500)] string? Body,
    [property: Range(0, long.MaxValue)] int? Badge,
    string? Sound);