// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SecurityAtcExt.Generated.ApiKeys.Handlers;
using SecurityAtcExt.Generated.ApiKeys.Models;
using SecurityAtcExt.Generated.ApiKeys.Results;

namespace SecurityAtcExt.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for ApiKeys.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ApiKeysEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/api-keys";

    public void DefineEndpoints(WebApplication app)
    {
        var apikeys = app
            .MapGroup(ApiRouteBase)
            .WithTags("ApiKeys")
            .RequireAuthorization();

        apikeys
            .MapGet("/", ListApiKeys)
            .WithName("ListApiKeys")
            .WithSummary("List API keys (Bearer OR ApiKey scheme)")
            .Produces<List<ApiKey>>()
            .ProducesProblem(StatusCodes.Status401Unauthorized)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .RequireAuthorization(policy => policy
                .AddAuthenticationSchemes("Bearer", "ApiKey")
                .RequireAuthenticatedUser());
    }

    internal async Task<IResult> ListApiKeys(
        [FromServices] IListApiKeysHandler handler,
        CancellationToken cancellationToken)
        => ListApiKeysResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}