// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Builder;

using SecurityAtcExt.Generated.Admins.Endpoints;
using SecurityAtcExt.Generated.ApiKeys.Endpoints;
using SecurityAtcExt.Generated.Orders.Endpoints;
using SecurityAtcExt.Generated.Publics.Endpoints;
using SecurityAtcExt.Generated.Reports.Endpoints;

namespace SecurityAtcExt.Generated.Endpoints;

/// <summary>
/// Extension methods for mapping all API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointMappingExtensions
{
    /// <summary>
    /// Maps all API endpoints from all path segments.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>The web application for method chaining.</returns>
    public static WebApplication MapEndpoints(this WebApplication app)
    {
        app.MapAdminsEndpoints();
        app.MapApiKeysEndpoints();
        app.MapOrdersEndpoints();
        app.MapPublicsEndpoints();
        app.MapReportsEndpoints();

        return app;
    }
}