// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace PetStoreFull.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record Pet(
    long Id,
    [property: Required] string Name,
    Category Category,
    [property: Required] List<string> PhotoUrls,
    List<Tag> Tags,
    string Status);