// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityAtcExt.Generated;
using SecurityAtcExt.Generated.ApiKeys.Models;

namespace SecurityAtcExt.Generated.ApiKeys.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List API keys (Bearer OR ApiKey scheme)
/// Operation: ListApiKeys.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListApiKeysEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsInternalServerError { get; }

    IEnumerable<ApiKey> OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}