// <auto-generated />
import { ApiClient } from './ApiClient';
import type { HealthStatus } from '../models';

export type GetHealthResult =
  | { status: 'ok'; data: HealthStatus; response: Response }
  | { status: 'parseError'; error: Error; response: Response };

export class HealthClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** Health check (global retry policy) */
  async getHealth(): Promise<GetHealthResult> {
    return this.api.request<HealthStatus>('GET', '/health') as Promise<GetHealthResult>;
  }
}