// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityOpenIdConnect.Generated.Me.Endpoints.Results;

namespace SecurityOpenIdConnect.Generated.Me.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Get current user profile
/// Operation: GetCurrentUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetCurrentUserEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetCurrentUserEndpointResult> ExecuteAsync(
        string httpClientName = "SecurityOpenIdConnect-ApiClient",
        CancellationToken cancellationToken = default);
}