// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using AllOfMultiLevel.Generated.Models;

namespace AllOfMultiLevel.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class AllOfMultiLevelClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public AllOfMultiLevelClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public AllOfMultiLevelClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async Task<List<Person>> ListPeopleAsync(CancellationToken cancellationToken = default)
    {
        var url = "/people";
        return (await httpClient.GetFromJsonAsync<List<Person>>(url, jsonSerializerOptions, cancellationToken))!;
    }

    public async Task<Person> CreatePersonAsync(
        CreatePersonParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/people";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, jsonSerializerOptions, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
        return (await response.Content.ReadFromJsonAsync<Person>(jsonSerializerOptions, cancellationToken))!;
    }

    public async Task<List<Employee>> ListEmployeesAsync(CancellationToken cancellationToken = default)
    {
        var url = "/employees";
        return (await httpClient.GetFromJsonAsync<List<Employee>>(url, jsonSerializerOptions, cancellationToken))!;
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}