// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using Retry.Generated;
using Retry.Generated.Orders.Models;

namespace Retry.Generated.Orders.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List orders (fast retry policy)
/// Operation: ListOrders.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOrdersEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsInternalServerError { get; }

    IEnumerable<Order> OkContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}