// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using ComponentsReuse.Generated.Models;
using ComponentsReuse.Generated.Parameters;
using ComponentsReuse.Generated.Results;

namespace ComponentsReuse.Generated.Handlers;

/// <summary>
/// Get item by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetItemByIdHandler
{
    Task<GetItemByIdResult> ExecuteAsync(
        GetItemByIdParameters parameters,
        CancellationToken cancellationToken = default);
}