// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';
import type { Notification } from '../models';

export class NotificationsClient {
  constructor(private readonly api: ApiClient) {}

  async sendNotification(body: Notification): Promise<ApiResult<void>> {
    return this.api.request<void>('POST', '/notifications', {
      body,
    });
  }

  async listNotifications(): Promise<ApiResult<Notification[]>> {
    return this.api.request<Notification[]>('GET', '/notifications');
  }
}