// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using VersioningQueryString.Generated.Owners.Handlers;
using VersioningQueryString.Generated.Pets.Handlers;

namespace VersioningQueryString;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ApiHandlerServiceCollectionExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>
    /// The service collection for method chaining.
    /// </returns>
    public static IServiceCollection AddApiHandlersFromVersioningQueryString(this IServiceCollection services)
    {
        services.AddScoped<ICreateOwnerHandler, global::VersioningQueryString.ApiHandlers.CreateOwnerHandler>();
        services.AddScoped<ICreatePetHandler, global::VersioningQueryString.ApiHandlers.CreatePetHandler>();
        services.AddScoped<IDeletePetHandler, global::VersioningQueryString.ApiHandlers.DeletePetHandler>();
        services.AddScoped<IGetOwnerByIdHandler, global::VersioningQueryString.ApiHandlers.GetOwnerByIdHandler>();
        services.AddScoped<IGetPetByIdHandler, global::VersioningQueryString.ApiHandlers.GetPetByIdHandler>();
        services.AddScoped<IListOwnersHandler, global::VersioningQueryString.ApiHandlers.ListOwnersHandler>();
        services.AddScoped<IListPetsHandler, global::VersioningQueryString.ApiHandlers.ListPetsHandler>();
        services.AddScoped<IUpdatePetHandler, global::VersioningQueryString.ApiHandlers.UpdatePetHandler>();

        return services;
    }
}