// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using CookieParameters.Generated;
using CookieParameters.Generated.Session.Models;

namespace CookieParameters.Generated.Session.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Get current session
/// Operation: GetSession.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetSessionEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsBadRequest { get; }

    bool IsInternalServerError { get; }

    bool IsGatewayTimeout { get; }

    Session OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails InternalServerErrorContent { get; }

    ProblemDetails GatewayTimeoutContent { get; }
}