// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using ReadOnlyWriteOnly.Generated.Models;

namespace ReadOnlyWriteOnly.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ReadOnlyWriteOnlyClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public ReadOnlyWriteOnlyClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public ReadOnlyWriteOnlyClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async Task<User> CreateUserAsync(
        CreateUserParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/users";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, jsonSerializerOptions, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
        return (await response.Content.ReadFromJsonAsync<User>(jsonSerializerOptions, cancellationToken))!;
    }

    public async Task<User> GetUserByIdAsync(
        GetUserByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/users/{parameters.UserId}";
        return (await httpClient.GetFromJsonAsync<User>(url, jsonSerializerOptions, cancellationToken))!;
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}