// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityStandard.Generated;
using SecurityStandard.Generated.Publics.Models;

namespace SecurityStandard.Generated.Publics.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Health check (public)
/// Operation: GetHealth.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetHealthEndpointResult : IEndpointResponse
{
    bool IsOk { get; }

    bool IsInternalServerError { get; }

    HealthStatus OkContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}