// <auto-generated />
import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions } from '@tanstack/react-query';
import { useApiService } from './useApiService';
import { ApiError } from '../errors/ApiError';
import type { Pet } from '../models';
import type { PetId } from '../types/BrandedIds';

const petsKeys = {
  all: ['pets'] as const,
  getPet: (petId: PetId) => [...petsKeys.all, 'getPet', petId] as const,
};

export { petsKeys };

export function useGetPet(petId: PetId, options?: Omit<UseQueryOptions<Pet, ApiError>, 'queryKey' | 'queryFn'>) {
  const api = useApiService();
  return useQuery({
    queryKey: petsKeys.getPet(petId),
    queryFn: async () => {
      const result = await api.pets.getPet(petId);
      if (result.status === 'ok') {
        return result.data;
      }
      throw new ApiError(
        result.response.status,
        result.response.statusText,
        'error' in result ? result.error.message : 'Request failed',
        result.response,
      );
    },
    enabled: !!petId,
    ...options,
  });
}