// <auto-generated />
using System;
using System.Threading;
using System.Threading.Tasks;
using SecurityHybrid.Generated.Models;
using SecurityHybrid.Generated.Parameters;
using SecurityHybrid.Generated.Results;

namespace SecurityHybrid.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: listReports.
/// </summary>
public sealed class ListReportsHandler : IListReportsHandler
{
    public Task<ListReportsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("listReports not implemented");
    }
}