// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;

namespace SecurityStandard.Generated.Users.Client;

/// <summary>
/// Registration extensions for <see cref="IUsersClient"/>.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class UsersClientServiceCollectionExtensions
{
    /// <summary>
    /// Adds <see cref="UsersClient"/> as <see cref="IUsersClient"/> using IHttpClientFactory.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="configureClient">Optional callback to configure the underlying <see cref="HttpClient"/>.</param>
    public static IHttpClientBuilder AddUsersClient(
        this IServiceCollection services,
        Action<HttpClient>? configureClient = null)
    {
        if (services is null)
        {
            throw new ArgumentNullException(nameof(services));
        }

        // An explicit factory is used because the generated client exposes both a
        // (HttpClient) and a (HttpClient, JsonSerializerOptions) constructor, which
        // ActivatorUtilities cannot disambiguate on its own.
        if (configureClient is null)
        {
            return services.AddHttpClient<IUsersClient>()
                .AddTypedClient<IUsersClient>(
                    static (httpClient, _) => new UsersClient(httpClient));
        }

        return services.AddHttpClient<IUsersClient>(configureClient)
            .AddTypedClient<IUsersClient>(
                static (httpClient, _) => new UsersClient(httpClient));
    }
}