// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using SecurityStandard.Generated.Users.Models;

namespace SecurityStandard.Generated.Users.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IUsersClient
{
    Task<List<User>> ListUsersAsync(CancellationToken cancellationToken = default);

    Task<User> GetUserByIdAsync(
        GetUserByIdParameters parameters,
        CancellationToken cancellationToken = default);
}