// <auto-generated />
export interface CreditCard {
  /** Discriminator value */
  readonly type: string;

  /** Credit card number */
  readonly cardNumber: string;

  /** Expiry date in MM/YY format */
  readonly expiryDate: string;

  /** Card verification value */
  readonly cvv?: string | null;

  /** Name on the card */
  readonly cardholderName?: string | null;
}