// <auto-generated />
export interface SmsNotification {
  /** Notification type identifier */
  readonly kind: string;

  /** Phone number in E.164 format */
  readonly phoneNumber: string;

  /** SMS message content */
  readonly message: string;
}