// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;

namespace RateLimit.Generated.RateLimiting;

/// <summary>
/// Rate limit policy name constants generated from OpenAPI extensions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class RateLimitPolicies
{
    /// <summary>
    /// Policy: Concurrency window, 5 requests/60s
    /// </summary>
    public const string ExportsConcurrent = "exports-concurrent";

    /// <summary>
    /// Policy: Fixed window, 1000 requests/60s
    /// </summary>
    public const string Global = "global";

    /// <summary>
    /// Policy: TokenBucket window, 200 requests/60s
    /// </summary>
    public const string NotificationsBurst = "notifications-burst";

    /// <summary>
    /// Policy: Fixed window, 100 requests/60s
    /// </summary>
    public const string OrdersStandard = "orders-standard";

    /// <summary>
    /// Policy: Fixed window, 10 requests/60s
    /// </summary>
    public const string OrdersStrict = "orders-strict";

    /// <summary>
    /// Policy: Sliding window, 50 requests/120s
    /// </summary>
    public const string ReportsSliding = "reports-sliding";
}