// <auto-generated />
import { ApiClient } from './ApiClient';
import type { ApiResult } from '../types/ApiResult';

export class ReportsClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  async getTextReport(): Promise<ApiResult<string>> {
    return this.api.request<string>('GET', '/reports/text', {
      responseType: 'text',
    });
  }
}