// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Net.ServerSentEvents;
using System.Runtime.CompilerServices;
using System.Threading;
using Atc.Rest.Client.Serialization;

namespace StreamingItemSchema.Generated.Streaming;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
internal static class StreamReaders
{
    public static async IAsyncEnumerable<T?> ReadServerSentEventsAsync<T>(
        Stream stream,
        IContractSerializer serializer,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var parser = SseParser.Create(
            stream,
            (eventType, bytes) => serializer.Deserialize<T>(bytes.ToArray()));

        await foreach (var item in parser.EnumerateAsync(cancellationToken))
        {
            yield return item.Data;
        }
    }
}