// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using SecurityOpenIdConnect.Generated;
using SecurityOpenIdConnect.Generated.Resources.Models;

namespace SecurityOpenIdConnect.Generated.Resources.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: List user resources
/// Operation: ListResources.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListResourcesEndpointResult : IEndpointResponse
{
    new bool IsOk { get; }

    bool IsUnauthorized { get; }

    bool IsForbidden { get; }

    bool IsInternalServerError { get; }

    IEnumerable<Resource> OkContent { get; }

    ProblemDetails UnauthorizedContent { get; }

    ProblemDetails ForbiddenContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}