// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RateLimit.Generated.Exports.Handlers;
using RateLimit.Generated.Exports.Models;
using RateLimit.Generated.Exports.Parameters;
using RateLimit.Generated.Exports.Results;
using RateLimit.Generated.RateLimiting;

namespace RateLimit.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Exports.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ExportsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/exports";

    public void DefineEndpoints(WebApplication app)
    {
        var exports = app
            .MapGroup(ApiRouteBase)
            .WithTags("Exports")
            .RequireRateLimiting(RateLimitPolicies.ExportsConcurrent);

        exports
            .MapPost("/", CreateExport)
            .WithName("CreateExport")
            .WithSummary("Create export (concurrency limited)")
            .Produces<ExportJob>(StatusCodes.Status202Accepted)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status429TooManyRequests)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> CreateExport(
        [FromServices] ICreateExportHandler handler,
        [AsParameters] CreateExportParameters parameters,
        CancellationToken cancellationToken)
        => CreateExportResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}