// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RateLimit.Generated.Notifications.Handlers;
using RateLimit.Generated.Notifications.Models;
using RateLimit.Generated.Notifications.Parameters;
using RateLimit.Generated.Notifications.Results;

namespace RateLimit.Generated.Notifications.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for Notifications.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class NotificationsEndpointDefinition : IEndpointDefinition
{
    public void DefineEndpoints(WebApplication app)
    {
        var notifications = app
            .MapGroup("/notifications")
            .WithTags("Notifications")
            .RequireRateLimiting("notifications-burst");

        notifications
            .MapPost("/", SendNotification)
            .WithName("SendNotification")
            .WithSummary("Send notification (token bucket with queue)")
            .Produces(StatusCodes.Status202Accepted)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status429TooManyRequests)
            .ProducesProblem(StatusCodes.Status500InternalServerError);
    }

    internal async Task<IResult> SendNotification(
        [FromServices] ISendNotificationHandler handler,
        [AsParameters] SendNotificationParameters parameters,
        CancellationToken cancellationToken)
        => SendNotificationResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapNotificationsEndpoints(this WebApplication app)
    {
        new NotificationsEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}