// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RateLimit.Generated.Reports.Handlers;
using RateLimit.Generated.Reports.Models;
using RateLimit.Generated.Reports.Results;
using RateLimit.Generated.RateLimiting;

namespace RateLimit.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Reports.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ReportsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/reports";

    public void DefineEndpoints(WebApplication app)
    {
        var reports = app
            .MapGroup(ApiRouteBase)
            .WithTags("Reports")
            .RequireRateLimiting(RateLimitPolicies.ReportsSliding);

        reports
            .MapGet("/", ListReports)
            .WithName("ListReports")
            .WithSummary("List reports (sliding window)")
            .Produces<List<Report>>()
            .ProducesProblem(StatusCodes.Status429TooManyRequests)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> ListReports(
        [FromServices] IListReportsHandler handler,
        CancellationToken cancellationToken)
        => ListReportsResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}