// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RateLimit.Generated.Webhooks.Handlers;
using RateLimit.Generated.Webhooks.Models;
using RateLimit.Generated.Webhooks.Parameters;
using RateLimit.Generated.Webhooks.Results;
using RateLimit.Generated.RateLimiting;

namespace RateLimit.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Webhooks.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class WebhooksEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/webhooks";

    public void DefineEndpoints(WebApplication app)
    {
        var webhooks = app
            .MapGroup(ApiRouteBase)
            .WithTags("Webhooks");

        webhooks
            .MapPost("/", ReceiveWebhook)
            .WithName("ReceiveWebhook")
            .WithSummary("Receive webhook (rate limiting disabled)")
            .Produces(StatusCodes.Status200OK)
            .ProducesValidationProblem()
            .ProducesProblem(StatusCodes.Status409Conflict)
            .ProducesProblem(StatusCodes.Status429TooManyRequests)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .DisableRateLimiting();
    }

    internal async Task<IResult> ReceiveWebhook(
        [FromServices] IReceiveWebhookHandler handler,
        [AsParameters] ReceiveWebhookParameters parameters,
        CancellationToken cancellationToken)
        => ReceiveWebhookResult.ToIResult(
                    await handler.ExecuteAsync(
                        parameters,
                        cancellationToken));
}