// <auto-generated />
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using SecurityAtcExt.Generated.Models;
using SecurityAtcExt.Generated.Parameters;
using SecurityAtcExt.Generated.Results;

namespace SecurityAtcExt.Generated.Handlers;

/// <summary>
/// Get admin settings (Bearer + admin role).
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetAdminSettingsHandler
{
    Task<GetAdminSettingsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}