// <auto-generated />
namespace SecurityAtcExt.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: updateAdminSettings.
/// </summary>
public sealed class UpdateAdminSettingsHandler : IUpdateAdminSettingsHandler
{
    public Task<UpdateAdminSettingsResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("updateAdminSettings not implemented");
    }
}