// <auto-generated />
namespace SecurityOpenIdConnect.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public class SecurityOpenIdConnectClient
{
    private readonly HttpClient httpClient;

    public SecurityOpenIdConnectClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
    }

    public async Task<HealthStatus> GetHealthAsync(CancellationToken cancellationToken = default)
    {
        var url = "/health";
        return (await httpClient.GetFromJsonAsync<HealthStatus>(url, cancellationToken))!;
    }

    public async Task<UserProfile> GetCurrentUserAsync(CancellationToken cancellationToken = default)
    {
        var url = "/me";
        return (await httpClient.GetFromJsonAsync<UserProfile>(url, cancellationToken))!;
    }

    public async Task<UserProfile> GetCurrentUserProfileAsync(CancellationToken cancellationToken = default)
    {
        var url = "/me/profile";
        return (await httpClient.GetFromJsonAsync<UserProfile>(url, cancellationToken))!;
    }

    public async Task<List<Resource>> ListResourcesAsync(CancellationToken cancellationToken = default)
    {
        var url = "/resources";
        return (await httpClient.GetFromJsonAsync<List<Resource>>(url, cancellationToken))!;
    }

    public async Task<Resource> CreateResourceAsync(
        CreateResourceParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/resources";
        var response = await httpClient.PostAsJsonAsync(url, parameters.Request, cancellationToken);
        response.EnsureSuccessStatusCode();
        return (await response.Content.ReadFromJsonAsync<Resource>(cancellationToken: cancellationToken))!;
    }

    public async Task<Resource> GetResourceByIdAsync(
        GetResourceByIdParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/resources/{parameters.ResourceId}";
        return (await httpClient.GetFromJsonAsync<Resource>(url, cancellationToken))!;
    }

    public async Task DeleteResourceAsync(
        DeleteResourceParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/resources/{parameters.ResourceId}";
        var response = await httpClient.DeleteAsync(url, cancellationToken);
        response.EnsureSuccessStatusCode();
    }
}