// <auto-generated />
namespace VersioningHeader.Generated.Models;

public sealed record CreatePetRequest(
    [property: Required, MinLength(1), MaxLength(100)] string Name,
    [property: Required] string Species,
    string? Breed,
    [property: Range(0, long.MaxValue)] int Age,
    Guid? OwnerId);