// <auto-generated />
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: createUser.
/// </summary>
public sealed class CreateUserHandler : ICreateUserHandler
{
    public Task<CreateUserResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("createUser not implemented");
    }
}