// <auto-generated />
namespace Demo.Domain.Handlers;

/// <summary>
/// Handler for operation request.
/// Operation: deleteUserById.
/// </summary>
public sealed class DeleteUserByIdHandler : IDeleteUserByIdHandler
{
    public Task<DeleteUserByIdResult> ExecuteAsync(
        CancellationToken cancellationToken = default)
    {
        throw new NotImplementedException("deleteUserById not implemented");
    }
}