// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using ParameterSerialization.Generated.Items;

namespace ParameterSerialization.Generated;

/// <summary>
/// Extension methods for registering all ParameterSerialization API endpoints in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ParameterSerializationEndpointsServiceCollectionExtensions
{
    /// <summary>
    /// Registers all ParameterSerialization API endpoint implementations from all path segments.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddParameterSerializationEndpoints(this IServiceCollection services)
    {
        services.AddItemsEndpoints();

        return services;
    }
}