// <auto-generated />
#nullable enable
using ComponentsReuse.Generated.Handlers;
using Microsoft.Extensions.DependencyInjection;

namespace ComponentsReuse.Generated.DependencyInjection;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddComponentsReuseHandlers(this IServiceCollection services)
    {
        // Handler for IGetItemByIdHandler must be registered in the Domain project
        // services.AddScoped<IGetItemByIdHandler, YourImplementation>();
        // Handler for IListItemsHandler must be registered in the Domain project
        // services.AddScoped<IListItemsHandler, YourImplementation>();

        return services;
    }
}