// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;

using SecurityStandard.Generated.Security;

namespace SecurityStandard.Generated.Security;

/// <summary>
/// Extension methods for configuring API security policies.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class SecurityServiceCollectionExtensions
{
    /// <summary>
    /// Registers authorization policies for the API based on OpenAPI security requirements.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for method chaining.</returns>
    public static IServiceCollection AddApiSecurityPolicies(this IServiceCollection services)
    {
        services.AddAuthorization(options =>
        {
            options.AddPolicy(SecurityPolicies.Oauth2Admin, policy =>
                policy.RequireClaim("scope", "admin"));

            // Combined policy (AND logic - all scopes required)
            options.AddPolicy(SecurityPolicies.Oauth2AdminAndOrdersWrite, policy =>
                policy.RequireAssertion(context =>
                    context.User.HasClaim("scope", "admin") &&
                    context.User.HasClaim("scope", "orders:write")));

            options.AddPolicy(SecurityPolicies.Oauth2OrdersRead, policy =>
                policy.RequireClaim("scope", "orders:read"));

            options.AddPolicy(SecurityPolicies.Oauth2OrdersWrite, policy =>
                policy.RequireClaim("scope", "orders:write"));
        });

        return services;
    }
}