// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Atc.Rest.Client;
using Retry.Generated.Reports.Models;

namespace Retry.Generated.Reports.Client;

/// <summary>
/// Parameters for operation request.
/// Description: Generate report (no retry, long timeout).
/// Operation: GenerateReport.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GenerateReportParameters(
    [property: Required] ReportRequest Request);