// <auto-generated />
import type { AxiosResponse } from 'axios';
import { ApiClient } from './ApiClient';
import type { Resource, ResourceQuery } from '../models';

export type ListResourcesResult =
  | { status: 'ok'; data: Resource[]; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export type QueryResourcesResult =
  | { status: 'ok'; data: Resource[]; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export type LinkResourceResult =
  | { status: 'noContent'; response: AxiosResponse }
  | { status: 'parseError'; error: Error; response: AxiosResponse };

export class ResourcesClient {
  private readonly api: ApiClient;

  constructor(api: ApiClient) {
    this.api = api;
  }

  /** List resources */
  async listResources(): Promise<ListResourcesResult> {
    return this.api.request<Resource[]>('GET', '/resources') as Promise<ListResourcesResult>;
  }

  /** Query resources with a body */
  async queryResources(body: ResourceQuery): Promise<QueryResourcesResult> {
    return this.api.request<Resource[]>('QUERY', '/resources', {
      body,
    }) as Promise<QueryResourcesResult>;
  }

  /** Link a resource (custom verb) */
  async linkResource(): Promise<LinkResourceResult> {
    return this.api.request<void>('LINK', '/resources') as Promise<LinkResourceResult>;
  }
}