// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Builder;

using StreamingItemSchema.Generated.Events.Endpoints;
using StreamingItemSchema.Generated.EventsSse.Endpoints;

namespace StreamingItemSchema.Generated.Endpoints;

/// <summary>
/// Extension methods for mapping all API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointMappingExtensions
{
    /// <summary>
    /// Maps all API endpoints from all path segments.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>The web application for method chaining.</returns>
    public static WebApplication MapEndpoints(this WebApplication app)
    {
        app.MapEventsEndpoints();
        app.MapEventsSseEndpoints();

        return app;
    }
}