// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StreamingItemSchema.Generated.EventsSeq.Handlers;
using StreamingItemSchema.Generated.EventsSeq.Results;

namespace StreamingItemSchema.Generated.EventsSeq.Endpoints;

/// <summary>
/// Defines a contract for endpoint definitions.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEndpointDefinition
{
    /// <summary>
    /// Defines the endpoints for this definition.
    /// </summary>
    void DefineEndpoints(WebApplication app);
}

/// <summary>
/// Endpoint definitions for EventsSeq.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class EventsSeqEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/events-seq";

    public void DefineEndpoints(WebApplication app)
    {
        var eventsseq = app
            .MapGroup(ApiRouteBase)
            .WithTags("EventsSeq");

        eventsseq
            .MapGet("/", StreamEventsSeq)
            .WithName("StreamEventsSeq")
            .WithSummary("Stream events as a JSON text sequence")
            .Produces(StatusCodes.Status200OK, contentType: "application/json-seq")
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> StreamEventsSeq(
        [FromServices] IStreamEventsSeqHandler handler,
        CancellationToken cancellationToken)
        => StreamEventsSeqResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapEventsSeqEndpoints(this WebApplication app)
    {
        new EventsSeqEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}