// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;

namespace ModelsAndProperties.Generated.Models;

/// <summary>
/// Status enumeration.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public enum StatusType
{
    Draft,
    Pending,
    Active,
    Inactive,
    Archived,
    Deleted,
}