// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using ModelsAndProperties.Generated.Defaults.Models;
using ModelsAndProperties.Generated.Defaults.Results;

namespace ModelsAndProperties.Generated.Defaults.Handlers;


/// <summary>
/// Get default values model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetDefaultsHandler
{
    Task<GetDefaultsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}