// <auto-generated />
export interface Resource {
  /** Resource ID */
  readonly id: string;

  /** Resource name */
  readonly name: string;

  /** Owner user ID */
  readonly ownerId?: string;

  /** Creation timestamp */
  readonly createdAt?: string;
}