// <auto-generated />
namespace PetStoreSimple.Generated.Handlers;

/// <summary>
/// Create a pet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreatePetsHandler
{
    Task<CreatePetsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}