// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Generated.Handlers;

/// <summary>
/// Create and return the created model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateTestItemWithModelHandler
{
    System.Threading.Tasks.Task<CreateTestItemWithModelResult> ExecuteAsync(
        CreateTestItemWithModelParameters parameters,
        CancellationToken cancellationToken = default);
}