// <auto-generated />
namespace Demo.Generated.Handlers;

/// <summary>
/// Create and return the created model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateTestItemWithModelHandler
{
    System.Threading.Tasks.Task<CreateTestItemWithModelResult> ExecuteAsync(
        CreateTestItemWithModelParameters parameters,
        CancellationToken cancellationToken = default);
}