// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Store.Client;
using PetStoreFull.Generated.Store.Endpoints.Results;

namespace PetStoreFull.Generated.Store.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Delete purchase order by identifier.
/// Operation: DeleteOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeleteOrderEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<DeleteOrderEndpointResult> ExecuteAsync(
        DeleteOrderParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default);
}