// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Atc.Rest.Client;
using PetStoreFull.Generated;
using PetStoreFull.Generated.Store.Models;

namespace PetStoreFull.Generated.Store.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint Result.
/// Description: Place an order for a pet.
/// Operation: PlaceOrder.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IPlaceOrderEndpointResult : IEndpointResponse
{
    new bool IsOk { get; }

    bool IsBadRequest { get; }

    bool IsUnprocessableEntity { get; }

    bool IsConflict { get; }

    bool IsInternalServerError { get; }

    Order OkContent { get; }

    ValidationProblemDetails BadRequestContent { get; }

    ProblemDetails UnprocessableEntityContent { get; }

    ProblemDetails ConflictContent { get; }

    ProblemDetails InternalServerErrorContent { get; }
}