// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using VersioningHeader.Generated.Models;

namespace VersioningHeader.Generated.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: Update a pet.
/// Operation: UpdatePet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdatePetParameters(
    [property: FromRoute(Name = "petId"), Required] Guid PetId,
    [property: FromBody, Required] UpdatePetRequest Request);