// <auto-generated />
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MultipleServers.Generated.Items.Models;

namespace MultipleServers.Generated.Items.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: List items.
/// Operation: ListItems.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record ListItemsParameters(
    [property: FromQuery(Name = "limit"), DefaultValue(20)] int? Limit = 20);

/// <summary>
/// Parameters for operation request.
/// Description: Get item by ID.
/// Operation: GetItemById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetItemByIdParameters(
    [property: FromRoute(Name = "itemId"), Required] Guid ItemId);