// <auto-generated />
namespace ModelsAndProperties.Generated.Handlers;

/// <summary>
/// Create a new model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface ICreateModelHandler
{
    Task<CreateModelResult> ExecuteAsync(
        CreateModelParameters parameters,
        CancellationToken cancellationToken = default);
}