// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using DiscriminatorImprovements.Generated.Events.Models;

namespace DiscriminatorImprovements.Generated.Events.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEventsClient
{
    Task<List<Event>> ListEventsAsync(CancellationToken cancellationToken = default);
}