// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using VersioningHeader.Generated.Pets.Client;
using VersioningHeader.Generated.Pets.Endpoints.Results;

namespace VersioningHeader.Generated.Pets.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Delete a pet
/// Operation: DeletePet.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IDeletePetEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<DeletePetEndpointResult> ExecuteAsync(
        DeletePetParameters parameters,
        string httpClientName = "VersioningHeader-ApiClient",
        CancellationToken cancellationToken = default);
}