// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using StreamingItemSchema.Generated.Models;
using StreamingItemSchema.Generated.Streaming;

namespace StreamingItemSchema.Generated.Events.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class EventsClient : IEventsClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public EventsClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public EventsClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async IAsyncEnumerable<Event> StreamEventsAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var url = "/events";
        using var response = await httpClient.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);

        await foreach (var item in StreamReaders.ReadJsonLinesAsync<Event>(stream, jsonSerializerOptions, cancellationToken))
        {
            if (item is not null)
            {
                yield return item;
            }
        }
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}