// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using StreamingItemSchema.Generated.Models;
using StreamingItemSchema.Generated.Streaming;

namespace StreamingItemSchema.Generated.EventsSeq.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IEventsSeqClient
{
    IAsyncEnumerable<Event> StreamEventsSeqAsync(CancellationToken cancellationToken = default);
}