// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace SecurityHybrid.Generated.Orders.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record GetOrderTrackingResponse(
    string OrderId,
    string Status,
    string Location);