// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using AnyOfNoDiscriminator.Generated.Models;
using Microsoft.AspNetCore.Mvc;

namespace AnyOfNoDiscriminator.Generated.Parameters;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record CreateShapeParameters(
    [property: FromBody, Required] Shape Request);