// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using MultipleServers.Generated.Models;
using MultipleServers.Generated.Parameters;
using MultipleServers.Generated.Results;

namespace MultipleServers.Generated.Handlers;

/// <summary>
/// Get item by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetItemByIdHandler
{
    Task<GetItemByIdResult> ExecuteAsync(
        GetItemByIdParameters parameters,
        CancellationToken cancellationToken = default);
}