// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using SecurityOpenIdConnect.Generated;
using SecurityOpenIdConnect.Generated.Resources.Endpoints.Interfaces;
using SecurityOpenIdConnect.Generated.Resources.Endpoints.Results;
using SecurityOpenIdConnect.Generated.Resources.Models;
using SecurityOpenIdConnect.Generated.Resources.Client;

namespace SecurityOpenIdConnect.Generated.Resources.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Create a new resource
/// Operation: CreateResource.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class CreateResourceEndpoint : ICreateResourceEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public CreateResourceEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<CreateResourceEndpointResult> ExecuteAsync(
        CreateResourceParameters parameters,
        string httpClientName = "SecurityOpenIdConnect-ApiClient",
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/resources");
        requestBuilder.WithBody(parameters.Request);

        using var requestMessage = requestBuilder.Build(HttpMethod.Post);
        using var response = await client.SendAsync(requestMessage, cancellationToken);

        var responseBuilder = httpMessageFactory.FromResponse(response);
        responseBuilder.AddSuccessResponse<Resource>(HttpStatusCode.Created);
        responseBuilder.AddErrorResponse<ValidationProblemDetails>(HttpStatusCode.BadRequest);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Unauthorized);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Forbidden);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.Conflict);
        responseBuilder.AddErrorResponse<ProblemDetails>(HttpStatusCode.InternalServerError);
        return await responseBuilder.BuildResponseAsync(x => new CreateResourceEndpointResult(x), cancellationToken);
    }
}