// <auto-generated />
namespace Demo.Generated.Models;

public record User(
    [property: Required] Guid Id,
    [property: Required, MinLength(2), MaxLength(50)] string FirstName,
    [property: Required, MinLength(2), MaxLength(50)] string LastName,
    [property: Required, MaxLength(254), EmailAddress] string Email,
    [property: RegularExpression(@"^\+?[1-9]\d{6,14}$")] string? Phone,
    [property: MaxLength(2048)] Uri? Website,
    [property: Required] DateTimeOffset DateOfBirth,
    [property: Range(0, 150)] int Age,
    [property: MaxLength(1000)] string? Bio,
    Uri? AvatarUrl,
    [property: Required] UserRole Role,
    [property: Required] Address Address,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    bool IsActive = true);