// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using InlineSchemas.Generated.Reports.Endpoints.Results;

namespace InlineSchemas.Generated.Reports.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all reports
/// Operation: ListReports.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListReportsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListReportsEndpointResult> ExecuteAsync(
        string httpClientName = "InlineSchemas-ApiClient",
        CancellationToken cancellationToken = default);
}