// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Builder;

namespace SecurityStandard.Generated.Endpoints;

/// <summary>
/// Extension methods for mapping API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointDefinitionExtensions
{
    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapAdminEndpoints(this WebApplication app)
    {
        new AdminEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapDataEndpoints(this WebApplication app)
    {
        new DataEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapOrdersEndpoints(this WebApplication app)
    {
        new OrdersEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapPublicEndpoints(this WebApplication app)
    {
        new PublicEndpointDefinition().DefineEndpoints(app);

        return app;
    }

    /// <summary>
    /// Maps all API endpoints from the generated endpoint definitions.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>
    /// The web application for method chaining.
    /// </returns>
    public static WebApplication MapUsersEndpoints(this WebApplication app)
    {
        new UsersEndpointDefinition().DefineEndpoints(app);

        return app;
    }
}