// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SecurityStandard.Generated.Public.Handlers;
using SecurityStandard.Generated.Public.Models;
using SecurityStandard.Generated.Public.Results;

namespace SecurityStandard.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Public.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class PublicEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/public";

    public void DefineEndpoints(WebApplication app)
    {
        var public = app
            .MapGroup(ApiRouteBase)
            .WithTags("Public");

        public
            .MapGet("health", GetHealth)
            .WithName("GetHealth")
            .WithSummary("Health check (public)")
            .Produces<HealthStatus>()
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout)
            .AllowAnonymous();
    }

    internal async Task<IResult> GetHealth(
        [FromServices] IGetHealthHandler handler,
        CancellationToken cancellationToken)
        => GetHealthResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}