// <auto-generated />
namespace InlineSchemas.Generated.Reports.Models;

public sealed record GetReportResponse(
    [property: Required] string Id,
    [property: Required] string Name,
    string Content,
    string Status,
    object Metadata);