// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.AspNetCore.Builder;

using NonJsonContent.Generated.Exports.Endpoints;
using NonJsonContent.Generated.Files.Endpoints;
using NonJsonContent.Generated.Items.Endpoints;
using NonJsonContent.Generated.Reports.Endpoints;

namespace NonJsonContent.Generated.Endpoints;

/// <summary>
/// Extension methods for mapping all API endpoints.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class EndpointMappingExtensions
{
    /// <summary>
    /// Maps all API endpoints from all path segments.
    /// </summary>
    /// <param name="app">The web application.</param>
    /// <returns>The web application for method chaining.</returns>
    public static WebApplication MapEndpoints(this WebApplication app)
    {
        app.MapExportsEndpoints();
        app.MapFilesEndpoints();
        app.MapItemsEndpoints();
        app.MapReportsEndpoints();

        return app;
    }
}