// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NonJsonContent.Generated.Exports.Handlers;
using NonJsonContent.Generated.Exports.Results;

namespace NonJsonContent.Generated.Endpoints;

/// <summary>
/// Endpoint definitions for Exports.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class ExportsEndpointDefinition : IEndpointDefinition
{
    internal const string ApiRouteBase = "/exports";

    public void DefineEndpoints(WebApplication app)
    {
        var exports = app
            .MapGroup(ApiRouteBase)
            .WithTags("Exports");

        exports
            .MapGet("csv", ExportCsv)
            .WithName("ExportCsv")
            .WithSummary("Export data as CSV")
            .Produces<string>(StatusCodes.Status200OK, contentType: "text/csv")
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .ProducesProblem(StatusCodes.Status504GatewayTimeout);
    }

    internal async Task<IResult> ExportCsv(
        [FromServices] IExportCsvHandler handler,
        CancellationToken cancellationToken)
        => ExportCsvResult.ToIResult(
                    await handler.ExecuteAsync(
                        cancellationToken));
}