// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Polymorphism.Generated.Notifications.Endpoints.Results;

namespace Polymorphism.Generated.Notifications.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: List all notifications
/// Operation: ListNotifications.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListNotificationsEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<ListNotificationsEndpointResult> ExecuteAsync(
        string httpClientName = "Polymorphism-ApiClient",
        CancellationToken cancellationToken = default);
}