// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Pets.Client;
using PetStoreFull.Generated.Pets.Endpoints.Results;

namespace PetStoreFull.Generated.Pets.Endpoints.Interfaces;

/// <summary>
/// Interface for Client Endpoint.
/// Description: Find pet by ID.
/// Operation: GetPetById.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetPetByIdEndpoint
{
    /// <summary>
    /// Execute method.
    /// </summary>
    Task<GetPetByIdEndpointResult> ExecuteAsync(
        GetPetByIdParameters parameters,
        string httpClientName = "PetStoreFull-ApiClient",
        CancellationToken cancellationToken = default);
}