namespace Showcase.BlazorApp.Services;

/// <summary>
/// Gateway service for API operations using generated endpoints.
/// This is a partial class split into files per first-path-segment.
/// Fields and constructor are auto-generated by the EndpointRegistration attribute.
/// </summary>
[EndpointRegistration("Showcase")]
public sealed partial class GatewayService
{
    private readonly JsonSerializerOptions jsonOptions = Atc.Serialization.JsonSerializerOptionsFactory.Create();
}