// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using ModelsAndProperties.Generated.Models;
using ModelsAndProperties.Generated.Parameters;
using ModelsAndProperties.Generated.Results;

namespace ModelsAndProperties.Generated.Handlers;

/// <summary>
/// Get array types model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetArrayTypesHandler
{
    Task<GetArrayTypesResult> ExecuteAsync(CancellationToken cancellationToken = default);
}