// <auto-generated />
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace SecurityStandard.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record Order(
    [property: Required] Guid Id,
    [property: Required] string CustomerId,
    [property: Required] string Status,
    double TotalAmount,
    DateTimeOffset CreatedAt);