// <auto-generated />
import { ApiClient, type ApiClientOptions } from './ApiClient';
import { ResourcesClient } from './ResourcesClient';

export class ApiService {
  readonly resources: ResourcesClient;

  constructor(baseUrl: string, options?: ApiClientOptions) {
    const api = new ApiClient(baseUrl, options);
    this.resources = new ResourcesClient(api);
  }
}