// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using CookieParameters.Generated.Models;

namespace CookieParameters.Generated.Client;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class CookieParametersClient
{
    private static readonly JsonSerializerOptions defaultJsonSerializerOptions = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
        Converters = { new JsonStringEnumConverter() },
    };

    private readonly HttpClient httpClient;
    private readonly JsonSerializerOptions jsonSerializerOptions;

    public CookieParametersClient(
        HttpClient httpClient)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = defaultJsonSerializerOptions;
    }

    public CookieParametersClient(
        HttpClient httpClient,
        JsonSerializerOptions jsonSerializerOptions)
    {
        this.httpClient = httpClient;
        this.jsonSerializerOptions = jsonSerializerOptions;
    }

    public async Task<Session> GetSessionAsync(
        GetSessionParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = "/session";
        return (await httpClient.GetFromJsonAsync<Session>(url, jsonSerializerOptions, cancellationToken))!;
    }

    public async Task TrackEventAsync(
        TrackEventParameters parameters,
        CancellationToken cancellationToken = default)
    {
        var url = $"/tracking/{Uri.EscapeDataString(parameters.EventId)}";
        var response = await httpClient.PostAsync(url, null, cancellationToken);
        await EnsureSuccessAsync(response, cancellationToken);
    }

    private static async System.Threading.Tasks.Task EnsureSuccessAsync(
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        if (response.IsSuccessStatusCode)
        {
            return;
        }

        var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
        throw new HttpRequestException(
            $"HTTP {(int)response.StatusCode} ({response.ReasonPhrase}): {errorContent}",
            inner: null,
            response.StatusCode);
    }
}