// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using PetStoreFull.Generated.Models;
using PetStoreFull.Generated.Parameters;
using PetStoreFull.Generated.Results;

namespace PetStoreFull.Generated.Handlers;

/// <summary>
/// Finds Pets by status.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IFindPetsByStatusHandler
{
    Task<FindPetsByStatusResult> ExecuteAsync(
        FindPetsByStatusParameters parameters,
        CancellationToken cancellationToken = default);
}