// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CachingHybrid.Generated.Models;
using Microsoft.AspNetCore.Mvc;

namespace CachingHybrid.Generated.Parameters;

/// <summary>
/// Parameters for operation request.
/// Description: Update user (no caching).
/// Operation: UpdateUser.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record UpdateUserParameters(
    [property: FromRoute(Name = "userId"), Required] Guid UserId,
    [property: FromBody, Required] UpdateUserRequest Request);