// <auto-generated />
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace DiscriminatorImprovements.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record OrderPlacedEvent : Event(
    [property: Required] string EventType,
    [property: Required] Guid OrderId);