// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client;
using Atc.Rest.Client.Builder;
using Microsoft.Extensions.Http;
using StreamingItemSchema.Generated;
using StreamingItemSchema.Generated.Streaming;
using StreamingItemSchema.Generated.EventsSse.Endpoints.Interfaces;
using StreamingItemSchema.Generated.EventsSse.Models;

namespace StreamingItemSchema.Generated.EventsSse.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Stream events as server-sent events
/// Operation: StreamEventsSse.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class StreamEventsSseEndpoint : IStreamEventsSseEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;

    public StreamEventsSseEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
    }

    public async Task<StreamingEndpointResponse<Event>> ExecuteAsync(
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/events-sse");

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        var response = await client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
            return new StreamingEndpointResponse<Event>(false, response.StatusCode, content: null, errorContent, response);
        }

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        var serializerOptions = new JsonSerializerOptions(JsonSerializerDefaults.Web);
        var content = StreamReaders.ReadServerSentEventsAsync<Event>(stream, serializerOptions, cancellationToken);
        return new StreamingEndpointResponse<Event>(true, response.StatusCode, content, errorContent: null, response);
    }
}