// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Atc.Rest.Client;
using Atc.Rest.Client.Builder;
using Atc.Rest.Client.Serialization;
using Microsoft.Extensions.Http;
using StreamingItemSchema.Generated;
using StreamingItemSchema.Generated.Streaming;
using StreamingItemSchema.Generated.EventsSeq.Endpoints.Interfaces;
using StreamingItemSchema.Generated.EventsSeq.Models;

namespace StreamingItemSchema.Generated.EventsSeq.Endpoints;

/// <summary>
/// Client Endpoint.
/// Description: Stream events as a JSON text sequence
/// Operation: StreamEventsSeq.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class StreamEventsSeqEndpoint : IStreamEventsSeqEndpoint
{
    private readonly IHttpClientFactory factory;
    private readonly IHttpMessageFactory httpMessageFactory;
    private readonly IContractSerializer contractSerializer;

    public StreamEventsSeqEndpoint(
        IHttpClientFactory factory,
        IHttpMessageFactory httpMessageFactory,
        IContractSerializer contractSerializer)
    {
        this.factory = factory;
        this.httpMessageFactory = httpMessageFactory;
        this.contractSerializer = contractSerializer;
    }

    public async Task<StreamingEndpointResponse<Event>> ExecuteAsync(
        string httpClientName = Constants.HttpClientName,
        CancellationToken cancellationToken = default)
    {
        var client = factory.CreateClient(httpClientName);

        var requestBuilder = httpMessageFactory.FromTemplate("/events-seq");

        using var requestMessage = requestBuilder.Build(HttpMethod.Get);
        var response = await client.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
            return new StreamingEndpointResponse<Event>(false, response.StatusCode, content: null, errorContent, response);
        }

        var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        var content = StreamReaders.ReadJsonSequenceAsync<Event>(stream, contractSerializer, cancellationToken);
        return new StreamingEndpointResponse<Event>(true, response.StatusCode, content, errorContent: null, response);
    }
}