// <auto-generated />
namespace VersioningHeader.Generated.Handlers;

/// <summary>
/// Get an owner by ID.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetOwnerByIdHandler
{
    Task<GetOwnerByIdResult> ExecuteAsync(
        GetOwnerByIdParameters parameters,
        CancellationToken cancellationToken = default);
}