// <auto-generated />
namespace VersioningHeader.Generated.Handlers;

/// <summary>
/// List all owners.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListOwnersHandler
{
    Task<ListOwnersResult> ExecuteAsync(CancellationToken cancellationToken = default);
}