// <auto-generated />
namespace ModelsAndProperties.Generated.Models;

public sealed record ValidationConstraints(
    [property: Required] string RequiredString,
    [property: Required] int RequiredInteger,
    [property: MinLength(5)] string MinLengthString,
    [property: MaxLength(100)] string MaxLengthString,
    [property: MinLength(2), MaxLength(50)] string LengthRangeString,
    [property: RegularExpression(@"^[A-Z]{2,3}$")] string PatternString,
    [property: RegularExpression(@"^\+?[1-9]\d{6,14}$")] string PhonePattern,
    [property: RegularExpression(@"^[a-zA-Z0-9_-]+$")] string AlphanumericPattern,
    [property: Range(0, long.MaxValue)] int MinInteger,
    [property: Range(long.MinValue, 100)] int MaxInteger,
    [property: Range(1, 1000)] int RangeInteger,
    [property: Range(0, double.MaxValue)] double MinNumber,
    [property: Range(double.MinValue, 99.99)] double MaxNumber,
    [property: Range(-180, 180)] double RangeNumber,
    [property: Range(0.01, 999999.99)] double PriceValue,
    [property: Range(1000000000, 9999999999999)] long LargeLong);