// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using AnyOfNoDiscriminator.Generated.Models;
using AnyOfNoDiscriminator.Generated.Parameters;
using AnyOfNoDiscriminator.Generated.Results;

namespace AnyOfNoDiscriminator.Generated.Handlers;

/// <summary>
/// List notifications of mixed types.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListNotificationsHandler
{
    Task<ListNotificationsResult> ExecuteAsync(CancellationToken cancellationToken = default);
}