// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using Demo.Generated.Models;
using Demo.Generated.Parameters;
using Demo.Generated.Results;

namespace Demo.Generated.Handlers;

/// <summary>
/// List all users.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IListUsersHandler
{
    System.Threading.Tasks.Task<ListUsersResult> ExecuteAsync(
        ListUsersParameters parameters,
        CancellationToken cancellationToken = default);
}