// <auto-generated />
using System;
using System.CodeDom.Compiler;
using System.ComponentModel.DataAnnotations;

namespace SecurityAtcExt.Generated.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed record TrackingInfo(
    [property: Required] Guid OrderId,
    [property: Required] string Status,
    string Location,
    DateTimeOffset LastUpdated);