// <auto-generated />
import type { AddressRequest } from './AddressRequest';
import type { UserRole } from '../enums/UserRole';

export interface CreateUserRequest {
  readonly firstName: string;

  readonly lastName: string;

  readonly email: string;

  readonly phone?: string | null;

  readonly website?: string | null;

  readonly dateOfBirth: string;

  readonly bio?: string | null;

  readonly avatarUrl?: string | null;

  readonly isActive?: boolean;

  readonly role: UserRole;

  readonly address: AddressRequest;
}