// <auto-generated />
export interface PaginatedResult {
  readonly pageSize?: number;

  readonly pageIndex?: number;

  readonly queryString?: string | null;

  readonly continuation?: string | null;

  readonly count?: number;

  readonly totalCount?: number;

  readonly results?: unknown[];
}