// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Threading;
using System.Threading.Tasks;
using StreamingItemSchema.Generated.EventsSeq.Results;

namespace StreamingItemSchema.Generated.EventsSeq.Handlers;


/// <summary>
/// Stream events as a JSON text sequence.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IStreamEventsSeqHandler
{
    Task<StreamEventsSeqResult> ExecuteAsync(CancellationToken cancellationToken = default);
}