// <auto-generated />
namespace Polymorphism.Generated.Models;

/// <summary>
/// Polymorphic base type (anyOf) with discriminator property 'kind'.
/// Note: Discriminator was auto-detected from common properties.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
[JsonPolymorphic(TypeDiscriminatorPropertyName = "kind")]
[JsonDerivedType(typeof(EmailNotification), "email_notification")]
[JsonDerivedType(typeof(SmsNotification), "sms_notification")]
[JsonDerivedType(typeof(PushNotification), "push_notification")]
public abstract record Notification;