name: "Post-Integration"

on:
  push:
    branches:
      - main
      - '!stable'
      - '!release'

env:
  ATC_EMAIL: 'atcnet.org@gmail.com'
  ATC_NAME: 'Atc-Net'
  NUGET_REPO_URL: 'https://nuget.pkg.github.com/atc-net/index.json'
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  merge-to-stable:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_WORKFLOWS }}

      - name: ⚛️ Setup Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.5.2
        with:
          setAllVars: true

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: 🧹 Clean
        run: dotnet clean Atc.Rest.Api.SourceGenerator.slnx -c Release && dotnet nuget locals all --clear

      - name: 🔁 Restore packages
        run: dotnet restore Atc.Rest.Api.SourceGenerator.slnx

      - name: 🛠️ Build solution
        run: dotnet build Atc.Rest.Api.SourceGenerator.slnx -c Release --no-restore /p:UseSourceLink=true

      - name: 🧪 Run unit tests
        run: dotnet test --solution Atc.Rest.Api.SourceGenerator.slnx -c Release --no-build --filter-not-trait "Category=Integration" --ignore-exit-code 8

      - name: ⏩ Merge to stable branch
        run: |
          git config --local user.email ${{ env.ATC_EMAIL }}
          git config --local user.name ${{ env.ATC_NAME }}
          git checkout stable
          git merge --ff-only main
          git push origin stable

      - name: 🗳️ Creating library package for pre-release
        run: |
          dotnet pack src/Atc.Rest.Api.SourceGenerator/Atc.Rest.Api.SourceGenerator.csproj \
            -c Release \
            -o ${GITHUB_WORKSPACE}/packages \
            -p:RepositoryBranch=$BRANCH_NAME \
            -p:ContinuousIntegrationBuild=true \
            -p:Version=${NBGV_NuGetPackageVersion}
          dotnet pack src/Atc.Rest.Api.Generator.Cli/Atc.Rest.Api.Generator.Cli.csproj \
            -c Release \
            -o ${GITHUB_WORKSPACE}/packages \
            -p:RepositoryBranch=$BRANCH_NAME \
            -p:ContinuousIntegrationBuild=true \
            -p:Version=${NBGV_NuGetPackageVersion}

      - name: 📦 Push packages to GitHub Package Registry
        run: |
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/Atc.Rest.Api.SourceGenerator.${NBGV_NuGetPackageVersion}.nupkg \
            -k ${{ secrets.GITHUB_TOKEN }} \
            -s ${{ env.NUGET_REPO_URL }} \
            --skip-duplicate
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/atc-rest-api-gen.${NBGV_NuGetPackageVersion}.nupkg \
            -k ${{ secrets.GITHUB_TOKEN }} \
            -s ${{ env.NUGET_REPO_URL }} \
            --skip-duplicate
