// <auto-generated />
namespace ModelsAndProperties.Generated.Handlers;

/// <summary>
/// Get nullable types model.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public interface IGetNullablesHandler
{
    Task<GetNullablesResult> ExecuteAsync(CancellationToken cancellationToken = default);
}