// <auto-generated />
#nullable enable
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Json;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace StreamingItemSchema.Generated.Streaming;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class SequentialStreamWriter
{
    private static readonly byte[] LineFeed = { (byte)'\n' };

    public static async Task WriteJsonLinesAsync<T>(
        IAsyncEnumerable<T> items,
        Stream stream,
        JsonSerializerOptions options,
        CancellationToken cancellationToken)
    {
        await foreach (var item in items.WithCancellation(cancellationToken))
        {
            await JsonSerializer.SerializeAsync(stream, item, options, cancellationToken);
            await stream.WriteAsync(LineFeed, cancellationToken);
            await stream.FlushAsync(cancellationToken);
        }
    }
}

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public sealed class JsonLinesResult<T> : IResult
{
    private readonly IAsyncEnumerable<T> items;

    public JsonLinesResult(IAsyncEnumerable<T> items)
        => this.items = items;

    public async Task ExecuteAsync(HttpContext httpContext)
    {
        httpContext.Response.ContentType = "application/jsonl";
        var options = httpContext.RequestServices
            .GetRequiredService<IOptions<JsonOptions>>()
            .Value.SerializerOptions;
        await SequentialStreamWriter.WriteJsonLinesAsync(items, httpContext.Response.Body, options, httpContext.RequestAborted);
    }
}