// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace PetStoreFull.Generated.Pet.Models;

[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FindPetsByStatusParametersStatus
{
    [EnumMember(Value = "available")]
    Available,

    [EnumMember(Value = "pending")]
    Pending,

    [EnumMember(Value = "sold")]
    Sold,
}