// <auto-generated />
#nullable enable

using System.CodeDom.Compiler;
using Microsoft.Extensions.DependencyInjection;
using SecurityStandard.Generated.Admin.Handlers;
using SecurityStandard.Generated.Data.Handlers;
using SecurityStandard.Generated.Orders.Handlers;
using SecurityStandard.Generated.Public.Handlers;
using SecurityStandard.Generated.Users.Handlers;

namespace SecurityStandard;

/// <summary>
/// Extension methods for registering API handlers in the dependency injection container.
/// </summary>
[GeneratedCode("Atc.Rest.Api.SourceGenerator", "1.0.0")]
public static class ApiHandlerServiceCollectionExtensions
{
    /// <summary>
    /// Registers all API handler implementations from this assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>
    /// The service collection for method chaining.
    /// </returns>
    public static IServiceCollection AddApiHandlersFromSecurityStandard(this IServiceCollection services)
    {
        services.AddScoped<ICreateOrderHandler, global::SecurityStandard.ApiHandlers.CreateOrderHandler>();
        services.AddScoped<IDeleteOrderHandler, global::SecurityStandard.ApiHandlers.DeleteOrderHandler>();
        services.AddScoped<IGetAdminSettingsHandler, global::SecurityStandard.ApiHandlers.GetAdminSettingsHandler>();
        services.AddScoped<IGetDataHandler, global::SecurityStandard.ApiHandlers.GetDataHandler>();
        services.AddScoped<IGetHealthHandler, global::SecurityStandard.ApiHandlers.GetHealthHandler>();
        services.AddScoped<IGetOrderByIdHandler, global::SecurityStandard.ApiHandlers.GetOrderByIdHandler>();
        services.AddScoped<IGetUserByIdHandler, global::SecurityStandard.ApiHandlers.GetUserByIdHandler>();
        services.AddScoped<IListOrdersHandler, global::SecurityStandard.ApiHandlers.ListOrdersHandler>();
        services.AddScoped<IListUsersHandler, global::SecurityStandard.ApiHandlers.ListUsersHandler>();
        services.AddScoped<IUpdateAdminSettingsHandler, global::SecurityStandard.ApiHandlers.UpdateAdminSettingsHandler>();

        return services;
    }
}